### ISSUE TITLE
Throw when PurgeOnStartup is requested

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#100]
PurgeOnStartup is not supported by ASB, we should throw when it's requested

**Comment by melkio** [comment]
Why do we not simulate the same behavior (purging) receiving and discarding all messages? 
Inside a while loop we can check if a new message exists (peek) and receive/discard it (with ReceiveMode.ReceiveAndDelete)

**Comment by yvesgoeleven** [comment]
@melkio upgrades are typically done in a running state, which means that something can still be sending to those queues, you would be purging forever, throwing messages away

**Comment by melkio** [comment]
Makes sense :+1: 
Is there a "delivery timestamp" header or something else inside the message? We could drop only messages deliverered before purging starts.

It's only to give the same "experience" across different transports

**Comment by melkio** [comment]
For deferred messages: how does other transport behave with scheduled messages? If a message isn't inside the queue when purging, this message will be delivered to the queue later, and then it's not deleted. I'm pretty sure that Rabbit works in this way or am I wrong?

**Comment by yvesgoeleven** [comment]
You could use EnqueuedTimeUtc property as a time indicator of when it was put on the queue. But messages can be 'invisible' in the queue, when either locked or defered, or in a session, etc... so you will not be able to see them, let alone purge them.

**Comment by yvesgoeleven** [comment]
I do not know how rabbit does it, maybe ask @bording

**Comment by yvesgoeleven** [comment]
PS: in case of deferrral, I think EnqueuedTimeUtc will change when it becomes visible on the queue

**Comment by SeanFeldman** [comment]
The underlying technology doesn't support purging natively. By saying "we can purge", we are introducing failure points where we won't purge all messages, but customers will make assumption that we do. Therefore I see this is something we shouldn't implement, unless native API provides a way.

**Comment by SeanFeldman** [comment]
Another problematic scenario -- code might be configured _not_ to create queues. In that case we'll be deleting queues w/o ability to re-create?

**Comment by SeanFeldman** [comment]
@melkio please update the general description with what's left and either close it or move back if needed. Thank you.

**Comment by melkio** [comment]
Closed by https://github.com/Particular/NServiceBus.AzureServiceBus/issues/109
