### ISSUE TITLE
Match RequiredConsistency with settings

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#101]
Match and validate `RequiredConsistency` with the actual settings from the core + ASB config impacting it, throw an exception if not compatible

**Comment by SeanFeldman** [comment]
@yvesgoeleven could you please list the participants in this decision making

**Comment by yvesgoeleven** [comment]
From the top of my head

- ReceiveMode
- SendVia
- Namespaces
