### ISSUE TITLE
Implement passive namespace fallback

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#103]
Only active namespaces are used now for sending messages, implement fallback to passive if the active ones didn't work

**Comment by mauroservienti** [comment]
In today sync was asked if this is mandatory for V6 or can be release as an update to V6.
Also @Particular/platform-dev-squad this is in progress but is lacking a proper task force.

**Comment by yvesgoeleven** [comment]
@mauroservienti relabled as bug, the work for this had already been done as part of the multi namespace support, but wasn't verified yet, now it is.

**Comment by yvesgoeleven** [comment]
@Particular/azure-maintainers PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/129 ready for review

**Comment by yvesgoeleven** [comment]
@Particular/azure-maintainers note: for local testing you need an additional environment variable containing a fallback namespace, build server has these already
