### ISSUE TITLE
Validate CriticalError behavior

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#104]
There are quite a few TODO's in the code and ATT's related to the fact that critical error is no longer passed in to the messagepump factory, figure out what these are there for and if the critical error behavior is still working as expected

**Comment by tmasternak** [comment]
>  figure out what these are there for and if the critical error behavior is still working as expected

The transport should call the `CriticalError` if the func passed to `Init` in `MessagePump` throws an exception. Looking at the code of `MessagePump` and `TopologyOperator` that does not seem to be the case. Here is a sample from [MSMQ](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L114) than might be helpful. It triggers `CircutBreaker` first which in turn results in `CriticalError` [invocation](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L32).

**Comment by yvesgoeleven** [comment]
@tmasternak we reviewed it, and it does work as expected (covered by this test https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Tests/Topology/Operation/When_operating_EndpointOrientedTopology.cs#L200).

What we do is register the `CriticalError` behavior into the `OnMessage` and `OnError` callbacks that we pass into the ASB SDK. This one triggeres when there is an exception occuring in the processing of a message (as proven by the test above) as well when there is a problem in the asb sdk itself.

So it will work fine.

**Comment by tmasternak** [comment]
> So it will work fine.

:+1:
