### ISSUE TITLE
Endurance test Forwarding topology with a long running process

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#106]
Similar to #76

**Comment by SeanFeldman** [comment]
@boblangley this one will ove to https://github.com/Particular/EndToEnd/issues/2 as well?

**Comment by boblangley** [comment]
@SeanFeldman Yes. I am closing this and updating the description of https://github.com/Particular/EndToEnd/issues/2 to make sure it includes this scope.
