### ISSUE TITLE
Configure Publisher Names

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#115]
Provide capability to configure publisher names at the transport level (where we used endpoint mappings in the past). Ensure this is mandatory for StandardTopology if there are subscriptions.

**Comment by SeanFeldman** [comment]
i.e. add some sort of endpoint mapping via code for `StandardTopology` to utilize.

**Comment by SeanFeldman** [comment]
Discussed this with @bording `UnicastRoutingTable` contains that information, why can't we make it public @SzymonPobiega?

**Comment by SzymonPobiega** [comment]
Well, we can but I think what you need is the `Publishers` collection rather than `URT`. @SeanFeldman start a PR and let @Particular/nservicebus-maintainers comment on that. @yvesgoeleven and @andreasohlund were discussing that on a call but I don't remember what was the outcome.

**Comment by SeanFeldman** [comment]
@melkio @yvesgoeleven please update issue with the outcome of the discussion

**Comment by yvesgoeleven** [comment]
@SeanFeldman result is in the top description :)

**Comment by SeanFeldman** [comment]
When `StandardTopology` is used, the Publishers for a subscribing endpoint **must** be configured.
When subscription is taking place and a publisher is not found in the list of the registered ones, what should be the expected behaviour? Assuming logging and throwing an exception (endpoint is expected to handle an event and it can't, critical error)?

**Comment by SzymonPobiega** [comment]
I think that failure to subscribe on a native pub/sub transport should result in a critical error.

**Comment by andreasohlund** [comment]
>I think that failure to subscribe on a native pub/sub transport should result in a critical error.

At least on rabbit failing to subscribe will cause an ex to be thrown from `.Subscribe` and that would cause the startup to fail. (we need to check how this behaves together with autosubscribe but I think it would prevent the endpoint from starting)

Is that what you are after @SzymonPobiega ?

**Comment by SzymonPobiega** [comment]
@andreasohlund Initially I thought that if you call `endpoint.Subscribe` while the endpoint is running we should raise a critical error but now I am not so such. If a failure in autosubscribe prevents an endpoint from starting that seems good enough. And when I subscribe in runtime it might be better to not raise a critical but rather use a normal exception and let the user decide if he wants to kill the endpoint or not.

**Comment by andreasohlund** [comment]
:+1: 

Also subscribing at runtime should be rare (smart client?) and in those cases it seems reasonable for the user to decide what to do in case of a failure

**Comment by yvesgoeleven** [comment]
@andreasohlund @SzymonPobiega from a transport implementation perspective, it cannot differentiate between autosubscribe, manual subscribe at startup or subscribe at runtime, we need a single clear behavior.

**Comment by SzymonPobiega** [comment]
@yvesgoeleven sure. I believe the transport should throw and the austosubscribe feature should make sure it fails a startup procedure if it gets an exception.

**Comment by andreasohlund** [comment]
:+1:

**Comment by melkio** [comment]
I'm trying to work on this issue, but something it's not clear to me.
> add some sort of endpoint mapping via code for StandardTopology to utilize

I did it in this way:

```c#
extensions.UseDefaultTopology()
    .RegisterPublisherFor<MyEvent>("publisher1")
    .RegisterPublisherFor<MyEvent>("publisher2");
```

But this configuration is completely unnatural, from the users perspective (IMO)
We are giving to users the responsability to configure mapping between event type and publishers name. For me is wrong: users can do mistakes in this phase and transport will not work.
Furthemore `core` has already this configuration. Why does transport have to replicate the same behaviours? Why not to use the same component already configured and ready to use? It isn't a simple mapping, but transport has to resolve event hierarchy i.e.

It doesn't make sense for me.

IMO it's better the current solution (with this hack: https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/Topologies/StandardTopologySectionManager.cs#L201)

@yvesgoeleven @SeanFeldman @andreasohlund @SzymonPobiega maybe we need to discuss more on possible solutions

**Comment by SzymonPobiega** [comment]
@melkio the core has the `Publishers` collection which has a slightly different purpose as it was meant to be used for message-driven pub/sub only. As we are seriously considering implementing native pub sub in all transports that currently have message-driven pub sub, the `Publishers` might get dropped in V7 entirely.

The ideas in ASB is that in the legacy topology the name of the topic included the name of the publisher (if I understand correctly). That's why this mapping is happening on ASB level (rather than core level).

**Comment by SeanFeldman** [comment]
> As we are seriously considering implementing native pub sub in all transports that currently have message-driven pub sub

You lost me with this @SzymonPobiega. Where can I find more info on this?

**Comment by SzymonPobiega** [comment]
@SeanFeldman https://github.com/Particular/PlatformDevelopment/issues/664

Not gonna happen as part of V6, but we have a complete set of spikes that prove it can be done. The problem to solve is how to deal with wire compat.

**Comment by yvesgoeleven** [comment]
@melkio just go ahead implementing the API we have foreseen to replace publishers

**Comment by yvesgoeleven** [comment]
PR Merged
