### ISSUE TITLE
Remove ForwardTo on all entities

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#117]
Have ran into this while working on https://github.com/Particular/NServiceBus.AzureServiceBus/issues/13. As part of the `ForwardingTopology` we forward all messages from subscriptions to the input queues of the subscribers. At the same time, `AzureServiceBusSubscriptionCreator` uses a default `ForwardTo` that can be set up by users via `AzureServiceBusSubscriptionSettings`.

Questions:

1. ~~Should this only be set for Error and Audit queues?~~
1. ~~What will this API look like for customers (pseudo code)?~~
1. ~~Why would we have forwarding `ForwardTo` for subscriptions by default to error and audit queues?~~
1. We have `ForwardDeadLetteredMessagesTo` in place, should that be enough? Yes

@yvesgoeleven any thoughts?

Connect to #13

**Comment by yvesgoeleven** [comment]
indeed, we should get rid of this setting, and figure out an api that allows the user to set forwarding for audit & error queue only

**Comment by SeanFeldman** [comment]
I'd like this conversation to include @timbussmann 
At this point the discussion is solely about transport forwarding endpoint`s error and audit queues.

**Comment by timbussmann** [comment]
> and figure out an api that allows the user to set forwarding for audit & error queue only

why do you need to do this? We not just respect the values configured in the `EndpointConfiguration`? If the user want's to change the queue, why does it require a transport specific alternative?

**Comment by yvesgoeleven** [comment]
Looks like I misunderstood how audit queues were named by default, I though they were by endpoint, we can remove regular forwarding. ForwardDeadLetteredMessagesTo will do.

**Comment by SeanFeldman** [comment]
Decision is to remove `ForwardTo` for **all** entities.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/a08b423798736c8a58ef44d2e8a01d6d345421f7
