### ISSUE TITLE
Create backward compatibility tests (production tests repo)

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#120]
To ensure compatibility among different ASB transport versions, add tests to `ProductionTests` repo under `TransportCompatibilityTests` solution.

TODO:
- [x] Implement
- [x] Integrate with NSB.ASB build on TC

**Comment by SeanFeldman** [comment]
PR https://github.com/Particular/ProductionTests/pull/54

**Comment by danielmarbach** [comment]
Since the mentioned PR is merged, can we close this one or are there more outstanding issues? @melkio @SeanFeldman

**Comment by SeanFeldman** [comment]
I've updated the description with what's left to be done to reflect the progress better @danielmarbach

**Comment by SeanFeldman** [comment]
Implemented & [integrated](https://builds.particular.net/viewType.html?buildTypeId=NServiceBusAzure_NServiceBusAzureServiceBus_4RunTransportBackwardsCompatibilityT)
