### ISSUE TITLE
ConnectivityMode setting missing

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#130]
Looks like we accidentally removed support for the ConnectivityMode setting, need to add it back and ensure it works

**Comment by SeanFeldman** [comment]
`ConnectivityMode.Tcp` is set as the default for the transport v6 and below.
ASB default is `ConnectivityMode.AutoDetect`.

 @yvesgoeleven should we change the default to be `AutoDetect` to align with ASB?

**Comment by SeanFeldman** [comment]
Previously, `ConnectivityMode` was set in the [transport configuration](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/27036d13951fcb27773fd7f0a0588dffa03aa558/src/Transport/Config/AzureServiceBusTransportConfiguration.cs#L30).

I'm going with [transport definition (initialization)](ServiceBusEnvironment.SystemConnectivity.Mode =) to set the connectivity mode, unless there are objections.
