### ISSUE TITLE
Namespace registration API

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#135]
As of now, registration of namespaces is done in the following way:

```c#
var nsi1 = new NamespaceInfo("test", "conn");	
var nsi2 = new NamespaceInfo("Test", "conn");
```

which will result in `nsi1` and `ns2` to be treated as two different namespace information objects based on hashcode therefore not equal. 

```c#
nsi1.GetHashCode(); // 1120192152
nsi2.GetHashCode(); // 1120228920
```

By enforcing lower case we eliminate ambiguity and can prevent issues at the configuration time.

Two namespaces are equal if they have the same names (with case insensitive equality) and connectionstrings (with case insensitive equality on namespace name and shared access policy name)

Configuration API doesn't allow to register the same namespace twice

/cc @yvesgoeleven @melkio

Related issue: https://github.com/Particular/NServiceBus.AzureServiceBus/issues/93

**Comment by melkio** [comment]
Good point @SeanFeldman 

A quick question before updating code: what does equality mean for `NamespaceInfo`? Same `names` or same `names` and `connectionStrings`?
Because connection string is built around three parameters:

- namespace name
- shared access policy name
- shared access policy key

`namespace name` and `shared access policy name` are case insensitive, but `shared access policy key` is case sensitive.

Introducing `NamespaceInfo` equality, considering `name` and `connectionString` is a bit harder

**Comment by SeanFeldman** [comment]
I was focusing on the `name` only. Connection strings are usually copied as-is due to complexity. Names are typed, and that's where the chances are higher to make a mistake.

**Comment by melkio** [comment]
Ok. Another question:
What about adding two namespaces with different names and the same connection string?

**Comment by SeanFeldman** [comment]
This is a configuration API. If they register two namespace infos with different names, but same connection string, it could be intentional (one endpoint got deployed with a name `A`, another was deployed with a name `B`). Both look at the same namespace. A third endpoint needs to be able to talk to all three, `A`, `B`, and `C`. I'm talking hypothetically here though :)

**Comment by SeanFeldman** [comment]
@melkio @yvesgoeleven please update issue with the agreed on behavious as per discussion.

**Comment by yvesgoeleven** [comment]
we should check for duplicate connectionstrings, and not allow them. It would only result in multiple receivers on the same entities, simply a waste of connections
