### ISSUE TITLE
Using namespace name instead of connectionString and sanitization don't work well together

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#156]
To reproduce the issue with queue name and namespace name you need 2 endpoints, v6 and v7 (nsb.asb version).
When v6 is sending to v7, the "replyTo" on brokered message looks like "queue@connectionstring". It's getting replaces with "queue@default" when get to v7 endpoint and sanitized, which ends up "queuedefault".

**Comment by SeanFeldman** [comment]
Adding more info:

Have found this when working on Transport Compatibility tests (PR is [here](https://github.com/Particular/ProductionTests/tree/azure-service-bus)). Failing test is `It_is_possible_to_send_request_and_receive_replay(6, 7)` when v6 sends command to v6 and v6 replies back to v7.

When traced through what was happening (in general description), noticed the following

| **Call**  | **Queue value**  | **Note** |
|:-----------|:------------------------|-------------|
| ReceiveNotifier | source@connectionString | |
| BrokeredMessageToIncomingMessageConverte | source@connectionString | uses `ReplyTo` from BrokeredMessage |
| DefaultConnectionStringToNamespaceNameMapper | source@default | |
| Handler(message) | | context.Reply(replyMessage) is called here |
| Dispatcher | | replyMessage getting sent out |
| EndpointOrientedTopologySectionManager.DetermineSendDestination() | | **sourcedefault** is returned as a result on internal call to Sanitization strategy which removed the `@` sign |


Connects to #93

**Comment by melkio** [comment]
Closed by #159
