### ISSUE TITLE
Configure properly RequiresConnectionString property on transport definition

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#163]
AzureServiceBus transport supports multiple namespaces and has an extension method to configure them.
From a user perspective using `ConnectionString` method from `TransportExtensions<T>` to setup the first namespace and then using `NamespacePartitioning` to add the others is weird.

Configuring `RequiresConnectionString` to `false` will allow users to register namespaces with a single method

**Comment by SeanFeldman** [comment]
`RequiresConnectionString` is a core flag? If so, then yes. :+1:
