### ISSUE TITLE
Unexpected message retries and dead letters under load

### ISSUE THREAD

**Issue by RipalV** [Particular/NServiceBus.AzureServiceBus#167]
We are having issues in production, when under load NServiceBus seems to be retrying some of the messages and makes processing slower.
We are using NServiceBus 5.2.9 and NServiceBus.Azure.Transports.WindowsAzureServiceBus 6.3.2 and hosted as Azure WebApp.
AzureServiceBusQueueConfig has below configuration and using valid license.
BatchSize = 3 (As VM is not single core)
MaxDeliveryCount = 3
LockDuration = 180000 (3 Minutes - to avoid any possible timeouts under load)

TransportConfig has MaximumConcurrencyLevel set to 3 as suggested by below help page.
http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#scenarios-cpu-vs-io-bound-processing

To demonstrate the issue, I have controller as below which adds many messages to ServiceBus:
```
        [HttpGet, Route("Status/Test/{count:int?}/{seconds:int?}")]
        public IHttpActionResult Test(int count = 100, int seconds = 30)
        {
            var startTime = DateTime.UtcNow;
            var requestId = Guid.NewGuid();
            for (int i = 1; i <= count; i++)
            {
                this.bus.Send(new Test { RequestId = requestId, Number = i, SleepSeconds = seconds });
            }

            return Ok((DateTime.UtcNow - startTime).TotalMilliseconds);
        }

```
And simple handler as below:
```
    public class TestCommandHandler : IHandleMessages<Test>
    {
        public void Handle(Test message)
        {
            Thread.Sleep(TimeSpan.FromSeconds(message.SleepSeconds));
        }
    }

```
When 100 messages are sent and handler sleeps for 30 seconds. This shows as below result using single host:
- 158 messages in audit queue
- 6 messages in azure dead letter (Not the error queue)
- No messages in error queue
- 58 messages retried

1) Retry Issue:
Below are the start and end time for retried messages in audit queue.
From the First request:

>     NServiceBus.ProcessingStarted: 2016-03-31 13:29:03:612274 Z,
>     NServiceBus.ProcessingEnded: 2016-03-31 13:29:33:633903 Z,
> 

From the Second request:

>     NServiceBus.ProcessingStarted: 2016-03-31 13:27:32:530180 Z,
>     NServiceBus.ProcessingEnded: 2016-03-31 13:28:02:546633 Z,
> 

As you can see clearly, Start time of retry is after end time of first attempt, hence NServiceBus already knows that it has processed the message then it must not process it again.

2) Dead Letter Issue:
These messages in Dead Letter queue (ASB Dead letter queue, not the error queue) are also present in the audit queue.
Which suggest that these messages were processed successfully but still end up in dead letter with below error:

>     DeadLetterReason: MaxDeliveryCountExceeded,
>     DeadLetterErrorDescription: Message could not be consumed after 3 delivery attempts.

Issue could be reproduced from the code snippets above.

**Comment by RipalV** [comment]
I have also noticed and might help with your investigation that with `BatchSize = 3` and `MaximumConcurrencyLevel = 3` and single host processing messages, when 100 messages are sent to a queue, it has about 20 to 26 messages locked.
I was expecting to only see 3 messages locked (because BatchSize is set to 3) and I guess as a result it ends up acquiring lock longer then it needs to resulting in dead letter.

**Comment by SeanFeldman** [comment]
Hi @RipalV,
This sounds like a support case. Unfortunately I don't have your info to open a case for you. Could you please submit it at support@particular.net with mentioning of this GH issue? Thank you.

**Comment by yvesgoeleven** [comment]
Continued in support
