### ISSUE TITLE
Upgrading to NServiceBus V6 will change the default topology to EndpointOrientedTopology

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#178]
Today we experienced #177 and that seems "by design".

However, the decision was made to make the new EndpointOrientedTopology the default instead of the ForwardingTopology. This is probably due to better and improved routing mechanics but #177 was caused by this decision. I now made an explicit choice for ForwardingTopology and it works again as expected *AND* backwards compatible.

I vote to make the topology an explicit choice OR keep the old topology as default and write a WARN to the log that this topology is choosen for backward compatibility.

In this case my preference would be the explicit choice.

Not doing this is asking for support cases.

**Comment by SeanFeldman** [comment]
Assumptions made in this issue are incorrect due to the missing documentation.
Separate issue is raised [here](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/181) (#181 Reconsider Default Topology).
