### ISSUE TITLE
Topologies and Publishers API

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#179]
Connects to https://github.com/Particular/PlatformDevelopment/issues/718

#### Context

With version 7 of the ASB transport, there are 2 types of topology that _will_ be covered by [documentation](https://github.com/Particular/docs.particular.net/pull/1411) being currently worked on.
- `EndpointOrientedTopology`
- `ForwardingTopology`

Customers can introduce their own topologies by implementing an [`ITopology`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e130445020cd510b25dcad68a62184c5d95d24bc/src/Transport/Topology/ITopology.cs#L8) contract. 

`EndpointOrientedTopology` the topology ASB has had since day one. It was relying on the publishers information that was provided by the core, till core version 6. To accommodate the change in core v6 _and_ due to the fact that this topology will become obsoleted in favour of `ForwardingTopology` in unforeseeable time, Publishers API was introduced to help `EndpointOrientedTopology` implementation.

The issue that is surfacing right now it that Publishers API is coupled to the `EndpointOrientedTopology` and has **nothing** to do with the `ForwardingTopology` or any potentially new topology implemented by us or customers. Therefore, Publishers API should be scoped to the `EndpointOrientedTopology` internally, and not bleed out into the public topology contract [`ITopology`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e130445020cd510b25dcad68a62184c5d95d24bc/src/Transport/Topology/ITopology.cs#L21), as it does today.

#### Question

Should we refactor the code and ensure that Publishers API is not leaking out into `ITopology`?

I.e. Update configuration API [`.UseTopology<T>()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e130445020cd510b25dcad68a62184c5d95d24bc/src/Transport/Config/ExtensionMethods/AzureServiceBusTransportExtensions.cs#L12-L28) to return continuation that only allows Publishers API for a `T` that is `EndpointOrientedTopology`.

**Comment by SeanFeldman** [comment]
@ramonsmits @timbussmann - fyi

**Comment by SeanFeldman** [comment]
#182 is a working spike that solves this issue

**Comment by SeanFeldman** [comment]
Note: github had a glitch. I did NOT try to close the issue :blush:

**Comment by timbussmann** [comment]
> Should we refactor the code and ensure that Publishers API is not leaking out into ITopology?

:+1: 

> Customers can introduce their own topologies by implementing an ITopology contract.

how realistic is this, or why would someone provide it's own topology? That seems to be very hard to maintain across major versions as a user?

**Comment by SeanFeldman** [comment]
@timbussmann rare, but realistic. We do have customers that have done it.

**Comment by andreasohlund** [comment]
@bording remind me did we drop support for "custom" topologies from rabbit?

**Comment by timbussmann** [comment]
@SeanFeldman since you mentioned the topology concept did not exist previously, how did users implement their own topology and how will they be able to update it to v6?

**Comment by SeanFeldman** [comment]
@timbussmann ASB has always provided contract that could be implemented to replace the default ones.

**Comment by yvesgoeleven** [comment]
@timbussmann it's not unlikely, and the faster SB team iterates and adds new capabilities to the service the more you'll see it.

**Comment by bording** [comment]
> @bording remind me did we drop support for "custom" topologies from rabbit?

No, it's still there.

**Comment by SeanFeldman** [comment]
@melkio if you strongly oppose this change, lets get on a call.
I'd like to get the PR #182 going. It will unblock documentation work done in https://github.com/Particular/PlatformDevelopment/issues/718, including PR https://github.com/Particular/docs.particular.net/pull/1407 you're working on.

**Comment by melkio** [comment]
I don't oppose to this change. I agree with this implementation. I only think that we can do better at discovering publishers configuration needs if we introduce specific methods to select topology

**Comment by SeanFeldman** [comment]
Meged

**Comment by SeanFeldman** [comment]
PR #182 merged.
