### ISSUE TITLE
Remove unused CancellationTokeSource

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#183]
Raised in https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/73#issuecomment-209885748

Making sure that when stopping the endpoint no exception related to that is put into logs.

**Comment by SeanFeldman** [comment]
Looking at the code, I don't think we need to have the `CancellationTokenSource` for the `TopologyOperator` at all. ASB doesn't have a polling loop as ASQ does. When endpoint is shutting down, the order of calls would be:

`MessagePump.Stop()` ==> `TopologyOperator.Stop()` ==> all `IManageMessagingFactoryLifeCycle.CloseAll()` ==> all `IMessagingFactory.Close()`.

Because this is a chain of calls and no tight loop that needs to be broken, there's no need in `CanellationTokenSource` for `TopologyOperator`. The defined [`cancellationTokenSource`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/4e3e6b7b4256c1d0d6587a8c2002ad63f144a7c8/src/Transport/Topology/TopologyOperator.cs#L39) is in essence can be removed.

@yvesgoeleven thoughts?

**Comment by melkio** [comment]
The "real" chain is:

`MessagePump.Stop()` ==> `TopologyOperator.Stop()` ==> *all* `INotifyIncomingMessages.Stop()` ==> `IManageMessagingFactoryLifeCycle.CloseAll()` (it's a single instance) ==> `IMessagingFactory.CloseAsync()`

@SeanFeldman I confirm that this [cancellationTokenSource](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/4e3e6b7b4256c1d0d6587a8c2002ad63f144a7c8/src/Transport/Topology/TopologyOperator.cs#L39) is useless and we can remove it

**Comment by SeanFeldman** [comment]
@melkio I thought you've done this? I might be wrong :)

**Comment by SeanFeldman** [comment]
Looks like it's still [there](cancellationTokenSource).

**Comment by melkio** [comment]
@SeanFeldman: I removed it in my wrong PR about _background process to complete messages_

**Comment by SeanFeldman** [comment]
Want to re-submit it separately?

**Comment by melkio** [comment]
Done: https://github.com/Particular/NServiceBus.AzureServiceBus/pull/238
