### ISSUE TITLE
Missing: DiscriminatorBasedIndividualization SetDiscriminatorGenerator

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#188]
The DiscriminatorBasedIndividualization (to be used for backward compat as our old discriminator logic differs slightly from the new one in the core), misses config option to set the value for discriminatorGenerator

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/3e04860ec7afd5486e6b88eca41a578d87444295
