### ISSUE TITLE
ASB transport sets transaction settings that are no longer honored by the core

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.AzureServiceBus#192]
Currently the ASB transport sets two settings related to transactions:

- `Transactions.DoNotWrapHandlersExecutionInATransactionScope`
- `Transactions.SuppressDistributedTransactions`

These settings are leftovers from NServiceBus 5 and setting them has no effect on NServiceBus 6.

The desired solution is to detect if a transaction scope will be used and throw an exception at transport configuration time to prevent endpoint startup. Transaction scopes can be created in the following situations:

- User requests the `TransportTransactionMode.TransactionScope`
- User requests handlers to be wrapped in a transaction scope by calling `endpointConfiguration.UnitOfWork().WrapHandlersInATransactionScope`

**Comment by SeanFeldman** [comment]
@MarcinHoppe are there replacements for these settings that the transport should set or everything is done now via `TransportInfrastructure.TransactionMode` ?
Those were indeed based on the old (core v5) settings.

**Comment by MarcinHoppe** [comment]
@SeanFeldman I think the best we can is to detect a transaction scope and throw. I discussed this a while back with @yvesgoeleven.

**Comment by SeanFeldman** [comment]
@yvesgoeleven @MarcinHoppe If you could update the issue with the discussion summary, would be great. Thanks.

**Comment by MarcinHoppe** [comment]
@SeanFeldman Updated issue description. :point_up:

**Comment by yvesgoeleven** [comment]
I've tested the scenario where User requests the TransportTransactionMode.TransactionScope. This has been covered by the core and throws an InvalidOperationException with text Azure Service Bus transport doesn't support the required transaction mode TransactionScope.

**Comment by MarcinHoppe** [comment]
@yvesgoeleven So we should be good removing these two settings. Want me to create a PR?

**Comment by yvesgoeleven** [comment]
@MarcinHoppe already created

**Comment by yvesgoeleven** [comment]
I'm also testing the UnitOfWork().WrapHandlersInATransactionScope() scenario, that seems to work fine (besides a crappy key not found exception that I'll report to the core)

**Comment by yvesgoeleven** [comment]
here is the associated PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/266
