### ISSUE TITLE
Rename UseNamespaceNamesInsteadOfConnectionStrings

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#196]
Something is off with the naming of this setting, the default seems to perform the mapping, calling this will pass the connectionstrings through as it is, which seems to be the opposite of the configuration setting name

**Comment by melkio** [comment]
@yvesgoeleven it's not right, the config API `UseNamespaceNamesInsteadOfConnectionStrings` enable the right behavior.

`DefaultBatchedOperationsToBrokeredMessagesConverter` uses an instance of `ICanMapNamespaceNameToConnectionString` when needs to convert an `outgoing message` to a `brokered message`.
The default behavior is `DefaultNamespaceNameToConnectionStringMapper` implementation for backward compatibility: if the `ReplyTo` header contains `namespace name`, this value is converted back to `connection string`.
When `UseNamespaceNamesInsteadOfConnectionStrings` is switched on, a different implementation of `ICanMapNamespaceNameToConnectionString` is provided: `PassThroughNamespaceNameToConnectionStringMapper`. This component does nothing against `RepyTo` header.

On the opposite side, `DefaultBrokeredMessagesToIncomingMessagesConverter` converts `connection string` to `namespace name` for each incoming message.

@Particular/azure-service-bus-maintainers: I think we can close this issue

**Comment by yvesgoeleven** [comment]
@melkio is our default behavior to send connection strings or namespace names?

**Comment by melkio** [comment]
default behaviour is to send connection strings for backward compatibility

**Comment by yvesgoeleven** [comment]
oh ok, is this the same in ASQ? @Scooletz ?

**Comment by Scooletz** [comment]
Yes, that's the same for ASQ: http://docs.particular.net/nservicebus/azure-storage-queues/configuration#connection-strings-securing-connection-strings
Should we provide an upgrade guide for this scenario?

**Comment by yvesgoeleven** [comment]
Ok, then we can close this issue, the name is correct

@Scooletz I don't think it needs to be part of the upgrade guide. This will probably be something you implement after a migration. We have an article for ASB in the pipe as well that describes how to keep connection strings safe.
