### ISSUE TITLE
RequiresDuplicateDetection can lead to a message loss in v7

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#201]
ASB transport allows [native duplicates detection](http://docs.particular.net/nservicebus/azure-service-bus/configuration/configuration#controlling-entities-queues). By default it's set to false, but can be enabled. 

SLR is implemented by taking a message failing FLR and, creating a new, deferred one, and dispatching it to the endpoint itself. The deferred message will be dispatched to the same queue with the [same message ID](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/576fc84ca3883a9d8231f15b5bea61ce7e316011/src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs#L33) that was used for the originally failing FLR message. 

When `RequiresDuplicateDetection` on ASB queue is enabled, that will trigger de-duplication and SLRed message will be considered as a duplicate message, causing its removal (message loss).

**TODO**

Confirm this behaviour with 
 - [x] Core doesn't require transport message ID to match the NSB (header) message ID*
 - [x] ASB v7
 - ~~ASB v6~~ separate issue #242

In case this is confirmed, potential solutions are:

1. **[Required solution]** Do not re-use NSB message ID for transport message ID. Always use a random unique value. 
 - Cons: ???
 - Pros: consistent for all messages
1. ~~**[Agreed solution]**~~ Detect SLR retries from NSB core [header "NServiceBus.Retries"](https://github.com/Particular/NServiceBus/blob/68f6d76bfaeb218525c2878e751bbd149b2b0b6f/src/NServiceBus.Core/Headers.cs#L96-L96) and if found, replace transport message ID with a random unique value. 
 - Cons: hacky, we need to inspect core header, which could change
 - Pros: unique to each message dispatched
1. Inspect and store information about queue setting for `RequiresDuplicateDetection`. When dispatching a message, check if dedup was enabled. If dedup is enabled, do not re-use NSB message ID, but assign a random unique value.
 - Cons: queue setting is read once, but could be updated and endpoint would run with stale info
 - Pros: ???

\* transport message ID is solely used when no `NServiceBus.MessageId` header is found on an incoming message from a native sender

**Update**:
There are 2 scenarios when a message can be lost because of the `RequiresDuplicateDetection` enabled:

1. Enabled SLR (transport message Id is re-used by utilizing `NServiceBus.MessageId` header value)
1. FLR with SC (SC will re-send message with the same Id)

For v7 solution is not to re-use `NServiceBus.MessageId` for the transport message Id.
For v6, a [separate issue](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/242) created.

**Comment by SeanFeldman** [comment]
I'll be going through the TODO section to confirm behaviour for ASB v6/7

@Particular/azure-service-bus-maintainers FYI

@andreasohlund could you please confirm that "Core doesn't require transport message ID to match the NSB (header) message ID"?

**Comment by andreasohlund** [comment]
Confirmed, native message id is only used when there is no "NServiceBus.MessageId" header present. And that only happens when the message is coming from a native sender

**Comment by SeanFeldman** [comment]
Confirmed message loss in v7 (message never gets into error queue, but is removed from the source queue).

**Comment by yvesgoeleven** [comment]
Can the transport somehow detect SLR retry to change the id?

**Comment by andreasohlund** [comment]
Yea we talked about that, you can look at the `NServiceBus.Retries` header

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers what do we do about v6 (current version)? /cc @andreasohlund

**Comment by SeanFeldman** [comment]
Was investigating this a little more and have bad news: this is also going to happen with FLR only and SC retrying messages. Except that with FLR only we don't have a header to detect (`NServiceBus.Retries` is not there)...

At this point I'm gravitating towards first option, do not re-use NSB message ID for transport message ID.

@Particular/azure-service-bus-maintainers @andreasohlund thoughts?

**Comment by andreasohlund** [comment]
>do not re-use NSB message ID for transport message ID.

That's what we want to do for the sqltransport as well (for other reasons).

**Comment by yvesgoeleven** [comment]
@SeanFeldman How can this happen on FLR? FLR is implemented using the native retry mechanism in ASB, any outbound message will get a new id, so I don't see how it can happen. And for SC it's unlikely to happen as well, duplicate detection is limited in time, so a user has to be pretty fast in order to trigger it

**Comment by SeanFeldman** [comment]
@yvesgoeleven this is how. Scenario: SLR disabled and SP is used to monitor failed messages.

* Set `DuplicateDetectionHistoryTimeWindow` for a couple of days (up to 7), or enough time for ops to notice failures.
* Message failing all FLR attempts will be moved to the error queue.
* SC will pick it up.
* Ops can resubmit failed messages.
* Messages will be de-duped on the identical message ID and will never be received.

We're exposing running of `DuplicateDetectionHistoryTimeWindow`, so no need to be fast 😃.

**Comment by SeanFeldman** [comment]
Now that we know there are two scenario for `RequiresDuplicateDetection` to lose messages
1. SLR enabled
2. FLR + SC combo

I'm wondering if option #1 would be preferable over option #2? Endpoints can't know if SC is used or not, therefore making it risky. 

On the other hand, we've not heard anything from the customers. Either because they don't use SC or they've not noticed this so far. Personally, I find native de-dup somewhat problematic, but we can't disable it. So what it's going to be folks?

**Comment by yvesgoeleven** [comment]
Would there be a risk to always use a new id for the brokeredmessage's messageid and never use the one from core?

**Comment by SeanFeldman** [comment]
I've [raised this ](https://particularsoftware.slack.com/archives/guild-transport/p1464640932000031)with all the transports. Collectively we should come to a conclusion.

**Comment by SeanFeldman** [comment]
Apperently SQL Server does exactly the same as proposed in option #1, [assigning a random unique value to the transport Id](https://github.com/Particular/NServiceBus.SqlServer/blob/dc21d09a0c801b19ec6f34f15b4de0ae6c3e41dc/src/NServiceBus.SqlServer/Queuing/MessageRow.cs#L29). I vote we should go with this for ASB as well.

**Comment by SimonCropp** [comment]
@andreasohlund so since this is message loss doesnt it qualify as a "must fix and backport"? admittedly it might be unlikely to happen but that just means we dont need to prioritize the fix. but is should still trump all new work?

**Comment by andreasohlund** [comment]
Message loss should be fixed yes, but can we backport a fix that isn't going to cause backwards compatibility issues?

**Comment by SeanFeldman** [comment]
@andreasohlund I cannot answer that question w/o a proper discussion. 
First, I'd need to understand what and where (outside of the transport itself) is relying on the transport message ID internally or externally (platform tools or customer code).

**Comment by SeanFeldman** [comment]
Update, v6 related conversation is moved into a separate issue: https://github.com/Particular/NServiceBus.AzureServiceBus/issues/242 .
This issue should focus on v7.

**Comment by SeanFeldman** [comment]
Fixed in https://github.com/Particular/NServiceBus.AzureServiceBus/commit/b3c2be75ca7b6ea70e64e834c9e4d8b7b0166961
