### ISSUE TITLE
Debugging Publish Message that does not get published nor audited

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.AzureServiceBus#202]
Have had two instances where some topics stopped working the past week, that is when Publishing Events the events did not get published to the subscribers, nor did they appear in the Audit queue. 

The solution was in both cases to delete related topics, which got recreated and things started to work as expected again. 

Feels like the issue can be with MS ASB or somewhere in between, the question is how one can debug this further down to see where the process stops, any verbose flag one can turn on in NSB.Azure? (there where no errors from NSB, and the topics in question where empty.)

**Comment by SeanFeldman** [comment]
@danielHalan you can configure NSB logging to DEBUG level. If NSB.Azure would encounter errors with the underlying ASB, it would log those. 
Are there any forwarding rules? Did you try to setup a catch-all subscription? Are there any topic settings that are turned on manually? Thanks.

**Comment by SeanFeldman** [comment]
Closing this. Reopen if needed.

**Comment by danielHalan** [comment]
Hi Sean, yes this can be closed for now, this has not re-occurred since, we've added more logs on all levels to see where it would disappear when (if) it would happen again.

NSB logging was set to DEBUG bug but no logs out of the ordinary was found. No manual topic settings. no special forwarding rules/catch-all except the standard Audit and Error queus

**Comment by danielHalan** [comment]
Hi again, 

This issue has been re-occurring from time to time since last post. Lastly was today. 
That is, that the Endpoint stop publishing events to other endpoints, which only is solved by manually shutting down and restarting the Endpoint Service.
The typical scenario is if a command takes longer then usual to complete, have noticed one time that NSB-endpoint would "restart" itself without giving any good error messages before, but that is not usually the case. (also after the self-restart the issue still persists)

Today this happens again after a long running command, but the command was successfully processed by a saga (no timeouts / restarts etc), but a different error occurred, indicating a to large message to process. (which I can't find, i.e. cant see any message in logs that would exceed message size). Except this fatal error all commands seems to be processed correctly. See full Exception bellow.

``
2017/12/14 02:43:08.694 Fatal A fatal exception occured while trying to send a message, the exception was The message with id 6d5d8074-79d3-4445-a255-a849002c2975 is larger that the maximum message size allowed by Azure ServiceBus, consider using the databus instead NServiceBus.Azure.Transports.WindowsAzureServiceBus.MessageTooLargeException: The message with id 6d5d8074-79d3-4445-a255-a849002c2975 is larger that the maximum message size allowed by Azure ServiceBus, consider using the databus instead
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.BrokeredMessageConverter.GuardMessageSize(BrokeredMessage brokeredMessage) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Utils\BrokeredMessageConverter.cs:line 95
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.BrokeredMessageConverter.ToBrokeredMessage(TransportMessage message, SendOptions options, SettingsHolder settings, Boolean expectDelay, Configure config) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Utils\BrokeredMessageConverter.cs:line 88
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.SendInternal(TransportMessage message, ISendBrokeredMessages sender, SendOptions options, Boolean expectDelay) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 53
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusSender.<>c__DisplayClass6_0.<SendInternal>b__0() in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\AzureServiceBusSender.cs:line 45
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.SendResourceManager.Commit(Enlistment enlistment) in C:\BuildAgent\work\2f57832e2eee436e\src\Transport\Sending\SendResourceManager.cs:line 25
``

**Comment by SeanFeldman** [comment]
> indicating a to large message to process. 

@danielHalan the exception you have provided is thrown for a message that is about to be sent, not a message that is received and processed. 
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/4b72ec2d42aa1fe4baf200893a5b14f47ba7f100/src/Transport/Utils/BrokeredMessageConverter.cs#L91

Sending endpoint verifies message is not exceeded the maximum allowed size before dispatching. You'll have to look at what has triggered this operation and why a message to be sent could exceed maximum message size. Unfortunately, from the log snippet provided it is not possible to determine where this has happened or what handler was executing handling what message. Is that something you could find out and share?

To help you with that, you can use the message ID that is copied from NServiceBus message ID
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/4b72ec2d42aa1fe4baf200893a5b14f47ba7f100/src/Transport/Utils/BrokeredMessageConverter.cs#L107
