### ISSUE TITLE
Follow standard component naming

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#204]
As described [here](https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/component-naming.md).

1. Namespaces need to be re-adjusted (ASB v7?)
1. The new nuget name would be `NServiceBus.Transport.AzureServiceBus` (ASB v7)

**Comment by SeanFeldman** [comment]
@andreasohlund should this be part of v6 (core) release or later?

**Comment by andreasohlund** [comment]
Renaming namespaces , yes if the effort is reasonable. Renaming nugets: no

**Comment by SeanFeldman** [comment]
Ok, perhaps splitting this into two will help. 1) namespaces for ASB v7 (core v6) and 2) package name change for ASB v8.

**Comment by yvesgoeleven** [comment]
replaced by https://github.com/Particular/NServiceBus.AzureServiceBus/issues/263 & https://github.com/Particular/NServiceBus.AzureServiceBus/issues/264
