### ISSUE TITLE
Addressing logic bugs

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#209]
While writing the doco, I noticed there are a few things off in the addressing logic.

Validation is called after sanitization (it should also be called before to prevent sanitization)
Composition is not integrated in the entity addressing
Individualization is not integrated in the core seam (BindToLocalEndpoint)

**Comment by SeanFeldman** [comment]
fixed in https://github.com/Particular/NServiceBus.AzureServiceBus/commit/5140f1add6d00dd069b7a0df29d0020b90dfc109
