### ISSUE TITLE
Implement Batch Completion

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#212]
Looks like Autocomplete doesn't guarantee completion until the next receive operation, we should implement batch completion ourselves. Reverted the code to individual completion for now

**Comment by SeanFeldman** [comment]
When `AutoComplete` is turned on, the completion is offloaded on a separate async thread, so that parallel OnMessage API callbacks will handle messages much faster because time it takes is only {the processing time}.
With AutoComplete, there's no guarantee that completion is successful, until the next callback is invoked. If next callback is not invoked, completion won't take place.

**Comment by melkio** [comment]
> With AutoComplete, there's no guarantee that completion is successful, until the next callback is invoked. 

I'm not sure this is true: I went through the ASB SDK source code and I think it's not about "waiting for next callback" but about "timing"
Into ASB SDK there is a component (`MessageReceivePump`) that adds `message's lockId` to an internal list and tries to "complete" received messages on different threads, running completion in parallel. 
If the endpoint shutdown before all stored `message's lockId` has been addressed, there is no way to complete remaining messages anymore.

**Comment by SeanFeldman** [comment]
@melkio is completion based on the separate thread based on a time or some other trigger?

**Comment by melkio** [comment]
@SeanFeldman what I understood is that `MessageReceivePump` uses an approach similar to `TPL Data Flow`: it creates a sort of async pipeline. Each received message goes through this pipeline. 
One step of this pipeline is to collect messages to complete. After a well defined parameter (`completionBufferWaitTime`) messages will be completed

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/60507f7dd13e4a1a2800baeeed84c63c410b3858
