### ISSUE TITLE
ServiceControl breaks when multi namespace or secure connection string are enabled

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.AzureServiceBus#217]
@Particular/azure-service-bus-maintainers 

I have noticed that there are 2 new features (multi namespace and secure connection string) that are scheduled to be released in the next major release.

Looking at the current doco written for these new features, I can't see how these features are going to work with ServiceControl.
According to the multi namespace feature, it needs to be enabled in all endpoints for it to work, but since ServiceControl is using v6.4.0 and there are no intentions to update it, it is not possible to enable this feature. The only way I see this working is by installing multiple instances of ServiceControl, one per namespace, I am not sure what the implications of this are regarding licensing ?
The other feature is the secure connection string, once again ServiceControl is using v6.4.0 and there are no intentions to update it, so it won't understand the new mappings.

----

 **Updates**

1. Multiple namespaces are not new to ASB. What we don't know is who and how uses it with SC (and if they do at all). That's possibly a question beyound this issue/repo.
1. Secure connection strings feature is not breaking relationship with SC more than it is in the current version of the transport.

**Comment by SeanFeldman** [comment]
Have a few questions

1. Multiple namespaces were already an option in ASB v6. Do we know how customer have used it with SC (and if they used SC at all)?
1. Secure connection strings - would that matter if we operate in a mode of "SC instance per namespace" and SC is configured with the connection string (SC on ASB v6)?

@Particular/azure-service-bus-maintainers should we discuss this and see if there's any action items?

**Comment by melkio** [comment]
If I understood well, the only way to use SC in a multiple namespaces scenario is to have a different SC instance for each namespace. In this way SC is be able to send back messages to originator. Nothing else. I can't figure out other ways to use SC in multiple namespaces scenarios.
@yvesgoeleven said (on slack):
> it's not a new problem
customers already have multiple SC instances running, one for each namespace

SC, from transport perspective, is simply another endpoint that relys on ASB v6. To enable "secure connection string" all endpoints have to be v7 (or more). If customers are using SC, they can't enable that feature, but they can upgrade all the other endpoints to ASB v7.

**Comment by SeanFeldman** [comment]
> If customers are using SC, they can't enable that feature, but they can
upgrade all the other endpoints to ASB v7.

Can't or should not?

**Comment by SeanFeldman** [comment]
>If customers are using SC, they can't enable that feature, but they can upgrade all the other endpoints to ASB v7.

Can't or should not?

**Comment by melkio** [comment]
No, wait. I wrote a wrong thing.
Securing connection string feature acts on `ReplyTo` header value only. Since SC uses `FailedQ` to know where to send messages back, enabling `UseNamespaceNameInsteadOfConnectionString` shouldn't affect SC.

**Comment by SeanFeldman** [comment]
Thank you @melkio.

I'll try to sum up what we've got so far:

1. Multiple namespaces are not new to ASB. What we don't know is who and how uses it with SC (and if they do at all). That's possibly a question beyound this issue/repo.
1. Secure connection strings feature is not breaking relationship with SC than it is in the current version of the transport.

@johnsimons @Particular/azure-service-bus-maintainers thoughts?

**Comment by johnsimons** [comment]
So to support multiple namespace deployments, SC needs to be multiple times, once per instance, @willie-levy how does this affect licensing ?

Regarding secureconnections, because the connection is not secured in the FailedQ header, SC should be able to do retries on those messages, I guess the next step is to test it ?

**Comment by SeanFeldman** [comment]
@johnsimons tiny adjustment - `FailedQ` doesn't contain any connection string information. Only queue name. Therefore you're correct, it will not have any impact.

**Comment by melkio** [comment]
since `FailedQ` doesn't contain any connection string information, SC doesn't support multiple namespaces scenario

**Comment by SeanFeldman** [comment]
Closing this issue. Reopen if needed.
