### ISSUE TITLE
Namespace naming Vs Multiple Namespaces

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#229]
'Multi namespace' is used for 2 scenario's

* Targetted sending (from an endpoint in a namespace to one in another)
* partitioning (2 endpoints communicating over a set of namespaces)

Combining namespace naming with the multi namespace seems to lead to a few issues in this context:
* endpoints in different namespaces cannot talk to each other anymore because the namespace name 'default' (coming from the connectionstring extension method) has a different mapping for both.
* namespaces registered are considered for partitioning only, so direct sending from an endpoint in namespace1 to an endpoint in namespace2 is no longer possible.

Changes required (still under analysis by @yvesgoeleven):

**Connectionstring to addnamespace mapping:**

- [x] default namespace name should be settable.
- [x] connectionstring should not be required so the addnamespace api can be used for all config.

**AddNamespace API:**

- [x] some kind of usage indicator should be introduced to indicate whether a registered namespaces is for targetted sending only, or can be used in the implicit model (with or without @destination in the address) for send or receive.

**Dispatcher changes (probably in impl of ITopologySectionManager):**

- *Option 1*: When a targetted send (or publish) is requested, it should bypass the partitioning logic so that the message is sent to the targetted namespace.
- *Option 2*:  Change the PartitioningIntent to include info about the targetted namespace, so that partitioning logic can use it in it's logic (to choose it in our impl's, but user could than decide for custom strategies).

**Partitioning Strategy Changes:**

- [x] The validation logic of partitioning strategies should be changed to take into account / ignore namespaces registered for targetted sending.

---
Original issue by @SeanFeldman 

Going through [configuration API for secured connection strings](http://docs.particular.net/nservicebus/azure-service-bus/securing-connection-strings), as a reader I could not find any information how 

`.ConnectionString("...");` from the [transport getting started doco](http://docs.particular.net/nservicebus/azure-service-bus/#setting-the-connection-string) relates to 

```c#
var namespacePartitioning = transport.NamespacePartitioning();
namespacePartitioning.UseStrategy<SingleNamespacePartitioning>();
namespacePartitioning.AddNamespace("namespaceName", "connString");
```

Questions I had:

1. What's the relationship between `.ConnectionString();` and `.AddNamespace()`? If `.AddNamespace()` is used, do I still need to provide `.ConnectionString();`? If `default` namespace derived from a single registered namespace with a name?
1. Should documentation first explain `.ConnectionString();` and that it's mapped automatically to the `default` name, and then describe `.AddNamespace()`?

/cc @melkio

**Comment by melkio** [comment]
This issue is labeled as "Discussion", I share my thoughts here . Let me know if I have to move them to another place.

I'm thinking about config API. Transport sets `RequiresConnectionString` to `true`. This is the first issue because users have to provide connection string through `ConnectionString` extension method.
From a user point of view it's weird to setup a namespace using `ConnectionString` and the others namespaces through `AddNamespace` API if they want to enable multiple namespaces support.

Transport could provide an overload to `AddNamespace` configuration API without first parameter (namespace name) to simplify configuration, and then we could change `UseNamespaceNameInsteadOfConnectionString` expliciting the "default" namespace name through a lambda for instance, as I suggested for ASQ.

@Particular/azure-service-bus-maintainers thoughts?

**Comment by SeanFeldman** [comment]
I might be off, but this is solutioning. On the call we agreed to come with all the scenarios and outline those first.

**Comment by yvesgoeleven** [comment]
There are more issues with the current configuration API

- Sending to targetted namespace (outside the regular communication) is no longer possible

**Comment by yvesgoeleven** [comment]
Will include https://github.com/Particular/NServiceBus.AzureServiceBus/issues/163 in this effort as it is related

**Comment by yvesgoeleven** [comment]
Docs PR https://github.com/Particular/docs.particular.net/pull/1640
