### ISSUE TITLE
Handler goes into non-processing state after errors, outputting various timeout warnings

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.AzureServiceBus#246]
Hi, 

Have an situation where after 2-3 messages that throws exception, the Handler stops processing messages, and produces timeout warnings. If Restarted, same occurrence happens again, 2-3 messages gets processed (resulting in exception) and back to timeout.

What is different with this Handler is has custom exception handling added (to throw an inner exception + more logging)

``      
b.Pipeline.Register<DbExceptionFilteringRegistration>();
``      
which has following in its constructor, 
``      
InsertBefore(WellKnownStep.InvokeHandlers);
``      

The repeating timeout messages are as following,

from time to time, 
```     
Warn TimeoutException occured when sending to queue Particular.ServiceControl System.TimeoutException: The request operation did not complete within the allotted timeout of 00:01:10. The time allotted to this operation may have been a portion of a longer timeout. TrackingId:8003da80-b081-4b6c-80b5-115d656e4bb7, Timestamp:6/6/2016 6:55:31 AM
```    

```    
Warn Transient Messaging exception occured on subscription xxxx.yyyyy Microsoft.ServiceBus.Messaging.MessagingCommunicationException: Error during communication with Service Bus. Check the connection information, then retry. ---> System.ServiceModel.CommunicationObjectFaultedException: Internal Server Error: The server did not provide a meaningful reply; this might be caused by a premature session shutdown. TrackingId:dc4294fb-fae5-4f7e-b890-912951547007, Timestamp:6/6/2016 7:01:34 AM
```    

and continuously,
```     
Warn Brokered message lock expired, this could be due to multiple reasons. One of the most common is a mismatch between the lock duration, batch size and processing speed of your handlers. This condition can also happen when there is clock skew between the client and the azure servicebus service.
```

**Comment by yvesgoeleven** [comment]
@danielHalan the first 2 exceptions are SB server side problems, it seems to be not responding, 

the third one implies that processing is slower than message intake. Is that DbExceptionFilteringRegistration very IO heavy perhaps and blocking processing?

**Comment by yvesgoeleven** [comment]
@danielHalan where are you hosted? I'm getting other similar reports from people in asia.

ps: if the endpoint appears to stop processing when to many critical errors occur (when ASB is down), you may want to change our critical error behavior as described here. http://docs.particular.net/nservicebus/hosting/cloud-services-host/critical

**Comment by danielHalan** [comment]
Actually its very light, just checks for inner exception of specific type, and if found throws that one.

The ASB and Workers are located in West EU, have other NSB going against same ASB without any issues on same VM. 

Just noted also that this NSB Endpoint is consuming all available memory 5.2GB (so memory is 99% used), while other enpoints are at 68MB.

**Comment by yvesgoeleven** [comment]
@danielHalan that's not good. Any chance you can share this endpoint with us and maybe a memory dump of that process so we can have a look what is wrong and where it's leaking?

**Comment by SeanFeldman** [comment]
@danielmarbach did you submit a support ticket? Anything new you have found? Should we investigate?

**Comment by danielHalan** [comment]
Hi, suspected it to be in regard with messages as this endpoint works in a QA environment (and no code changes since it stopped working) and after clearing topics (there was quite some messages stuck) its back to normal.. will open support@ ticket with compiled logs / endp

**Comment by SeanFeldman** [comment]
@danielHalan have you had this issue since again?

**Comment by SeanFeldman** [comment]
@danielHalan I'm going to close this one. In case this issue arises again, please re-open.
