### ISSUE TITLE
Get rid of TransactionScopes

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#25]
Transactionscopes are giving us all kinds of fits, lets replace them with

- Allow transport to disable all scopes (requires core changes in v6)
- receive transactions through queue peek lock
- send delay through local outbox
- send transactions by means of origin queue if available

**Comment by abombss** [comment]
+1, I do have problem with Outbox and competing consumers. Outbox needs to ensure their is extensibility for some type of shared storage like Redis Cache or something so competing consumers can work when the message lock is lost or the message is abandoned.

**Comment by yvesgoeleven** [comment]
It is extensible, but redis gives us no persistence guarantees, so I don't see how that can help?

**Comment by yvesgoeleven** [comment]
We're no longer using TX scopes in core v6.
