### ISSUE TITLE
Is ThrowOnFailingSanitization a sanitization strategy?

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#254]
`ThrowOnFailingSanitization` doesn't seem a sanitization strategy.
It doesn't do anything except throwing if validation fails.

Isn't it better to create a `ThrowOnFailingValidation` validation strategy with the same beahvior?

**Comment by SeanFeldman** [comment]
If we follow the idea that `IValidationStrategy` is to validate and `ISanitizeStrategy` to sanitize, I'd say validation should solely return validation result and it's sanitization responsibility to decide what to do with the validation result. If sanitisation strategy decided that it will ignore the validation result and throw, then that's what it does.

Perhaps the name is misleading, and should be `ThrowOnFailedValidationSanitization`?

**Comment by yvesgoeleven** [comment]
Part of https://github.com/Particular/NServiceBus.AzureServiceBus/pull/265
