### ISSUE TITLE
Adjust namespaces

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#263]
As described [here](https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/component-naming.md) namespaces need to be re-adjusted 

Part of #204

**Comment by SeanFeldman** [comment]
Let's keep this on hold until significant code changes are done. Will
minimize number of conflicts.

**Comment by SeanFeldman** [comment]
fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/635c27c2c3f369ed083fab6feb601b3ae9292f86
