### ISSUE TITLE
New nuget package name

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#264]
As described [here](https://github.com/Particular/PlatformDevelopment/blob/master/designprinciples/nservicebus/component-naming.md) the new nuget name would be `NServiceBus.Transport.AzureServiceBus` (ASB v7)

Part of #204

**Comment by danielmarbach** [comment]
There is no benefit for our customers if we change the name of the package just for internal aligning purposes. It might be beneficial for .NET Core support with the revised SDK that we create a new version 1.0 of the transport and then we can align the name. Closing this
