### ISSUE TITLE
Review Internal vs Public for reuse

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#272]
Review Internal vs Public API for reuse

**Comment by yvesgoeleven** [comment]
https://github.com/Particular/NServiceBus.AzureServiceBus/pull/388

**Comment by SeanFeldman** [comment]
closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/739be8c8946276fcaf8e9ad60ddea22763b8f88a
