### ISSUE TITLE
Implement recoverability seem

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#277]
A new part of the transport seem will be introcuded, which allows native recoverability features (FLR counter)

Instead of core deciding when the error behavior should kick in, this task is delegated to the transport But the core still decides how it's done (send to errorQ, SLR logic etc...).

In order to get this behavior  an OnError callback will be introduced that transport needs to invoke when the maximum retry count has been exceeded, and this callback will return a result that indicates whether core handled the message (by sending to errorQ or SLR)

The behavior needs to be implemented differently depending on transaction mode though:

When transaction mode < AtomicSendWithReceive

onError needs to be invoked after an execution occurs in the pipeline, https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Receiving/MessageReceiverNotifier.cs#L199, passing in the exception info

* When core says that the exception is handled, the messages should be completed
* When core says the exception is not handled, the message should be abandoned

When transaction mode = AtomicSendWithReceive then 'Completing after an exception' (bullet 1 above) could lead to pending send operations being triggered which should not be triggered (because the message has been sent to error queue or SLR), so in this case

* Should NOT invoke on error callback after processing the pipeline
* instead always Abandon the message and put exception information in message header (truncate if needed) using Abandon overload (add overload to the adapter)
* on next receive, check the retryAttempts and invoke on error instead of invoking the pipeline https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Receiving/MessageReceiverNotifier.cs#L182 passing in the necessary exception information

**Comment by SeanFeldman** [comment]
@melkio could you please update the issue with the details from the sync with the TF? Thank you.

**Comment by melkio** [comment]
> In order to get this behavior an OnError callback will be introduced that transport needs to invoke when the maximum retry count has been exceeded, and this callback will return a result that indicates whether core handled the message (by sending to errorQ or SLR)

It's not right. Transport has to invoke _OnError_ callback each time a message fails. Core handles the retry count exceeded scenario.

_OnError_ callback output could be:

- `Handled`: transport has to acknowledge the message
- `RetryRequired`: transport has to abandon the message and retry later

/ @tmasternak @danielmarbach

**Comment by yvesgoeleven** [comment]
@melkio core handlers the retry count exceeded scenario: but we do have control on the number used (last parameter on ErrorContext), that's what we need

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/1a6070e83b894090508d2178324c3af9d71ae101
