### ISSUE TITLE
Can't set custom implementation of IConvertBrokeredMessagesToIncomingMessages and IConvertOutgoingMessagesToBrokeredMessages

### ISSUE THREAD

**Issue by melkio** [Particular/NServiceBus.AzureServiceBus#278]
It's not possible to provide a custom implementation of `IConvertBrokeredMessagesToIncomingMessages` or `IConvertOutgoingMessagesToBrokeredMessages` through configuration API.

Topologies register default implementations directly into the container.

**Comment by SeanFeldman** [comment]
For the future, would be nice to set some context in addition to the subject. As a reviewer, I saw a solution to a problem, but wasn't sure what the problem was or what triggered it. :smiley:

**Comment by melkio** [comment]
@SeanFeldman description updated.
This issue belong to the same "category" of the other issues we discovered writing the doco: transport doesn't provide some "extensibility points" to configure custom components or it doesn't configure properly provided custom components implementations.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/3d42faf51ff63253e6636f6455cc6236b6c6adb9
