### ISSUE TITLE
Document entity name length limitations and how to change the validation rules

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#28]
## Who's affected

- Any users that have topic & queue names longer than 260 characters and trying to use `Messaging` Service Bus namespace

## Symptoms

Endpoint is working locally, but is failing in Azure because Queue name is too long.

## Workaround

Use namespace of type `Notification Hub` or `Mixed`.

## Analysis

Azure ServiceBus has 3 types of namespaces: `Notification Hub`, `Messaging`, and `Mixed`.
For ~~`Notification Hub` and~~ `Mixed` Queues and Topics name length can be up to [290 max length](https://msdn.microsoft.com/en-us/library/hh322663.aspx). For `Messaging` ~~and _~~`Notifications Hub`~~_ Queues and Topics name length can be up to 260 (~~not documented anywhere~~ [MSDN](https://msdn.microsoft.com/en-us/library/azure/hh767287.aspx)). 

Note: `Notifications Hub` do not allow queues/topics creation.

Azure ServiceBus transport is is replacing long names with a deterministic GUID. To validate name for [topics](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/6b95553d676c881c62b514a2304ece85e0b4436c/src/Transport/Topology/QueueAndTopicByEndpoint/NamingConventions.cs#L120) and [queues](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/6b95553d676c881c62b514a2304ece85e0b4436c/src/Transport/Topology/QueueAndTopicByEndpoint/NamingConventions.cs#L25), 290 max length is used  which is breaking when `Messaging` namespace is used, causing endpoints to fail when deployed into azure servicebus namespace that is of `Messaging` type, but not when executed locally with test namespace of `Mixed` type.

**Original Issue** raised in user group: @johnfly https://groups.google.com/forum/#!topic/particularsoftware/XuHp_8wZ09o

### Update

It is no longer possible to create namespace of type `Mixed`, only `Notification Hub` and `Messaging` that are both now limiting to 260 characters

Things to do:
- [ ] Documentation

**Comment by yvesgoeleven** [comment]
Not according to this documentation https://msdn.microsoft.com/en-us/library/hh322663.aspx

**Comment by SeanFeldman** [comment]
Updated analysis. This is an issue with `Messaging` type of namespaces. `Mixed` and `Notification Hub` types accept names up to 290 characters.

**Comment by SeanFeldman** [comment]
Going through requirements discussion

**Comment by yvesgoeleven** [comment]
Looks like Mixed is now also max 260

**Comment by yvesgoeleven** [comment]
Requires documentation

**Comment by yvesgoeleven** [comment]
Replaced by https://github.com/Particular/NServiceBus.AzureServiceBus/issues/145
