### ISSUE TITLE
ICreateQueues implementation doesn't use identity passed by core

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#287]
As part of issue #283, it was identified that in addition to `QueueBinding`s, there's also an `identity` argument passed into `ICreateQueues.CreateQueueIfNecessary`. It's not used anywhere. 

1. What's the purpose of this argument?
1. Does ASB transport miss something by not using it?

@Particular/nservicebus-maintainers could please someone help us with identifying the purpose of `identity`? Thank you.

**Comment by danielmarbach** [comment]
The core passes `WindowsIdentity.GetCurrent().Name`. Does that mean anything in the context of the cloud? I doubt so.

**Comment by SeanFeldman** [comment]
@danielmarbach doubt it will :)
Constructive feedback for the core - to provide that information in the xmldoc.
The current xmldoc says:

```c#
/// <summary>
/// Creates message queues for the defined queue bindings and identity.
/// </summary>
Task CreateQueueIfNecessary(QueueBindings queueBindings, string identity);
```

Thank you for clarifying this. Closing issue as we don't need the identity.
