### ISSUE TITLE
Default: Move dead letters to centralized error queue

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#288]
By default the platform and all transports move messages that failed during Immediate and Delayed Retries to the centralized error queue. This should be the default for ASB v7 as well for "dead lettered messages". I recommend we make that behavior the standard behavior. Document the behavior breaking change in the upgrade guide and allow users to opt-out from that behavior.

**Comment by danielmarbach** [comment]
// cc @SeanFeldman

**Comment by SeanFeldman** [comment]
@danielmarbach all errors are sent to the single error queue defined by the core. The deadlettered messages are the ones that are not moved to the cetralized error queue. Just to be clear, we're talking about moving DLQed messages to the centralized error queue as well. Is this correct?

**Comment by danielmarbach** [comment]
yes correct. Feel free to reword a bit

**Comment by danielmarbach** [comment]
Changed it slightly

**Comment by yvesgoeleven** [comment]
We should set forwarding on the dlq then

**Comment by yvesgoeleven** [comment]
We can not default this because of the cross namespace limit, but users could set up a central queue per namespace and forward to that (doco issue to be created for this https://github.com/Particular/docs.particular.net/issues/1446)
