### ISSUE TITLE
Throw meaningful exception with a queue name when queue is not found upon sending

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#30]
When sending a message and queue is not found, exception should provide what queue was not found. Absence of a queue name makes investigation difficult as well as can masquerade the real problem.

Similar to [MSMQ transport]( https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqMessageSender.cs#L78)

**Original issue** was brought up by @jaldipp in [user group](https://groups.google.com/d/msg/particularsoftware/triuleAjDp4/ZrujnYmAiUYJ)

**Comment by SeanFeldman** [comment]
QueueNotFoundException is thrown

**Comment by jaldipp** [comment]
Hi,

Just wanted to say hello to you and let you know that I found something interesting for you, look at it here <http://ziltothyra.vahaug.com/uevzlfmv>

Sent from a prehistoric stone tablet, jaldipp@yahoo.com

**Comment by jaldipp** [comment]
Hello friend, 

I thought you  were interested in stuff like that, so probably that article would  be helpful to you, please  read it here <http://level.bendelbees.com/aeuofly>

Warmest, jaldipp
