### ISSUE TITLE
Allow AMQP protocol

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#306]
With ASB v3 the default communication protocol is AMQP and not SBMP.
[Documentation](https://azure.microsoft.com/en-us/documentation/articles/service-bus-amqp-protocol-guide/) says:

> The proprietary SBMP protocol that is also supported is being phased out in favor of AMQP.

## Current state of things

There's no API to change transport type and current implementation defaults to SBMP.
Currently we're telling customers that they can change connectivity mode by using connection string and append  a string to influence it. With transport type that won't work since appending

- `;TransportType=Amqp` or 
- `;TransportType=NetMessaging`

to connection string will not be changing anything.

Unfortunately, we're creating `MessagingFactory` not by using a raw connecting string (`MessagingFactory.CreateFromConnectionString(connString)`), but by using [`MessagingFactory.CreateAsync(namespaceManager.Address, MessageFactorySettings)`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/212d068b2ac8ab11f26c128b6e68e6f8697eee10/src/Transport/Connectivity/MessagingFactoryCreator.cs#L47). Messaging factory settings needs to have `TransportType` property to be set explicitly, which we don't. 

## Update 2016-08-24

Version 6 of the transport did **not** allow changing transport type and was solely SBMP based.
This would be considered a new feature.

## Update 2016-08-26

Can't make AMQP the default at this point due to performance issues we're currently experiencing. A [new issue](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/313) is opened for this

## PoA

- [x] Add transport extension to configure transport type
- ~~Set default transport type to AMQP~~ replaced by issue #313
- [x] Update implementation to respect the new transport setting
- [x] Update documentation [PR #](https://github.com/Particular/docs.particular.net/pull/1821)

**Comment by SeanFeldman** [comment]
Quick validation:

```c#
MessagingFactory.CreateFromConnectionString(connectionString);
MessagingFactory.CreateFromConnectionString(connectionString + ";TransportType=Amqp");
MessagingFactory.CreateAsync(namespaceManager.Address, mfs_with_no_transporttype_specified);
MessagingFactory.CreateAsync(namespaceManager.Address, mfs_with_transporttype_specified);
```

results in

```
Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessagingFactory
Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory
Microsoft.ServiceBus.Messaging.Sbmp.SbmpMessagingFactory
Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory
```

**Comment by SeanFeldman** [comment]
Setting transport type to AMQP is [currently breaking](https://builds.particular.net/project.html?projectId=NServiceBusAzure_NServiceBusAzureServiceBus&branch_NServiceBusAzure_NServiceBusAzureServiceBus=307) and we'll need to investigate to find out what's happening.

**Comment by SeanFeldman** [comment]
Question: if we implement support to switch to AMQP _and_ decide to set it as a default, wouldn't that require a new major? And if so, would we want to get in in NSB v6 round or it doesn't matter and we can release it as transport vNext rather than v7?

**Comment by SeanFeldman** [comment]
PS: assuming public API and behaviour of the transport is not going to change.

**Comment by yvesgoeleven** [comment]
AMQP doesn't support transactions/sendvia, so we should not default to it. I'll make sure the supported tx mode is lowered if AMQP is enabled explicitly by the user

**Comment by SeanFeldman** [comment]
So there no feature parity? Need to verify as ASB team claims there is.

**Comment by SeanFeldman** [comment]
AMQP protocol still doesn't support transactions/send-via.
