### ISSUE TITLE
Delivery count to respect Immediate retries and user settings

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#308]
## Description

Before the new retries seam implementation, retries feature did not respect the native `DeliveryCount`. 
NSB.ASB is setting the default value to [10 and we expect customers to adjust it](http://docs.particular.net/nservicebus/azure-service-bus/configuration/full#controlling-entities-queues) according to what is configured with Immediate and Delayed retries.

With the new seam in place, native delivery counter is used by immediate and delayed retries and we we could configure `DeliveryCount` to match Immediate retries count (Delayed retries are not relevant since  SLRed messages are brand new message).

## Proposal

Leave the default and reconfigure `DeliveryCount` to match Immediate retries (ex-FLR) and allow user override with validation to ensure user setting is no less than Immediate retries count is set to.

## Technical Info

Delivery count is configured for [queues](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Config/DefaultConfigurationValues.cs#L72) and [subscriptions](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Config/DefaultConfigurationValues.cs#L114).

Core exposes the setting via [`NumberOfImmediateRetries`](https://github.com/Particular/NServiceBus/blob/e3a465651022f4ecb2ad56909495bf324dea8e6a/src/NServiceBus.Core/Recoverability/Recoverability.cs#L214) settings key.

## PoA
- [x] Implement changes PR #333
- [x] [Update documentation and upgrade guide](http://docs.particular.net/nservicebus/azure-service-bus/retries#first-level-retries-vs-maxdeliverycount) [PR #1945](https://github.com/Particular/docs.particular.net/pull/1945)

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers should we get this into RC?

**Comment by SeanFeldman** [comment]
@yvesgoeleven ping

**Comment by yvesgoeleven** [comment]
@SeanFeldman did we miss this one? I think we can do it on maintainer budget, has no impact on api

**Comment by SeanFeldman** [comment]
Question: When an entity is created, we set the `MaxDeliveryCount` with the [default value](http://docs.particular.net/nservicebus/azure-service-bus/retries#first-level-retries-vs-maxdeliverycount). If we are switching to using `NumberOfImmediateRetries` would this be an issue when an endpoint code redeployed and immediate retries are changing, causing `MaxDeliveryCount` of already existing entities to change?

**Comment by yvesgoeleven** [comment]
1. I don't think this is a problem
2. I don't know, it really depends on the consumer of the audit & error queues. Can we use the default for queues that we're not going to consume from instead?

**Comment by andreasohlund** [comment]
Using defaults for non shared queues like audit/error sounds resonable to me. It this something that SC should care about thought? (Since sc will consume from it?)

**Comment by SeanFeldman** [comment]
@andreasohlund "non shared"? I thought `audit` and `error` queues are shared by multiple endpoints.

We could apply defaults for those queues, but question is how to know what those queues are? `ICreateQueues` gets `QueueBindings`, and names (`queueBindings.SendingAddresses`) won't necessarily indicate if a queue is an error/audit queue or not.

**Comment by andreasohlund** [comment]
My bad, should be shared, edited

**Comment by SeanFeldman** [comment]
I was wrong about `QueueBindings.SendingAddresses` (thank you @andreasohlund for clarification).

Let me try to sum it up:
- `QueueBindings.SendingAddresses` will always contain the shared queue names.
- `QueueBindings.SendingAddresses` will contain dedicated (other endpoints) names it sends messages to
- ErrorQ and AuditQ values can be retrieved from the settings as @andreasohlund pointed out. `settings.ErrorQueueAddress()` & `settings.TryGetAuditQueueAddress()`

Applying default values to `MaxDeliverCount` for shared queues won't be an issue. Potential issue might be in how ASB transport creates resources. Opened a separate issue (#3xx) for that.

**Comment by SeanFeldman** [comment]
Trying to find documentation on QueueBinding, stumbled upon a [sample](https://docs.particular.net/samples/custom-transport/#transport-implementation-queuecreation) that shows that `queueBindings.SendingAddresses` should be used to create queues...

**Comment by SeanFeldman** [comment]
A few scenarios to think of:

1. A CPU intense endpoint with a prefetch that is too aggressive scenario. Delivery count on a message will be increased each time lock token is lost. Eventually it could surpass the `MaxDeliveryCount` set to the value of `NumberOfImmediateRtries`, causing message to **go to the DLQ w/o being processed**.  No different from what could have happened in the past. On a positive side, we can now centralise DLQ-ed messages.

2. Delivery count doesn't surpass `NumberOfImmediateRtries`, but still message lock token is lost a few times. The retries mechanism logic is based on the native message delivery counter, and as a result of that there will be **less** than`NumberOfImmediateRtries` immediate retries.

@Particular/azure-host-maintainers @andreasohlund do you see any major issues with scenarios or can poke more holes?
