### ISSUE TITLE
Document native integration

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#31]
Document how you can perform native integration (f.e. legacy xml), but still benefit from the nsb pipeline capabilities

**Comment by SeanFeldman** [comment]
@yvesgoeleven does [this sample](docs.particular.net/samples/azure/native-integration-asb/) resolves this issue?

**Comment by yvesgoeleven** [comment]
needs doco for the vnext way

**Comment by SeanFeldman** [comment]
Doco added: http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#configuring-in-detail-brokeredmessage-body-conventions
