### ISSUE TITLE
Performance drop somewhere in last few beta versions

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#314]
Since August 19th performance for a test has severely degraded. These are the numbers of the Azure test environment but a similar degradation is visible when running the tests locally ().

![image](https://cloud.githubusercontent.com/assets/152998/18052559/5e35d2ac-6dfb-11e6-9acf-3fb1d792fe5e.png)

Source:

* http://deploy.particular.net:8000/en-US/app/search/transports_fixture?form.transport_kind=AzureServiceBus&form.nsb_version=V6&form.nsb_version=V5&earliest=0&latest=&form.testRunId=636078182711414446
* https://github.com/Particular/EndToEnd/commits/master/src/PerformanceTests/NServiceBus6/packages.config (6.0.0-beta0007)
* https://github.com/Particular/EndToEnd/blob/master/src/PerformanceTests/Transport.V6.AzureServiceBus.V7/packages.config (ASB 7.0.0-beta0012)

**Comment by andreasohlund** [comment]
@Particular/azure-service-bus-maintainers could this be the atomic sends with receive change?

@ramonsmits have you done any testing of the `ReceiveOnly` mode?

**Comment by yvesgoeleven** [comment]
@ramonsmits @andreasohlund yes that could be, we had to drop batched completion as we noticed that send via feature wasn't really working properly... ReceiveOnly still does batched completion

**Comment by andreasohlund** [comment]
@ramonsmits can you confirm that ReceiveOnly tests still perform well? (just to narrow this down)

**Comment by WojcikMike** [comment]
@andreasohlund there is no TransactionMode being set so it runs on default. The only change from test perspective is that on 19th of August:
https://github.com/Particular/EndToEnd/commit/cc06a07d9c17bc939f2291a590ff97bda4f0ef31#diff-4ba3206003888d01f27512edf29f4b3c

When it comes to the test ReceiveRunner it is the light green test on the diagram showing the biggest drop.

**Comment by SeanFeldman** [comment]
@WojcikMike by default, a single namespace is used and other configurations that influence transport transaction mode are set to enable `SendsAtomicWithReceive`. Hence the default behaviour has changed, which is impacting the overall performance.

Would it be possible to run both tests, for `SendsAtomicWithReceive` and `ReceiveOnly`?

**Comment by ramonsmits** [comment]
@andreasohlund @WojcikMike @SeanFeldman The scenarios has a send and a receive part. The duration of the whole affects the throughput calculation. 

I can create a scenarios to test performance of SendsAtomicWithReceive and ReceiveOnly. Do you also want to test performance of these on the previous betas?

**Comment by SeanFeldman** [comment]
@ramonsmits it would make sense to compare apples to apples (ie older versions with new).
Saying that, is there a chance we can collaborate on this?

**Comment by SeanFeldman** [comment]
@ramonsmits any updates?

**Comment by SeanFeldman** [comment]
@ramonsmits do you still see a significant drop?

**Comment by SeanFeldman** [comment]
@ramonsmits could you please update this issue? Thanks.

**Comment by SeanFeldman** [comment]
@ramonsmits is this still an issue?

**Comment by ramonsmits** [comment]
Performance tests on the Azure environment shows that SendsAtomicWithReceive performance is very bad.

Source: http://deploy.particular.net:8000/en-US/app/search/transports_fixture

In a receive test only got 3.1 msg/s on average. Based on earlier conversation with @yvesgoeleven on Slack I increased the maximum concurrency to 64 * logical cores which results in 512 on the Azure VM. The prefetch count is 3 * the maximum concurrency so that is 1,536 as he said ASB would benefit a lot from the allowed maximum concurrency and prefetching.

It seems that V7 doesn't like this, especially not in combination with SendsAtomicWithReceive

## Packages

```
  <package id="NServiceBus" version="6.0.0-rc0002" targetFramework="net452" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="7.0.0-rc0004" targetFramework="net452" />
  <package id="WindowsAzure.ServiceBus" version="3.4.0" targetFramework="net452" />
```

Doing local dev box tests with maximum concurrency level = logical cores the transport is stable. That is maximum concurrency level = 8 (logical cores) and prefetch = 24 (8*3) this with ReceiveOnly I'm able to get 700 msg/s but with SendsAtomicWithReceive the experience isn't as good with ReceiveOnly, performance is just below 100 msg/s.

Graph of throughput, third block is SendsAtomicWithReceive:

![image](https://cloud.githubusercontent.com/assets/152998/18946586/d8c45c04-862f-11e6-8aba-81344fd0c4c3.png)


It seems that it indeed was caused due to using SendsAtomicWithReceive as the test used the default transaction mode.

**Comment by yvesgoeleven** [comment]
@ramonsmits I think you switched the settings, the ones applied to atomic should be the low ones, the ones for receive should be the high ones

**Comment by SeanFeldman** [comment]
A few things wanted to highlight about how we go about performance:

1. ASB performance optimizations are not finalized. @Particular/azure-service-bus-maintainers are still discovering undocumented features/information as we go.
1. The definition of "bad" is relative. Considering that `SendsAtomicWithReceive` requires transaction to take place per message, will decrease the performance significantly. Also, we should compare v6 with v7. If v6 in equivalent mode was sending 10 msg/s top, then we should compare that with 100 msg/s in v7. That's a x10 improvement. Yes, we'll strive to get even higher numbers, but we shouldn't consider v7 performance as a no-go. Not to mention that performance improvements can and will be released as minor releases.
1. Clearly define test scenarios with the configuration parameters used for those. Slack conversations, zoom calls, GH issue - should consolidate those. Otherwise it's all over the place and, personally, can't track it.
1. Have a **call** to make sure we're talking the same "language".

Thank you.

**Comment by SeanFeldman** [comment]
@ramonsmits I believe this issue is addressed now. Shall we close it?

**Comment by ramonsmits** [comment]
I think so, although our latest findings regarding configuring ASB for high throughput should be documented.

I checked https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Config/DefaultConfigurationValues.cs and the defaults seem to be aligned.

**Comment by SeanFeldman** [comment]
👍 @ramonsmits that is already taking place - @yvesgoeleven works on a sample/doco
