### ISSUE TITLE
Performance issues with ConnectionString..ctor(String)

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#332]
A quick test (sending 100 messages) shows that from the total execution time of 421 ms, sender spends 72 ms on regex operations performed by `ConnectionString` ctor. Roughly 28% of the execution time.
![image](https://cloud.githubusercontent.com/assets/1309622/18639999/62188e38-7e53-11e6-9d2c-6edaed036d0f.png)

Potential offenders:
- [ctor](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Topology/MetaModel/ConnectionString.cs#L28-L30)
- [TryParse](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/release-7.0.0/src/Transport/Topology/MetaModel/ConnectionString.cs#L64)

**Comment by abombss** [comment]
I thought service bus sdk has a connection string builder / parser that you can pull the namespace from.
 https://msdn.microsoft.com/en-us/library/microsoft.servicebus.servicebusconnectionstringbuilder.aspx

**Comment by SeanFeldman** [comment]
@abombss you're correct. We could have used
`ServiceBusConnectionStringBuilder`, but...

1. It doesn't always throw a meaningful exception in the context of the
transport (see example 1 below)
2. Fails to perform basic validation a namespace name should undergo (see
example 2 below)

**Example 1**

```c#
var csb = new ServiceBusConnectionStringBuilder("Endpoint=sb://
mynamespace.servicebus.windows.net;SharedAccessKeyName=secret");
```
Will throw a vague exception:

```
Some of the configuration is missing a required component. Make sure all or
none of the following properties are defined as part of
'Microsoft.ServiceBus.ConnectionString' key within 'appSettings' section,
or Windows Azure configuration settings:
[SharedAccessKeyName,SharedAccessKey]
Parameter name: connectionString
```

**Example 2**

```c#
var csb = new ServiceBusConnectionStringBuilder("Endpoint=sb://
a.servicebus.windows.net
;SharedAccessKeyName=secret;SharedAccessKey=sastoken");
var ep = csb.Endpoints.First();
Console.WriteLine(ep.DnsSafeHost.Split(new[] { '.'}).First()); // "a"
Console.WriteLine(csb.SharedAccessKeyName);
Console.WriteLine(csb.SharedAccessKey);
```

Will not throw even though namespace name `a` is invalid.

**Comment by yvesgoeleven** [comment]
This is in RC6
