### ISSUE TITLE
Produce scripts to generate system queues

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#335]
## Problem description

Part of the discussion in issue #308 (Delivery count to respect Immediate retries and user settings), brought up the issue with how resources are created by an executing endpoint. 

`TransportResourcesCreator` is creating the resources needed for an executing endpoint.
`ForwardingTopologySectionManager` is used to determine what resources need to be created. When it does so, it uses [SendingAddresses](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/108b46f049d75af03bd7a4486303fcb766cc4c1a/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs#L73) which is wrong.
(`EndpointOrientedTopologySectionManager` equivalent is [here](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/108b46f049d75af03bd7a4486303fcb766cc4c1a/src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs#L67))

Example: endpoint A sends messages to B. B has created its queues first, then A goes through the startup process and will create its own queues, including those in `QueueBindings.SendingAddresses`. That will include error queue, audit queue, and B`s input queue. Since queues exist, it will only update those. Some of the side effects - causing`MaxDeliveryCount`to be updated to A`s `NumberOfImmediateRtries` and losing the original values.
## Questions to answer
1. Who's responsible to create error and audit queues? If endpoint shouldn't do this, it's a bug we need to fix and document. 
2. First time UX consideration w/o shared queues being created. How important that aspect is?
## Update 2016-09-21

System Queues are the queues shared by multiple endpoints (e.g. Audit and Error queues). In the future (TBD), system queues should not be created by endpoints, but by OPs only. Therefore, build process should be emitting script to assist with that. For the F5 experience, it would be ideal to create those queues to make things easier.

Connects to https://github.com/Particular/NServiceBus.Azure/issues/310

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers please chime in.
/cc @andreasohlund

**Comment by yvesgoeleven** [comment]
I thought we changed our mind about creating audit & error, as it improves first time user experience if they are created automatically? We should indeed watch out with settings on those

**Comment by andreasohlund** [comment]
>I thought we changed our mind about creating audit & error,

Yes we currently create those to enable a good F5 experience. Going forwards, in in future majors, I hope we can move to a model where F5 is handled by development transport + development persistence and for the "real" transports we instead provide guidance and scripts that shows users how to set this up for their production environments since having all the endpoints create those queues concurrently at startup is a recipe for pain.

Side note: 
Does this even work in Azure given that you have to have admin rights to create queues and running with admin rights is a no go from a security perspective?

The NSB host solves this by asking the users to run `NServiceBus.host.exe /install` as admin to setup the queues and then start the endpoints as a restricted account?

The above of course fails if you host your endpoints in eg. IIS so there we guide them to script those queues: 

https://docs.particular.net/nservicebus/msmq/operations-scripting#create-queues-creating-queues-for-an-endpoint

@SimonCropp has some cool ideas to output the needed scripts during compile time into a `.deployment` folder or similar which I really like (again this is the future not for this version)

**Comment by yvesgoeleven** [comment]
@andreasohlund we don't need to run as admin to create queues, but we do need a connectionstring with manage accounts. We test the connectionstring to see if the demand to create queues matches up with the connectionstring claims and report if we don't hav sufficients rights.

**Comment by yvesgoeleven** [comment]
@andreasohlund but I'm right that for this version we need to create the audit & error queue, right?

**Comment by andreasohlund** [comment]
>we don't need to run as admin to create queues, but we do need a connectionstring with manage rights

Does this conflict with "security best practises" for ASB in general?

>but I'm right that for this version we need to create the audit & error queue, right?

Correct!

**Comment by SeanFeldman** [comment]
Let's focus on the question for V7 of ASB (NSB v6): should or should not create Audit and Error queues: the answer I hear is "YES". Design moving forward is in the future, we need to address #308 first.

If that's the consensus, then:

1. An executing endpont can (and will) create shared queues. 
1. An executing endpoint should *not* create other endpoints queues

**Comment by yvesgoeleven** [comment]
@SeanFeldman correct, but that's what we do (I've been ensured that only error & audit are in queuebindings)

@andreasohlund we can run fine with a limited account as well, user just has to turn create queues off.

**Comment by SeanFeldman** [comment]
@andreasohlund could you please comment on 
> @SeanFeldman correct, but that's what we do (I've been ensured that only error & audit are in queuebindings)

**Comment by SeanFeldman** [comment]
Trying to find documentation on QueueBinding, stumbled upon a [sample](https://docs.particular.net/samples/custom-transport/#transport-implementation-queuecreation) that shows that `queueBindings.SendingAddresses` should be used to create queues...

**Comment by andreasohlund** [comment]
>as a feature creator you can add there any queue and have it created on startup

I'd say if a feature add this it's to be considered a "system queue" just like error+audit so we should create that one as well.

In short: We should for now create all the queues not belonging to other endpoints just like you stated above 👍

**Comment by SeanFeldman** [comment]
@andreasohlund "system queues" is a good replacement for "shared queues". ❤️ that.
I'll keep this issue opened as a Feature request and update the description.

**Comment by danielmarbach** [comment]
We have a few ideas to support this better in the new transport. Closing
