### ISSUE TITLE
Excessive INFO logging of NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#336]
For some reason the following is logged a lot:
```
2016-09-19 20:21:44.5837|INFO|16|NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator|Checking existence cache for 'PerformanceTest'
2016-09-19 20:21:44.5837|INFO|16|NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator|Determined that the queue 'PerformanceTest' exists
2016-09-19 20:21:44.5837|INFO|16|NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator|Queue 'PerformanceTest' already exists, skipping creation
```

Either there is something wrong but if this is 'normal' then the log level should not be INFO but DEBUG.

## References

- https://builds.particular.net/repository/download/PerfTests_DeployAndRun/187850:id/perftests/%40/Performance/TransactionModesFixture/GatedSendLocalRunner/V5~AzureServiceBus~None~/trace.log
- https://builds.particular.net/repository/download/PerfTests_DeployAndRun/187850:id/perftests/%40/Performance/TransactionModesFixture/GatedSendLocalRunner/V5~AzureServiceBus~Receive~/trace.log

**Comment by yvesgoeleven** [comment]
It is normal, and that log exists in prior versions as well, but maybe we should remove the log statement, not the first time someone complains about it (or interprets it wrong)

**Comment by SeanFeldman** [comment]
I don't like dropping those longs. Rather reword the message if it's not clear, but let know what's going on.

**Comment by SeanFeldman** [comment]
All those logs are V5? Is that old logs we're looking at @ramonsmits ?

**Comment by ramonsmits** [comment]
Sorry, this is also based on V5 logging. Had this discussion some time ago with @SeanFeldman and that would be a 'breaking' change. AFAIK this isn't happening in this excess with V6.

**Comment by ramonsmits** [comment]
Closing this including a logging filter for NLog which prevents the excessive logging:

```xml
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <targets>
      <target name="file" xsi:type="File" fileName="trace.log" layout="${longdate:universalTime=true}|${level:uppercase=true}|${threadid}|${logger}|${message}${onexception:${newline}${exception:format=tostring}}" />
    </targets>
    <rules>
        <logger name="NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator" maxlevel="Info" final="true" />
        <logger name="NServiceBus.Distributor.MSMQ.*" maxlevel="Info" final="true" />
        <logger name="*" minlevel="Info" writeTo="file" />
    </rules>
  </nlog>
```

**Comment by Maqster6** [comment]
Hi, could you provide the same filter but for Log4Net?
