### ISSUE TITLE
Allow to disable native deferral

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#338]
See https://twitter.com/tekmaven/status/776793287206248448 for more context

> Need timeouts for long periods (1 yr).  we hit queue quota and killed our endpoint.  db timeouts are better in this case.

**Comment by SeanFeldman** [comment]
We're using `ScheduledEnqueueTimeUtc`. We can go one (and more) years with the value. that doesn't work @tekmaven ?

**Comment by yvesgoeleven** [comment]
@SeanFeldman we can go on until the queue is filled up, that's @tekmaven's problem, the queue is full with future messages

**Comment by SeanFeldman** [comment]
Ah, ok. So it's not the setting when the message will show up, but having way too many messages to chew up the space on queue. Got it.

**Comment by tekmaven** [comment]
The workaround I have right now (in v5) is to use a custom container, call this on startup: 
```
busConfiguration.EnableFeature<TimeoutManagerBasedDeferral>();
busConfiguration.EnableFeature<TimeoutManager>();
```
and finally, configure the container to always return `TimeoutManagerDeferrer` when it resolves `IDeferMessages`.  This is all a little hacky, and even worse because `TimeoutManagerDeferrer` is not public.

**Comment by SeanFeldman** [comment]
@tekmaven thinking out loud - the max queue size is 5 GB. If you have [partitioning enabled,](https://azure.microsoft.com/en-us/documentation/articles/service-bus-partitioning/#enable-partitioning) you multiply that by 16, in essence getting your queue size increased by 75 GB. Would that work for you?

**Comment by SeanFeldman** [comment]
@tekmaven have you tried the suggested above approach?
Also, could you please let us know how big are the future messages that 5GB is not enough. Would be good to understand the business need. Thank you.

**Comment by SeanFeldman** [comment]
@tekmaven did you have a chance to look into my suggestion? Thanks.

**Comment by tekmaven** [comment]
Hey Sean,

We implemented my workaround for this to use the db.  NSB is all about options, why force people to go in one direction?

-Ryan

**Comment by SeanFeldman** [comment]
@tekmaven intention was not to force into a single direction, but see if this would work for you.
Glad to hear workaround works. for you.

**Comment by danielmarbach** [comment]
From a platform perspective, we are mostly abandoning the timeout manager and implement native deferral on all the transports where we can. Closing this since we won't move forward on this one.
