### ISSUE TITLE
Disable prefetching by default in combination with transaction mode none

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#340]
While talking about prefetching I was wondering what the behavior is during graceful shutdown specifically to this question:

- Are message that are already 'prefetched' but not yet processed still processed until the prefetch buffer/queue is depleted

If the answer is no and the customer is running with transaction mode 'None' than we have potential message loss during a 'graceful shutdown' even though no errors occur as the messages in the prefetch buffer are then discarded.

If this behavior is our actual behavior we should write a WARN log entry stating something like the following at startup

> WARN Prefetchsize is larger than 0 while transaction mode is 'None'. This can result in message loss during normal operation.

Also, during shutdown, we should log a similar message for each discarded message if possible.

## Update 2016-09-26

The transport will not set a default `PrefetchCount` if receive mode is `ReceiveAndDelete`, unless user has explicitly configured `PrefetchCount` using an API.

## PoA
- [x] Implement the change PR #346 
- [x] Update documentation to make it clear that `PrefetchCount` **will** be used if configured despite the `ReceiveAndDelete` mode. [PR #1964](https://github.com/Particular/docs.particular.net/pull/1964)

**Comment by yvesgoeleven** [comment]
@ramonsmits they will be gone, running in transaction mode none is very dangerous regardless of prefetch as stated in our docs. I'm ok with adding a warn statement (I'd rather see this mode gone completely)

**Comment by SeanFeldman** [comment]
I wonder if we should automatically disable prefetching if mode is Receive-and-Delete

**Comment by bording** [comment]
> I wonder if think we should automatically disable prefetching if mode is Receive-and-Delete

An alternative would be to not actually use a Receive-and-Delete mode, which is what I ended up doing in Rabbit, for a number of reasons.

**Comment by SeanFeldman** [comment]
What we'll do is disable prefetch by default with `ReceiveAndDelete`, but allow it to be configured through API if needed. While `ReceiveAndDelete` is dangerous, it does allow faster throughput and if loosing individual messages is not a problem, this mode can be helpful. Wherever it fits the overall NSB offer, is a different issue that should be discussed. [All transport support unreliable mode](https://docs.particular.net/nservicebus/transports/transactions) today. Are you saying the doco is incorrect @bording?

**Comment by bording** [comment]
>  All transport support unreliable mode today. Are you saying the doco is incorrect @bording?

No, I wouldn't say that. We already document that we don't really do anything different for the two modes: https://docs.particular.net/nservicebus/rabbitmq/transactions-and-delivery-guarantees

**Comment by SeanFeldman** [comment]
@ramonsmits please see the general description with update. Do you still think we should log a warning?

**Comment by SeanFeldman** [comment]
@ramonsmits log entry [added](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/346/commits/1b9791bb5e5f775e45a437257b83b3a75d8c4888)

**Comment by ramonsmits** [comment]
I think the concern is addressed so we can close this case @SeanFeldman

**Comment by SeanFeldman** [comment]
Need to update doco first ([PoA section](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/340#issue-178616712)), and then will be able close this.

**Comment by SeanFeldman** [comment]
Will go out with RC5
