### ISSUE TITLE
Outbox doesn't work with ASB transport

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#352]
## Who's affected

Anyone using Azure Service Bus transport in conjunction with the Outbox feature

## Symptoms 

Handlers process messages and then NHibernate.Exceptions.GenericADOException is thrown with a message `could not execute query, System.ComponentModel.Win32Exception: The wait operation timed out`, eventually moving incoming messages into the error queue.

## Workaround

Set transport transaction mode to `ReceiveOnly` explicitly.

```c#
var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
transport.Transactions(TransportTransactionMode.ReceiveOnly); // lower transport transaction mode
```

**Comment by ramonsmits** [comment]
@SeanFeldman What exactly is the cause of this? Is it because SendsAtomicWithReceive uses a TransactionScope? What happens when a user explicitly does `transport.Transactions(TransportTransactionMode.SendsAtomicWithReceive)` and enables outbox?

**Comment by yvesgoeleven** [comment]
@ramonsmits personally haven't tested that yet, I'd assume outbox to throw an exception that you can't do that

**Comment by SeanFeldman** [comment]
@ramonsmits the cause was a bug in the transport resolved by PR. The core was setting a default setting, while the transport was looking for an [explicit override](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/353/files#diff-abc21d576eebe5908bcca158905c4878R50).
