### ISSUE TITLE
Publishing same type of event from more than one BC is not working

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#36]
According to ADSD (SOA Building blocks - part 5) several BCs (business components) of the same service should be able to publish same type of event. It is achieved by shared `Subscription Storage` among BCs of the same service.

![image](https://cloud.githubusercontent.com/assets/1309622/7675802/f0030de0-fcf9-11e4-9e1e-02a556644897.png)

"While an event should have one specific publisher, it is OK for BCs of the same service to publish the same event. There's no worry about single source of truth, since BCs deal with partitioned deployment of the same business and there will be no contradicting events as far as external system`s concern". 22 min into part 5.

---

This is not working for ASB with native Azure Service Bus pub/sub implementation. Registration sent for an event by an external service is associated solely with the endpoint registration was sent to and not shared with other BCs.

@udidahan could you please confirm?
//cc @yvesgoeleven

**Comment by udidahan** [comment]
Confirmed.

This would hold true even if you have a component of a single service deployed to multiple systems.

**Comment by yvesgoeleven** [comment]
In the current topology, you would indeed need to explicitly subscribe to both origin endpoints as the topics are organised per endpoint and not per type. In the new topology, this should be fixed though.

**Comment by udidahan** [comment]
Then that's going to need some documentation :)

**Comment by yvesgoeleven** [comment]
After discussion with @SeanFeldman it looks like none of the transports can do this, as the core doesn't allow to subscribe to the same message type multiple times in it's message mappings. Internally the message mappings are kept in a dictionary resulting in an exception if you try to register the same type with a different endpoint.

PS: we are really talking about 2 different BC's (aka different code bases, not different instances of the same BC) to be the source of the same event type, imo this is really bad design.

**Comment by andreasohlund** [comment]
>After discussion with @SeanFeldman it looks like none of the transports can do this

Not 100% true, the ones that uses storage driven pubsub (msmq, asq + sql) can do it by sharing the same subscription storage like shown in the picture above in @udidahan 's picture.

Subscribers then just have to pick one of them when subscribing

**Comment by yvesgoeleven** [comment]
@andreasohlund but you would have to manually prepopulate that store, as you cannot route subscription messages to both

**Comment by SeanFeldman** [comment]
@andreasohlund it feels wrong. We rely on the fact that subscription storage is _shared_ (despite what is told about BCs - share nothing like angry siblings). If it's not shared, then it's not possible or workarounds are needed. Also, message mapping is not supportive for this scenario. You can't subscribe to the same event from two BCs using the same syntax, but you can if you tweak how you do it. Example:

**Failing mapping**
``` C#
            return new UnicastBusConfig
            {
                MessageEndpointMappings = new MessageEndpointMappingCollection
                {
                    new MessageEndpointMapping
                    {
                        Endpoint = "x-receiver-regular",
                        Messages = "Messages.Events.NotifyEvent, Messages"
                    },
                    new MessageEndpointMapping
                    {
                        Endpoint = "x-receiver-preferred",
                        Messages = "Messages.Events.NotifyEvent, Messages"
                    }
                }
            };
```

**working mapping**
``` C#
            return new UnicastBusConfig
            {
                MessageEndpointMappings = new MessageEndpointMappingCollection
                {
                    new MessageEndpointMapping
                    {
                        Endpoint = "x-receiver-regular",
                        Messages = "Messages.Events.NotifyEvent, Messages"
                    },
                    new MessageEndpointMapping
                    {
                        Endpoint = "x-receiver-preferred",
                        AssemblyName = "Messages",
                        Namespace = "Messages.Events"
                    }
                }
            };
```

**Comment by DavidBoike** [comment]
I *think* that Udi would say the "angry siblings" things pertains to business data. Subscription storage is part of the infrastructure, owend by the IT/Ops service, so it doesn't count. Implementation detail, essentially.

**Comment by SeanFeldman** [comment]
@DavidBoike implementation details, yes. Not so sure about IT/Ops service here.
Questions that I still have is: if this is a valid case, should subscription syntax support it explicitly?

**Comment by DavidBoike** [comment]
I think so. Is there something that can point me to what the new topology looks like because I want to learn.

With SQS on another project, I created topics based on only message type. It may have been naive, but it would have supported publish from anywhere. It had the additional wrinkle that if you took event inheritance into account, you had to create a topic for every individual class, which could get out of control quickly.

**Comment by udidahan** [comment]
> I think that Udi would say the "angry siblings" things pertains to business data. Subscription storage is part of the infrastructure, owend by the IT/Ops service, so it doesn't count. Implementation detail, essentially.

@DavidBoike right.

**Comment by SeanFeldman** [comment]
To sum this up: 
1. We need to have a better way to represent logical vs physical ("subscribe to an event from a Service, which can be published from physical BCs)
2. ASB transport to address this in the next major version
