### ISSUE TITLE
Change IManageMessageSenderLifeCycle & IManageMessageReceiverLifeCycle to return a task

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#362]
So that the inner `EntityClientEntry` can be turned into a task and awaited when used, instead of the `.GetAwaiter().GetResult()` calls in this method

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/587

**Comment by danielmarbach** [comment]
Done via https://github.com/Particular/NServiceBus.AzureServiceBus/pull/613. Closing
