### ISSUE TITLE
Unclean transport shutdown where not all batched message completions are awaited

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#365]
## Who's affected

Anyone using Azure Service Bus transport version 7.0.0

## Symptoms

When shutting down, the transport is supposed to complete all messages in-flights within 30 seconds from shutdown request. When multiple receivers are used, only a single receiver is awaited, causing transport to close receiver connections w/o waiting for the rest of batched completion tasks to handle their work. This could results in interrupting native client work upon ASB transport shutdown which would lead to native ASB client throwing exceptions.

**Comment by danielmarbach** [comment]
@seanfeldman ha! Gotcha you didn't mention the people involved in this finding ;) (hehehe just playing back)

**Comment by SeanFeldman** [comment]
@danielmarbach you're too quick. Was about to update it 😉
