### ISSUE TITLE
Performing BatchedCompletion task with concurrency more than one

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#372]
## Reasons for this discussion

- The discussion was triggered by code review @danielmarbach and myself did for `MessageReceiverNotifier` which resulted in hotfix-7.0.1 and fix of issue #365. When transport switched to multiple receivers, we were only awaiting for a single receiver, rather all of them when stopping notifier.
- Additional issue that was addressed, #369 working with @ramonsmits, which also highlighted the complexity of the completion and the need to review it.

## Assumptions made and questions

- Running multiple completion tasks, each handling up to 5K message completions. With a possibility to configure a high number of clients per entity, the same number of completion tasks will be created. Should we adopt/change it?

- On shutdown, do we drain completion tasks efficiently and correctly?

@Particular/azure-host-maintainers @danielmarbach thoughts?

**Comment by yvesgoeleven** [comment]
Also related AMQP requires completion to happen on same receiver as receive operation (even when batched): https://github.com/Particular/NServiceBus.AzureServiceBus/issues/379

**Comment by yvesgoeleven** [comment]
@SeanFeldman this one is done right?

**Comment by SeanFeldman** [comment]
@yvesgoeleven correct
