### ISSUE TITLE
Got 'PrefetchCount was reduced to zero...' while explicitly setting PrefetchCount

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#374]
Version: 7.0.1

I get this message even though I explicitly set prefetch value.

> 2016-10-14 08:07:59.1679|WARN|1|NServiceBus.AzureServiceBusTransport|Mesasge receiver PrefetchCount was reduced to zero because to avoid message loss with ReceiveAndDelete receive mode. To enforce prefetch, use configuration API to set the value explicitly.

Not sure if prefetching is now even enabled.

**Comment by ramonsmits** [comment]
There is also a typo in the message.

**Comment by yvesgoeleven** [comment]
@ramonsmits it is, we lower the default. but that should be reflected in the message, good catch

**Comment by ramonsmits** [comment]
Mmm, there is something missing in the description. I got this message while I explicitly configured prefetching with the API.

**Comment by yvesgoeleven** [comment]
@ramonsmits indeed, I'll change it to be explicit about us changing default, not the setting itself

**Comment by ramonsmits** [comment]
Not sure if I understand you.

I expected that I do not get this, that prefetching is enabled even though it can result in message loss. If we still set it to 0, then I expect an exception as I've explicitly configured that in the API.

**Comment by yvesgoeleven** [comment]
@ramonsmits got it, I made it so https://github.com/Particular/NServiceBus.AzureServiceBus/pull/375
