### ISSUE TITLE
Review connectivity pool of Factories vs pool of Receivers

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#376]
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/587

**Comment by SeanFeldman** [comment]
Factories usage has to be substantially reviewed considering the following:

- Senders vs receivers
- Number of message pumps know and possible
- Relationship between `MessagingFactory` and `MessageSender`/`Receiver`
- Reuse of factories/clients

At this point we know that [documentation](https://azure.microsoft.com/en-us/documentation/articles/service-bus-performance-improvements/#reusing-factories-and-clients) not only helping, but also does the opposite.

**Comment by danielmarbach** [comment]
Sound like something we could address with 8.0 or Future. Is it important enough to be part of 8.0 or should we backlog it?

**Comment by SeanFeldman** [comment]
Probably not 8.0 since 8.0 will potentially focus on
- Completion of sealing of APIs that got obsoleted in 7.1.0
- Addressing internal container and ReadOnlySetting

which on its own is enough of work.

**Comment by danielmarbach** [comment]
Not addressing this. We'll take this into consideration when we build the new client.
