### ISSUE TITLE
Improve 'A message lock lost exception' exception

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#383]
When leases aren't long enough the following message can be written in the log

> 2016-10-18 09:29:54.9964|WARN|87|NServiceBus.Transport.AzureServiceBus.MessageReceiverExtensions|A message lock lost exception occured while trying to complete a batch of messages, you may consider to increase the lock duration or reduce the batch size, the exception was The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

This is not really useful. It would be nice if this would contain:
- Message ID
- Fetched UTC timestamp
- Lease expiration timestamp
- Lease expiration duration

I also think that this should be logged with log level ERROR as this results in more-than-once processing.

Minor thing, there is a typo: occured => occurred 
## Who's affected
- Everyone
## Symptoms
- Message lock lost exceptions

**Comment by yvesgoeleven** [comment]
@ramonsmits problem is this exception is thrown by ASB, we don't control it. all we do is send a list of guids to asb, the rest happens in the service somewhere. We can ask the asb team to include this info, but that's it

**Comment by ramonsmits** [comment]
@yvesgoeleven So you get this if 1 of the leases in the batch completion is expired? Do we still have the BrokerMessages somewhere as then we can filter that probably based on that lease token and mention the `LockedUntilUtc` value from that object.

**Comment by yvesgoeleven** [comment]
@ramonsmits indeed, but the brokered message is not around at that point anymore, all that is left is that lock token

**Comment by SeanFeldman** [comment]
I'll tackle this question from a different perspective - a batch of 100 messages has failed. What will MessageID, Fetched UTC timestamp, Lease expiration timestamp, and Lease expiration duration help? They are all likely to have everything almost the same, except the message ID. Let's say we provide MessageID, will it help when you have a 100 of those? 

I've tried that approach when dispatch a batch of messages and operation fails. A wall of GUIDs gets logged and it's not really helpful.

Good discussion. We just need to look at it from a practical point of view.

**Comment by ramonsmits** [comment]
Knowing which messages will be processed again while the message is already processed can help in diagnosing issues later on.

I don't know why all of them would have the same data. What is just one message took a long time to process because it did some kind of external

Only seeing the ID doesn't help and that is why I mention that it would be helpful to see the meta data. Knowing if just for example 1 message expired or maybe all of them.

I wanted to see this info when I got this exception because I didn't know why I got it. I could help me tweak the required lease duration to a value that is more appropriate without being overly conservative.

**Comment by SeanFeldman** [comment]
@ramonsmits besides the fact that data is not around at the point when we attempt to complete, I really can't see how would this info would help when there are dozens of messages that failed to complete. In a system where you have a constant stream of messages. Let's get on a call to review/discuss this?

**Comment by yvesgoeleven** [comment]
@SeanFeldman @ramonsmits is there an action point here?

**Comment by SeanFeldman** [comment]
@yvesgoeleven we didn't have a chance to connect to discuss this. Feels like a nice-to-have.

**Comment by ramonsmits** [comment]
@yvesgoeleven @SeanFeldman I also has another idea. Due to the prefetchingm the lease lock is potentially acquired much earlier than the processing starts. What about checking this value just before processing starts? For example, lease duration is 30 seconds, due to prefetching the lock is already acquired 20 seconds before processing starts meaning only 10 seconds left to complete and ack the lease.

This could be put in a performance counter so that this can even be graphed.

**Comment by SeanFeldman** [comment]
@ramonsmits from a performance point of view, the investment is more of the overhead than benefit. It's simpler to retry the messages and lock tockens are enough to correlate back to the messages _if_ such action is required.

I'm going to close this for now.

PS: spelling will be fixed via #401

**Comment by ramonsmits** [comment]
Don't understand that performance remark @SeanFeldman . This is to inform customers that if a lease is expired to warn that the same message will be processed again.

**Comment by SeanFeldman** [comment]
@ramonsmits my bad, I was thinking of batched completion.
