### ISSUE TITLE
Duplicate Subscriptions from same Logical Subscriber

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.AzureServiceBus#39]
We are getting a weird problem where it appears multiple Topic subscriptions are being created.

![example_subscriber_multiples](https://cloud.githubusercontent.com/assets/2546913/7973851/39ec4bd4-0a0f-11e5-9e2a-dd9ffb185e88.PNG)

In this example there is currently only 1 logical subscriber for this message (CustomerCreated), and that is the same logical publisher.

This is not behavior we saw previously with older versions of NServiceBus (we relatively recently updated). As you can see some of the "subscribers" are not processing messages, but every once in a while the host will connect to the duplicate subscription and begin processing them. The "plain" subscription (without a trailing number) works as usual. We are not sure how to trouble shoot this.

We use Azure scaling extensively, and the number of subscriptions matches up to the upper bound of instances this WorkerRole will spin up under load.

Here is the NServiceBus versions we are running:

```XML
  <package id="NServiceBus" version="5.2.0" targetFramework="net451" />
  <package id="NServiceBus.Azure" version="6.2.1" targetFramework="net451" />
  <package id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="6.2.0" targetFramework="net451" />
  <package id="NServiceBus.CommonLogging" version="2.1.0" targetFramework="net451" />
  <package id="NServiceBus.Hosting.Azure" version="6.2.1" targetFramework="net451" />
  <package id="NServiceBus.RavenDB" version="2.1.0" targetFramework="net451" />
  <package id="NServiceBus.StructureMap" version="5.0.1" targetFramework="net451" />
```

**Comment by SeanFeldman** [comment]
@thetinomen, are you using ScaleOut in your endpoint config?
http://docs.particular.net/nservicebus/scalability-and-ha/individualizing-queues-when-scaling-out#uniquequeueperendpointinstance1934519126

Can you share your endpoint configuration code?

**Comment by thetinomen** [comment]
We are not _intentionally_ using ScaleOut. Unless it is enabled by default.

Here is a Gist with the Endpoint Config Files:
https://gist.github.com/thetinomen/31204a5762241607db12

**Comment by yvesgoeleven** [comment]
The scaleout defaults differ per host, which host(s) are you using?

PS: Judging from the AsA_Worker profile, I assume you are hosting in cloudservices when in azure? But are you using a different host when hosting on your machine?

PPS: I notice you are using raven as  persistence, raven stores data on disk. Cloudservices disks will eventually disappear, they are not durable, so if you don't want to loose your data I recommend using a different persistence

**Comment by thetinomen** [comment]
We host worker roles using the NServiceBus.Hosting.Azure host package. Debugging locally is done via the emulator. We never use the default host process and only use self hosted in our LINQPad scripts, which do not implement subscribers. 

When running in Azure our RavenDb connection strings point to a cloud hosted RanenHQ database.

**Comment by yvesgoeleven** [comment]
I suggest you explicitly configure the scaleout settings to be certain 

configuration.ScaleOut().UseSingleBrokerQueue();

**Comment by thetinomen** [comment]
Another clue. This particular host is currently the only one where we are running Sagas.

**Comment by SeanFeldman** [comment]
@thetinomen any chance you could share a repro for this?

**Comment by SeanFeldman** [comment]
@thetinomen did you try what @yvesgoeleven suggested?

**Comment by thetinomen** [comment]
I did, it doesn't _appear_ to have fixed it. I am trying to confirm.

My apologies, I have been working on the requested repro, work has just been crazy so it has been slower than desirable.

**Comment by thetinomen** [comment]
Ok, I was implementing `configuration.ScaleOut().UseSingleBrokerQueue();` incorrectly (I thought our endpoint config was picking it up).

We have now resolved it by adding a INeedInitialization class with this configuration set. However it is enabled by default with Sagas, is that the desired behavior?

Could this be related to mixing Asa_Worker with the NServiceBus.Hosting.Azure package? Is there a different profile we should be using?

**Comment by boblangley** [comment]
Alright, I have created [a repro](https://github.com/BobAtParticular/NSB.ASB.Issue39), and it even does this behavior in the Azure Emulator. 

What is strange is it even does it for the handler only endpoint. Since the NSB references are a little out of date I will next update everything to latest and see if the problem persists.

**Comment by SeanFeldman** [comment]
Fixed in the new topology (`ForwardingTopology`).
I'll close the issue. Please re-open if needed.
