### ISSUE TITLE
First topic in events bundle is never used

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#391]
## Who's affected

- Anyone using `ForwardingTopology` and working with events on Azure Service Bus 

## Symptoms

With the `ForwardingTopology` when events are sent, they are randomly distributed between bundled topics for better performance. By default, there are 2 topics in a bundle, but only one is utilized. 

## Details

Bundles are used for performance. This bug does not require an immediate upgrade.

**Comment by danielmarbach** [comment]
How about we fix it in 7.1 then?

**Comment by SeanFeldman** [comment]
This required the discussion on #388 to reach a conclusion first.
Agreement is that we're going to deploy this bug fix, #392, and #388 in 7.1.0
