### ISSUE TITLE
Is MessageFactorySettingsFactory customization a feasible overload?

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#395]
While investigating for #389 I worked on MessagingFactoryCreator. The creator uses the namespaceManagers in two locations. One during the creation and one time during the messaging factory settings creation to assign the token provider. This made me question whether the 

`Func<string, MessagingFactorySettings>>(WellKnownConfigurationKeys.Connectivity.MessagingFactories.MessagingFactorySettingsFactory
`

is essentially a feasible overload. Is it enough to pass in the namespace only so that users could create their settings? Wouldn't it make sense to pass in the namespace and the namespace managers? Or wouldn't it be even better that we pass in the preconfigured messaging factory settings and users return us the settings again with their modifications?

**Comment by danielmarbach** [comment]
Talked to @yvesgoeleven and he explained to me that we only access the namespace manager to access the token provider in order to not create a new one again. Users can very well implement that function without ever needing to access the namespace manager.

**Comment by yvesgoeleven** [comment]
Just to add: The token provider class offers a bunch of static methods to create a new one: https://msdn.microsoft.com/en-us/library/microsoft.servicebus.tokenprovider_methods.aspx

**Comment by yvesgoeleven** [comment]
We also have documentation on the topic: https://docs.particular.net/nservicebus/azure-service-bus/token-provider
