### ISSUE TITLE
Individualization can cause subscription names to exceed 50 character limit

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#40]
## Who's affected

Anyone who's using ASB and running outside of cloud services where combination of subscription and machine names can exceed 50 characters limit.

## Symptoms

We check character limit before individualization

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Topology/QueueAndTopicByEndpoint/NamingConventions.cs#L94

that should have been after

_Note_: there might [one more problem](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/40#issuecomment-112531497) associated with this

**Comment by SeanFeldman** [comment]
Before core 5.2.x transport was applying individualization, so the logic to create subscription name was the following:
1. check subscription name (S) for a max length (50). 
2. If max length is exceeded, we turn S into a deterministic GUID (32 characters w/o dashes) 
3. Individualize by appending "-X" where X is either instance number (cloud) or machine name (not-cloud)

This is where the _reported issue_ could be monitored if S + "-X" > 50 characters

After core 5.2.x endpoint can be already individualized by core and S will contain endpoint name and "-X"  when the check for max length is done, turning into GUID combination of S + "-X".

**Comment by SeanFeldman** [comment]
@yvesgoeleven where was it brought up (google user group / question)?

**Comment by yvesgoeleven** [comment]
twitter
