### ISSUE TITLE
Single message completion should log ASB related exception details

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#402]
`MessageRecieveNotifier` is completing a message in `HandleCompletion()` method and is using `BrokeredMessage.CompleteAsync()` rather than going through `BrokeredMessageExtensions.SafeCompleteAsync()` extension method to log exception details when needed.

**Comment by danielmarbach** [comment]
Implemented as part of #434 Closing
