### ISSUE TITLE
Creating custom partitioning strategies

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#404]
#@internal: changes associated with internalization of types done in #388 

As part of ASB tranport API, we allow custom partitioning strategies to be [registered](https://docs.particular.net/nservicebus/azure-service-bus/configuration/full#physical-addressing-logic-namespace-partitioning).
To be able to access the namespaces registered with the transport, internally `NamespaceConfigurations` type is used, which is also exposed in a [sample we provide](https://docs.particular.net/samples/azure/custom-partitioning-asb/#subscriber-creating-a-custom-partitioning-strategy) how to create custom partitioning strategies. 

Should we revert internalization of `NamespaceConfigurations` and make it publicly available again or
review `namespacePartitioning.UseStrategy<T>()` API? The API doesn't allow registration of an object that could be initialized with the needed information about namespaces.

@Particular/azure-service-bus-maintainers @danielmarbach this is blocking release 7.1.0

**Update**:

Decision is to not obsolete this with a warning message. Release 8.0.0 will have a different way of registering partitioning strategy and API for building custom partitioning strategies. At that point we'll obsolete the involved types with errors and appropriate guidance.

**Comment by boblangley** [comment]
Perhaps we should just handle the conversion for the user and provide them only RuntimeNamespaceInfo via an extension method in ReadOnlySettings? Here is a PR #405

**Comment by SeanFeldman** [comment]
@yvesgoeleven I agree we should revert internalization of `NamespaceConfigurations` for now and leave it as-is for v7.x 

@danielmarbach attempted a different approach in PR #407 , which is probably a good way for vNext, but not the current solution.

**Comment by danielmarbach** [comment]
#437 was merged. Closing
