### ISSUE TITLE
FailOverNamespacePartitioning won't fail over

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#406]
## Who's affected

Anyone using `FailOverNamespacePartitioning`

## Symptoms

Fail-over namespace is not used, causing endpoint to raise critical error.

## Original issue

`FailOverNamespacePartitioning` strategy is supposed to provide passive namespace for the fallback namespaces when `DefaultOutgoingBatchRouter` is failing to route messages to the active namespace. Due to how destination namespaces are constructed, topology section managers return only active namespaces for sending intent. 

~~A few question that arise:~~
1. ~~Is `FailOverNamespacePartitioning` a truly one of the partitioning strategy or should it be a feature?~~ 
1. ~~Should the sample strategy in #404 become a built in "data distribution" strategy, where out of the box we allow explicit partitioning strategy selection from a pre-defined "list", with `INamespacePartitioningStrategy` becoming sealed off until we have a better idea of how to deal with it?~~

@Particular/azure-service-bus-maintainers please chime in

**Update**: flipping over to a passive namespace to become a primary is not required for this strategy to work. This would make it more efficient if we could know which namespace was failing. We'll consider this improvement in the future version as it requires API changes (feature #420 raised).

**Comment by danielmarbach** [comment]
I stumbled over this right now. The failover mode of the strategy is never set so it will always return primary no matter whether the primary is available or not. So the sample 

https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#fail-over-namespace-partitioning

with the statement

> The transport uses the primary namespace by default, and switches to secondary one when the primary is not available.

Is not correct.

**Comment by yvesgoeleven** [comment]
sounds like 2 bugs in one
 * partitioning strategy should return a set of 1 active and 1 passive in this case
 * partitioning strategy shoud flip the active and passive if it can't use active for a while

**Comment by SeanFeldman** [comment]
Maintainers call is scheduled.

**Comment by SeanFeldman** [comment]
Scheduled to be fixed in 7.0.3

**Comment by SeanFeldman** [comment]
## Call summary

1. Section managers (`ForwardingTopologySectionManager ` and `EndpointOrientedTopologySectionManager`) should not [filter out namespace](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/b1767af2fd30093383519e894f18910b01a84151/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs#L160) based on Mode when sending to partitioned namespaces.
1. [`FailOverNamespacePartitioning`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/b1767af2fd30093383519e894f18910b01a84151/src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs#L39) incorrectly returns a single namespace when `Sending` partitioning intent is used.
1. `FailOverNamespacePartitioning` Mode is not updated to reflect a failure to receive messages from ASB client. As a result of that `FailOverNamespacePartitioning` doesn't switch to the secondary/passive namespace. This would require a new interface to communicate with partitioning strategies. Discussion in issue #414
1. Circuit breaker is [armed after a 1 failure](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/b1767af2fd30093383519e894f18910b01a84151/src/Transport/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs#L38) only. Separate [bug issue](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/413) raised.

Documentation changes/clarification that are needed

1. Built in strategies other than `FailOverNamespacePartitioning` **do not** support fail over namespace. Needs to be clarified in [Multiple Namespaces Support](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support) doco. If failover is needed in addition to HA, a custom strategy needs to be created.
1. Document creation of a strategy that supports both HA and failover in a sample.
1. Existing sample for [Custom Partitioning Strategy](https://docs.particular.net/samples/azure/custom-partitioning-asb/) should be explained/renamed as "Data Distribution" stategy.
1. Existing sample for [Custom Partitioning Strategy](https://docs.particular.net/samples/azure/custom-partitioning-asb/) is not linked to the documentation [Multiple Namespaces support](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support).
1. [Multiple Namespaces support](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support) should point to the section on "Implementing a custom namespace partitioning strategy" in [Addressing Logic](https://docs.particular.net/nservicebus/azure-service-bus/addressing-logic#namespace-partitioning-implementing-a-custom-namespace-partitioning-strategy) doco.

@Particular/azure-service-bus-maintainers anything I've missed?
