### ISSUE TITLE
Dequeuing temporary locked

### ISSUE THREAD

**Issue by imperugo** [Particular/NServiceBus.AzureServiceBus#41]
Hi, 
I've a strange behaviour with my Bus and Azure ServiceBus.
Basically I'm sending 10000 messages into the queue from a ```ISendOnlyBus``` instance and, from another process, I dequeue message with ``IBus```.
After the first tentative I noticed that my messages was moved into "Dead Letter Queue" so, following this [link](http://apptiviz.com/blog/2015/february/28/nservicebus-messages-and-azure-service-bus-dead-letter-queue.aspx) I changed my configuration with this values:

```csharp
new AzureServiceBusQueueConfig()
{
	ConnectionString = this.configuration.Bus.TransportConnectionString,
	MaxDeliveryCount = 1500, 
	LockDuration = (int)(new TimeSpan(0, 5, 0).TotalMilliseconds)
}
```

I'm not sure about that values but now the messages still into the distribution queue.
The problem now is the dispatcher, after some message (variable from 100 to 150/200) it stops dequeuing.
The only way to retrieve the new messages is to stop and start it again.

The log says nothing, 

```log
2015-06-07 06:29:17.591 +00:00 [Information] Queue 'Particular.ServiceControl' already exists, skipping creation
2015-06-07 06:29:27.589 +00:00 [Information] Checking existence cache for 'Particular.ServiceControl'
2015-06-07 06:29:27.592 +00:00 [Information] Determined that the queue 'Particular.ServiceControl' exists
2015-06-07 06:29:27.594 +00:00 [Information] Queue 'Particular.ServiceControl' already exists, skipping creation
```

The error queue is empty, same for the Dead Letter Queue so I assume that the messages are still valid.
Any hint about this strange behaviour?

**Comment by yvesgoeleven** [comment]
I guess your endpoint is now working hard on... waiting (for locks to be released)

I would lower batch size to 1, and return MaxDeliveryCount & LockDuration to normal values... if that keeps running, then slowly up the batch size.

**Comment by imperugo** [comment]
I noticed that the default value for the batch is 1000, does it mean that the instance download 1000 messages for each round trip?

**Comment by yvesgoeleven** [comment]
yes, which is too high if you have a lot of IO going on, we are aware of that

**Comment by imperugo** [comment]
Ok and there is a way to have different values related to a specific set of commands?
For example the IHandleMessage<MyCommand> got 1000 message for a single roundtrip and the implementation of IHandleMessage<MyCommand2> only 10?

**Comment by yvesgoeleven** [comment]
no, it's a transport level setting.

**Comment by imperugo** [comment]
I changed the configuration as you suggested me but now, something I've that message

>A message lock lost exception occured while trying to complete a message, you may consider to increase the lock duration or reduce the batch size, the exception was The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue

Any hint?

**Comment by yvesgoeleven** [comment]
That means that processing a single message takes longer than 30 seconds (assuming your batch size is 1 now, and lock duration is the default 30 seconds)

**Comment by imperugo** [comment]
ok, something like this

```csharp
new AzureServiceBusQueueConfig()
{
	ConnectionString = this.configuration.Bus.TransportConnectionString,
	BatchSize = 1, //TODO:default value 1000, need to tune it
	LockDuration = (int)(new TimeSpan(0, 2, 0).TotalMilliseconds)
}
```
should fix that right?

**Comment by yvesgoeleven** [comment]
That would make the lock duration 2 minutes and should give your operation more time. Do note that lock duration is embedded in the queue definition, so you may need to recreate your queue before it actually applies.

**Comment by imperugo** [comment]
Ok and what do you suggest in case of long running message operation?
Saga?

**Comment by yvesgoeleven** [comment]
Yes, but multiple implemenations exist within the concept of a saga as well

- split into small pieces of work and coordinate using a saga
- if you have a long operation (downloading a video f.e.), the spin off a background thread and use saga timeouts to check progress

**Comment by yvesgoeleven** [comment]
I assume we can close this issue now, feel free to reopen if needed
