### ISSUE TITLE
Topic existence is not verified with an associated namespace

### ISSUE THREAD

**Issue by HaripraghashSubramaniam** [Particular/NServiceBus.AzureServiceBus#411]
## Who's affected

Everyone that uses a multiple namespace partitioning strategy

## Symptoms

Topics are not created in secondary namespaces if they already exist in the primary

## Details

We are trying to use Multiple namespaces using round robin strategy. When we provide 2 namespaces with primary namespace having all the input queues, topics etc created and a blank and a new secondary namespace,

In `AzureServiceBusQueueCreator`, It first checks for the queues and if queues are existing in the primary namespace then it doesnt create them. Then it checks for queues in secondary namespace. If it doesnt exist then it creates them. This works because in `ExistsAsync` forms the key as a combination of queue path and namespace

In `AzureServiceBusTopicCreator`, it jsut checks for the topicname in primary namespace. If it exists, then it adds it to the `rememberExistence` without adding the namespace. If the secondary namespace doesnt have the topic with the same name, then it still considers and assumes that the secondary topic has the topic(even though it doesnt exist)  as `ExistsAsync`  **doesnt** form the key as a combination of topic path and namespace.

**Comment by yvesgoeleven** [comment]
@jabrouni1 thanks for reporting, we'll make sure this gets fixed
