### ISSUE TITLE
RepeatedFailuresOverTimeCircuitBreaker is armed after a single error

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#413]
## Who's Affected

Anyone using Azure Service Bus transport

## Symptoms

When ASB client fails to receive a message, transport will invoke `RepeatedFailuresOverTimeCircuitBreaker`. Circuit breaker should have a few failures prior to arming and raising a critical error after 30 seconds. Instead, a single error will arm the trigger. 

In scenarios where message flow is low, a single unsuccessfully received by ASB client message would cause circuit breaker to arm and fire, causing endpoint to shut down.

Connected to #414

**Comment by SeanFeldman** [comment]
Given the CB originated from the core, I've opened up an [issue](https://github.com/Particular/NServiceBus/issues/4275) with core to clarify the intent of the original class.

**Comment by SeanFeldman** [comment]
For core it's working as designed. For ASB, behaviour might require a change to take into consideration possible failover.

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers should we increase number of failures, or should we clarify the name? Right now, with a single failure, we have a solid behavior.

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers ping

**Comment by yvesgoeleven** [comment]
@SeanFeldman let's just leave it as is, the name is a bit confusing but as the behavior has been like this since the beginning, I would not change it now

**Comment by SeanFeldman** [comment]
Sounds good.
@danielmarbach said the same about Core version, name is confusing.
Closing. Reopen if needed.
