### ISSUE TITLE
Unnecessary check when creating queues

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#424]
Core only invokes `ICreateQueues` when queue creation is allowed
- Running with a debugger attached
- `endpointConfig.EnableInstallers()` 

Anything else will not trigger queue creation calls, make [this check](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Creation/AzureServiceBusQueueCreator.cs#L53) obsolete.

**Comment by danielmarbach** [comment]
PR #438 was merged. Closing this.
