### ISSUE TITLE
Release a deprecation package for NServiceBus.Azure

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus.AzureServiceBus#426]
As NServiceBus.Azure will be split in the next major (into persistence & databus) and will cease to exist, we should notify users about this when they try to upgrade.

- [ ] Create an empty V7 package, add [deprecated] to the title & update the description to point to the 2 new packages. We did this in the past for NServiceBus.Interfaces see https://github.com/Particular/NServiceBus/blob/support-5.0/packaging/NServiceBus.Interfaces.5.0.0.nupkg
- [ ] On upgrade, open an webpage (using ps) that points to https://docs.particular.net/nservicebus/upgrades/azure-deprecation

**Comment by SeanFeldman** [comment]
👍

**Comment by boblangley** [comment]
https://github.com/Particular/NServiceBus.Azure/pull/293 closes this issue, not https://github.com/Particular/NServiceBus.Azure/pull/290 which was abandoned.
