### ISSUE TITLE
Remove the check if topology needs to be created for Subscriptions

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#428]
Addresses #425 

The check is unnecessary and can be removed.

**Comment by danielmarbach** [comment]
Done as part of #438 Closing

@SeanFeldman can you double check and reopen if necessary

**Comment by SeanFeldman** [comment]
Confirmed. We also removed the default value added by the transport to the "create queues" setting from the core. Now there's no questions about what the default is.
