### ISSUE TITLE
Circuit breaker never invoked when messages are failing to be received

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#429]
## Who's affected 

- Anyone using Azure Service Bus transport version 7 and up

## Symptoms

Circuit breaker is not triggered when messages are failing to be received.

## Details

[MessageReceiveNotifier](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Receiving/MessageReceiverNotifier.cs#L108) should invoke error callback when OnMessage API is failing to receive a message, which in turn should arm circuit breaker. `OnError` callback passed into `MessageReceiveNotifier` from `TopologyOperator`, but itself is [*never* assigned](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Topology/TopologyOperator.cs#L78). The original intent was to [assign `TopologyOperator` an error callback](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Seam/MessagePump.cs#L91) that would trigger a circuit breaker arming in `MessagePump`, but the code is never exercised in `MessagePump.Init()`.

**Comment by SeanFeldman** [comment]
@Particular/azure-maintainers this might need to be treated as critical

**Comment by danielmarbach** [comment]
Small update: The code is implemented and available on the hotfix 7.0.4 branch. We are in the process of reviewing it. As part of the 7.0.4 releae we will also be releasing a fix for a shutdown race scenario #434
