### ISSUE TITLE
Add the ability to configure Support Ordering for queue and topic creation.

### ISSUE THREAD

**Issue by JonathanStarnes** [Particular/NServiceBus.AzureServiceBus#43]
Would allow for turning off Ordering when it is not needed.

**Comment by SeanFeldman** [comment]
@JonathanStarnes this would not entirely work since with `PeekLock` messages can get processed out of original order when lock expires. What I'm trying to say is that we shouldn't assume message order.

**Comment by SeanFeldman** [comment]
Good post on this: http://www.ben-morris.com/dont-assume-message-ordering-in-azure-service-bus/

**Comment by JonathanStarnes** [comment]
@SeanFeldman So when creating the queues should the SupportOrdering configuration be set to false by default? Currently when queues are being created the SupportOrdering configuration is set to true which is causing delivery failures when there are a large number of workers. This seems to go away when I manually change the Support Ordering configuration to false.

**Comment by JonathanStarnes** [comment]
@SeanFeldman Totally agree with the article. I am just trying to set the configuration to false when creating queues and topics with NSB using Azure Service Transport. This should be quite a simple change. 

```
   var description = new QueueDescription(queueName)
            {
                LockDuration = LockDuration,
                MaxSizeInMegabytes = MaxSizeInMegabytes,
                RequiresDuplicateDetection = RequiresDuplicateDetection,
                RequiresSession = RequiresSession,
                DefaultMessageTimeToLive = DefaultMessageTimeToLive,
                EnableDeadLetteringOnMessageExpiration = EnableDeadLetteringOnMessageExpiration,
                DuplicateDetectionHistoryTimeWindow = DuplicateDetectionHistoryTimeWindow,
                MaxDeliveryCount = MaxDeliveryCount,
                EnableBatchedOperations = EnableBatchedOperations,
                EnablePartitioning = EnablePartitioning,
                SupportOrdering =  SupportOrdering
            };
```

**Comment by JonathanStarnes** [comment]
@SeanFeldman Maybe instead of allowing for configuration just add a default to false?

**Comment by SeanFeldman** [comment]
@JonathanStarnes I see now. Azure SB API default is set to true and [MSDN documentation](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.queuedescription.supportordering.aspx) doesn't state that. 

We'll add it in the next version. Thank you for bringing this up :)

**Comment by JonathanStarnes** [comment]
@No Problem. If you want I need this anyway I can send a pull request.

**Comment by SeanFeldman** [comment]
PR works, thanks

**Comment by SeanFeldman** [comment]
Note: for existing queues and topics `SupportOrdering` cannot be changed. Either queues/topics are deleted and new setting will apply or a 3rd party tool (ServiceBus Explorer or similar) is used to modify the setting manually.

**Comment by SimonCropp** [comment]
@SeanFeldman can u add a link to the updated doco

**Comment by SeanFeldman** [comment]
http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#configuring-in-detail
Good catch @SimonCropp :) thanks
