### ISSUE TITLE
IEndpointInstance.Stop can cause hosting process shutdown

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.AzureServiceBus#433]
## Who's affected

- Anyone running with Azure Service Bus transport and requires start and stop of the endpoint independent of the host process.

## Symptoms

`IEndpointInstance.Stop()`  can cause the host to shut down.

## Context

Due to race-condition between message processing logic and endpoint shutdown logic, hosting process can be killed when `IEndpointInstance.Stop()` is called. 

The issue is caused by the fact that message processing logic relies on the resources which are cleaned when stopping `MessagePump` and stopping does not wait until processing finishes for all in-flight messages and will timeout after 30s.

### Root cause analysis
Here are some important facts about current code base:
 1. The [lambda](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Seam/MessagePump.cs#L95) that is passed to `TopologyOperator.OnError` pulls `this` into closure and executes `this.circuitBreaker` on each invocation
2. Fody weaves in `Dispose` method for  `MessagePump` that nullifies the `this.circuitBreaker` reference when exectued.
3. `MessageReceiveNotifier` and as a result `MessagePump.Stop()` method [wait for up to 30 sec](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Receiving/MessageReceiverNotifier.cs#L106) for any in-flight messages before finishing
4. `Dispose` is called on `MessagePump` by core executing `IBuilder.Dispose` during `IEndpointInstance.Stop`

Here is a sample execution that shows the problem:
1. Message is received by Azure SDK
2. `MessageReceiveNotifer.ProcessMessagesAsync` is called and throws
3. The exception is caught by the SDK
4. `MessageRecieveNotifier.OptionsOnExceptionReceived` is called and continues execution until it reaches `TopologyOperator.OnError` lambda but before accessing `circuitBreaker` reference
5. `MessagePump.Stop` is called it and waits 30s until shutdown timeout, the `MessagePump.Dispose` is called and `circuitBreaker` reference is set to `null`
6. Processing stopped in point `4` continues and throws `NullReferenceException`

In general when we have set timeout for waiting on in-flight messages we cannot get rid of this race-condition.

In practice there is additional bug that makes this problem appear way more frequent. The problem is caused by the fact that we [remove in-flight task before the error handling callback is called](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Receiving/MessageReceiverNotifier.cs#L167) by SDK.

```
            var processTask = ProcessMessage(internalReceiver, message, slotNumber);
            pipelineInvocations.TryAdd(processTask, processTask);
            processTask.ContinueWith((t, state) =>
            {
                var invocations = (ConcurrentDictionary<Task, Task>) state;
                Task toBeRemoved;
                invocations.TryRemove(t, out toBeRemoved);
            }, pipelineInvocations, TaskContinuationOptions.ExecuteSynchronously);
            return processTask;
```

So what happens here is that we remove the task from `invocations` before the exception can be observed by Azure SDK and so we do not wait in `Stop` for error callback for in-flight failed messages.

**Comment by tmasternak** [comment]
@Scooletz can you please verify the the summary of our findings is correct?

**Comment by Scooletz** [comment]
It is very correct @tmasternak .

The latest finding that the `OnMessageOptions.ExceptionReceived` is called as a continuation to the task seems to be true as well. The callback we initiate, is passed to the internal `Microsoft.ServiceBus.Messaging.MessageReceivePump` that uses it to initiate `Microsoft.ServiceBus.Common.TaskAsyncResult` which runs completing as a continuation if a task didn't return yet

```
  public TaskAsyncResult(Task task, AsyncCallback callback, object state)
      : base(callback, state)
    {
      this.task = task;
      if (this.task.IsCompleted)
        this.CompleteWithTaskResult(true);
      else
        this.task.ContinueWith(new Action<Task>(this.OnTaskContinued));
    }
```
This means that the `processTask` we return has two continuations: 
- the first that removes the entry from `invocations`, 
- the second, that will run the `callback`. 

If there was an exception, the removal task can remove the entry when still exception is being handled on the separate continuation showing that there's no more tasks and enabling stopping the endpoint. Again, this happens when the error is being handled.

---
Below, there's a solution part, which is just a sketch, and lets me save my reasoning flow.
If we captured the exception in the callback, wrapped it with our own and passed a primitive that is responsible for removing the task from `invocations` we could:
- `processTask.ContinueWith` only for successful runs
- remove the task from invocations in the error handler

That would ensure proper synchronization point (casual ordering) or handling the error AND THEN removing the task from incoming.

**Comment by Scooletz** [comment]
Ping @Particular/azure-maintainers

**Comment by bording** [comment]
I've read through this a few times, and I'm still not seeing how this explains the stack trace in #432. By the time the [ScenarioRunner](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs#L31) has set the Context to null to cause the NRE in `ContextAppender.Log` that is seen in the #432 stack trace, how is there still code executing in `OptionsOnExceptionReceived`?

The first thing that happens in [MessageReceiverNotifier.Stop](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Receiving/MessageReceiverNotifier.cs#L100) is registering `OptionsOnExceptionReceived`, so how can that be newly entered after that point?

Or are you trying to say that an invocation of `OptionsOnExceptionReceived` that was entered before Stop was called is slow enough that it can still be executing while finishing the Stop call and everything else core does when stopping an endpoint and then get to the offending line in the ScenarioRunner?

😕

**Comment by tmasternak** [comment]
> Or are you trying to say that an invocation of OptionsOnExceptionReceived that was entered before Stop was called is slow enough that it can still be executing while finishing the Stop call and everything else core does when stopping an endpoint and then get to the offending line in the ScenarioRunner?

I think this is the case. The scenario that I gave in the description - `OptionsOnExceptionReceived` not making progress for 30s,  is not very likely to happen but still possible. The more probable problem is the second thing mentioned (and described by in more details by @Scooletz) i.e. just after `OptionsOnExceptionReceiverd` goes past `stopping` check and `Stop` gets executed and does not wait because `invocations` collection is already empty. So the scenario goes like this:
1. Processing fails
2. Continuation with `pipelineInvocationTasks.TryRemove(t, out toBeRemoved);` gets executed
3. Continuation calling `OptionsOnExceptionReceived` gets executed and goes past `stopping` check
4. Context switches to `Stop` (no wait because of 2), after that `IBuilder.Dispose` and finally test run finishes settin logging context to [null](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs#L31)
5. Execution returns to 3 which tries to use `logger` that is already disposed.

**Comment by Scooletz** [comment]
@tmasternak I updated my proposal to make it simpler a little bit. Now the continuation is returned that either removes the entry or throws, leaving the removal to the `OptionsOnExceptionReceived`. I know it's a bit slower with removing the task from `invocations`. We can discuss both approaches through.

**Comment by danielmarbach** [comment]
@tmasternak @Scooletz let's sync on this. I've been doing a fair amount of analysis on this one already.

**Comment by SeanFeldman** [comment]
Adding required sections. Moving forward, let's make sure that all bugs have those.
