### ISSUE TITLE
Allow message de-duplication on message's payload level

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#443]
I've spiked this option for something else needed to do with with ASB and it seems like a great way to achieve message deduplication using message/payload properties in conjunction with the native deduplication feature. More details [here](https://weblogs.asp.net/sfeldman/bend-message-deduplication-on-azure-service-bus-to-your-will).

Update: the hash assigned to the outgoing message id would be of the payload + incoming message id.

**Comment by Scooletz** [comment]
> More details here.

Where? :P

**Comment by SeanFeldman** [comment]
My bad, markdown issue. Fixed. Alternative link [here](https://blogs.msdn.microsoft.com/servicebus/2016/12/08/deduplication-with-message-payload/)

**Comment by SeanFeldman** [comment]
Have discussed this a bit with @bording and this could potentially be viewed as an Outbox for ASB (issue #22).

**Comment by yvesgoeleven** [comment]
@SeanFeldman @bording the intention of #22 is to survive network outages, nothing else.

ps: that issue predates the core outbox feature, it was not intended to work the same way (a different name may be needed)

**Comment by SeanFeldman** [comment]
Closing this one as we probably won't get to it.
