### ISSUE TITLE
Align assembly names with namespaces for test projects

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.AzureServiceBus#444]
Currently for unit tests and acceptance tests assembly names and namespace names are not aligned

**Comment by SeanFeldman** [comment]
@tmasternak so is with transport tests

#### ATTs
Project name: `NServiceBus.AzureServiceBus.AcceptanceTests`
Assembly name: `NServiceBus.Azure.Transports.WindowsAzureServiceBus.AcceptanceTests`
Default namespace: `NServiceBus.Azure.Transports.WindowsAzureServiceBus.AcceptanceTests`

#### Unit tests
Project name: `NServiceBus.AzureServiceBus.Tests`
Assembly name: `NServiceBus.Azure.WindowsAzureServiceBus.Tests`
Default namespace: `NServiceBus.Azure.WindowsAzureServiceBus.Tests`

#### Transport tests
Project name: `NServiceBus.AzureServiceBus.TransportTests`
Assembly name: `TransportTests`
Default namespace: `TransportTests`

**Comment by SeanFeldman** [comment]
Can be done as part of the routine work/refactoring. Closing.
