### ISSUE TITLE
Namespace alias should not work by default

### ISSUE THREAD

**Issue by dvdstelt** [Particular/NServiceBus.AzureServiceBus#446]
### Issue

On the following configuration, the connectionstring is not in `ReplyTo` or `ReplyToAddress` according to [this page in doco](https://docs.particular.net/nservicebus/azure-service-bus/securing-connection-strings). The `UseNamespaceAliasesInsteadOfConnectionStrings` setting seems to be on by default?

```
var configuration = new EndpointConfiguration("Sales");

configuration.UsePersistence<InMemoryPersistence>();
configuration.SendFailedMessagesTo("error");
configuration.AuditProcessedMessagesTo("audit");

configuration.Conventions().DefiningCommandsAs(t => t.Namespace != null && t.Namespace.EndsWith("Messages.Commands"));
configuration.Conventions().DefiningEventsAs(t => t.Namespace != null && t.Namespace.EndsWith("Messages.Events"));
            
// Azure Service Bus specific
var transport = configuration.UseTransport<AzureServiceBusTransport>();
transport.UseForwardingTopology();
```

![image](https://cloud.githubusercontent.com/assets/1257410/20970980/18eb90c2-bc90-11e6-82bc-de661a1c2cd2.png)

**Comment by SeanFeldman** [comment]
@dvdstelt I cannot reproduce this. Have used one of the samples and `ReplyToAddress` is **not** secured by default. Could you please run the same [sample](https://docs.particular.net/samples/azure/azure-service-bus/) to see if you get the same results? Thanks.

![image](https://cloud.githubusercontent.com/assets/1309622/20999544/7c42d4c2-bcd2-11e6-8b1a-2170f5dec6ae.png)

**Comment by dvdstelt** [comment]
It's ServiceInsight that isn't showing the connectionstring, just the word "default". I don't think that's the proper way to do it, because if I get confused, others might as well ;-)

@SeanFeldman How did you manage to get the above screenshot? What tool did you use? I checked with ServiceBus Explorer and it's awful!

**Comment by SeanFeldman** [comment]
>What tool did you use?

SBE

>I checked with ServiceBus Explorer and it's awful!

It likes me 😃
