### ISSUE TITLE
Replace the internal container with newing up instances directly where needed

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#448]
@SeanFeldman and I made a spike to show that it is possible to replace the internal container inside the topology. The approach would be following

- The topology is the composition root of the infrastructure required to run it
- All singleton scoped objects are held as fields inside the topology
- On demand created objects with transient scope are created with `new `when needed and held by the instance that needs the transient objects
- All container resolve calls happening during runtime are replaced with constructor injection or explicit method injection (method accepting parameters which define what dependencies an instance needs).

**Comment by yvesgoeleven** [comment]
👍

**Comment by Scooletz** [comment]
Where's the spike @danielmarbach ? :)

**Comment by SeanFeldman** [comment]
Gone with the wind...​

**Comment by danielmarbach** [comment]
Last outstanding PR is available here https://github.com/Particular/NServiceBus.AzureServiceBus/pull/598
