### ISSUE TITLE
Handler Stopped Processing Messages

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.AzureServiceBus#45]
When processing an larger amount of mesages (7000+ in queue) the Command Handler stopped processing, where at some points one can find following warnings

```
2015/06/25 05:46:30.802 Warn Brokered message lock expired, this could be due to multiple reasons. One of the most common is a mismatch between the lock duration, batch size and processing speed of your handlers. This condition can also happen when there is clock skew between the client and the azure servicebus service. 
```

Otherwise just normal info logs appearing...
```
2015/06/25 06:20:29.004 Info Checking existence cache for 'Particular.ServiceControl' 
2015/06/25 06:20:29.004 Info Determined that the queue 'Particular.ServiceControl' exists 
2015/06/25 06:20:29.004 Info Queue 'Particular.ServiceControl' already exists, skipping creation 
2015/06/25 06:20:34.606 Info Checking existence cache for 'Particular.ServiceControl' 
2015/06/25 06:20:34.606 Info Determined that the queue 'Particular.ServiceControl' exists 
2015/06/25 06:20:34.606 Info Queue 'Particular.ServiceControl' already exists, skipping creation 
2015/06/25 06:20:36.133 Info Checking existence cache for 'Particular.ServiceControl' 
2015/06/25 06:20:36.133 Info Determined that the queue 'Particular.ServiceControl' exists 
2015/06/25 06:20:36.133 Info Queue 'Particular.ServiceControl' already exists, skipping creation 
2015/06/25 06:20:36.720 Info Checking existence cache for 'Particular.ServiceControl' 
2015/06/25 06:20:36.720 Info Determined that the queue 'Particular.ServiceControl' exists 
2015/06/25 06:20:36.720 Info Queue 'Particular.ServiceControl' already exists, skipping creation 
2015/06/25 06:20:39.365 Info Checking existence cache for 'Particular.ServiceControl' 
2015/06/25 06:20:39.365 Info Determined that the queue 'Particular.ServiceControl' exists 
2015/06/25 06:20:39.365 Info Queue 'Particular.ServiceControl' already exists, skipping creation 
2015/06/25 06:20:39.539 Info Checking existence cache for 'Particular.ServiceControl' 
2015/06/25 06:20:39.539 Info Determined that the queue 'Particular.ServiceControl' exists 
```

also on a side note, there are 900+ messages in dead-letter queue, and the ASB Max-Delivery-Count is set to 500.

After a "Restart" it picks up where it left off, and start processing commands as expected.

**Comment by yvesgoeleven** [comment]
Try reducing the batch size, it probably reads in more messages then it can send out, causing the locks to expire and eventually SB will move them to DLQ

**Comment by SeanFeldman** [comment]
@danielHalan we've updated doco to guide better on this. Have you seen it?  ([link](http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#scenarios-cpu-vs-io-bound-processing)) Do you find it helpful?

**Comment by danielHalan** [comment]
Yes, dialed down the BatchSize to 200 and it has not occurred again since..

**Comment by dasjestyr** [comment]
how do you change the batch size? I didn't see it on the doc

**Comment by boblangley** [comment]
@dasjestyr 

For version 7 of the transport: https://docs.particular.net/nservicebus/azure-service-bus/configuration/full#controlling-connectivity-message-receivers Use the `PrefetchCount` setting to adjust the batch size.

For version 6 of the transport: https://docs.particular.net/nservicebus/azure-service-bus/configuration/azureservicebusqueueconfig Use the `BatchCount` setting to adjust the batch size.

**Comment by dasjestyr** [comment]
@boblangley (using 6.x) there doesn't appear to be a `BatchCount` setting. There's a `BatchSize` setting but it doesn't seem to work; I'm still getting the exception stating that I'm attempting to send more than 100 messages in a single transaction. The description sounds like it only applies to pulling messages off the queue rather than placing them on the queue.

**Comment by SeanFeldman** [comment]
@dasjestyr `BatchSize` is intended  for receiving operations. You're
sending a batch of messages and ASB does not allow more than 100 messages
to be sent in a single operation. It's addressed in NSB.ASB v7 by splitting
the batches larger than 100 messages into chunks. In v6 you'll need to do
it yourself.

**Comment by dasjestyr** [comment]
Ive seen allusions to doing this myself, but I haven't seen how. Can you help me out with something a bit more concrete?

**Comment by SeanFeldman** [comment]
The code where you create and dispatch your messages, do not send more than
100 messages at a time. Without seeing your code, more than that be just a
guess 😃

**Comment by dasjestyr** [comment]
Well, I mean, I'm not lol. I "send" them to the bus one at a time, but it appears to not actually send until it has a bunch batched up or there's lull or something. In other words, if I send one and call it day, then it's fine, but if I continue to send them rapid fire, then it appears to wait for about a thousand to pool up before attempting to send it.

**Comment by SeanFeldman** [comment]
Could you share your code (or a repro)?
Feel free to send it to sean.feldman@particular.net

On Apr 13, 2017 20:13, "Jeremy Stafford" <notifications@github.com> wrote:

Well, I mean, I'm not lol. I "send" them to the bus one at a time, but it
appears to not actually send until it has a bunch batched up or there's
lull or something. In other words, if I send one and call it day, then it's
fine, but if I continue to send them rapid fire, then it appears to wait
for about a thousand to pool up before attempting to send it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Particular/NServiceBus.AzureServiceBus/issues/45#issuecomment-294060977>,
or mute the thread
