### ISSUE TITLE
Topology migration

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#458]
Could we provide a migration tool or code internally in the transport which bridges an endpoint-oriented topology over to a forwarding topology on the fly including guidance when the old topology can be removed?

Connects to https://github.com/Particular/NServiceBus.Azure/issues/310

**Comment by SeanFeldman** [comment]
This is something that has been briefly discussed in the past and the biggest concern was always the fact that taking offline a system to perform an complete upgrade is not an option. Worth discussing to see if we could bypass that w/o having to require system to go down, _if_ possible. If not, at least we'll be able to document the reasons.

**Comment by yvesgoeleven** [comment]
We can't do it automatically without causing downtime (main limitation is that it's impossible to both receive and forward from an entity at the same time), but we could document how to do it step by step without causing downtime.

**Comment by SeanFeldman** [comment]
Note: there will be basic automatic interoperabitlity between Azure Service Bus (ASB) Forwarding topology and Azure Service Bus .NET Standard (ASBS, ASB transport for .NET Core).
