### ISSUE TITLE
Polymorphic events from different publishers not handled properly with EndpointOrientedTopology

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#460]
## Who's affected

- Anyone using `EndpointOrientedTopology` and has endpoints that subscribe to polymorphic events published by different endpoints, applying workaround demonstrated in [Polymorphic events with Azure Service Bus Transport](https://docs.particular.net/samples/azure/polymorphic-events-asb/) sample.

## Symptoms

Each publisher should have a subscription for the subscriber, but only one such subscription is created under a single publisher. This could lead to published events disappear and never be handled. While `EndpointOrientedTopology` doesn't support polymorphic events out-of-the-box, with disabled `AutoSubscribe` feature and manual subscription to the base event it should work as expected.

## Details

Verification `When_multi_subscribing_to_a_polymorphic_event` should work for this scenario when `AutoSubscribe` feature is disabled for the `Subscriber` endpoint and registered publishers are using the base event type (`IMyEvent`) for `EndpointOrientedTopology`.

**Comment by yvesgoeleven** [comment]
Endpoint oriented topology has never supported polymorphic events ootb, we introduced forwarding topology specifically with this in mind. It's ok to fix this creation problem of course, but we should do a better effort to guide people to use forwarding topology instead (and maybe provide some documentation on how to transition from one to the other). See discussion in #458

**Comment by SeanFeldman** [comment]
The scenario here is a hierarchy of events (happened to be polymorphic events), 
`Base` <|-- `Derived1` <|-- `Derived2`

A single `subscriber` and two publishers, `publisher1` and `publisher2` where `publisher1` publishes `Derived1` and `publisher2` publishes `publisher2`.
Both should be received, but only one would be since only one subscription will exist due to this bug.

![image](https://cloud.githubusercontent.com/assets/1309622/21369348/c5aabf08-c6c3-11e6-9502-a347a664f59e.png)

With the fix, subscriptions are not "de-duplicated" and created as expected

![image](https://cloud.githubusercontent.com/assets/1309622/21369407/01622040-c6c4-11e6-90f1-6b02349b0501.png)
