### ISSUE TITLE
Review entities Path / Name / FullPath usage

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#467]
**Placeholder**. Full description will come later.

We've got inconsistent usage of entity `Path`, `Name` and full path. As a result of that there are leaking abstractions ([`MessageReceiveNotifier`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/160c369e9cedd9beab531ec47d8ada7da8985833/src/Transport/Receiving/MessageReceiverNotifier.cs#L39))
and potential issue, break the transport with [`HierarchyComposition`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/160c369e9cedd9beab531ec47d8ada7da8985833/src/Transport/Addressing/Composition/Strategies/HierarchyComposition.cs). Hierarchy composition when used with subscriptions, could break topology assumptions and cause it to fail to operate.

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/587

**Comment by danielmarbach** [comment]
Low impact change, we will not address this and consider a better design when we start working on the .NET Standard compliant client.
