### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by HaripraghashSubramaniam** [Particular/NServiceBus.AzureServiceBus#468]
I am using Nservicebus 6.1.1 with NSB ASB 7.1.0. I ran a bit of soak test and I can see the memory increasing over time. I tried to see how the heap looks like and i can see a lot of ASB objects not disposed.

Could this be a memory leak?

![nsb-asb-memory](https://cloud.githubusercontent.com/assets/1676625/21486816/02443e14-cbb3-11e6-8210-cdd7cf792442.jpg)

**Comment by SeanFeldman** [comment]
Could you please provide the code you used for the test? Thanks.

**Comment by HaripraghashSubramaniam** [comment]
``
Sure.

Its in here
https://www.dropbox.com/s/u3q9yjju2s76gg8/nsbasb7.zip?dl=0

ASB con string and licence files have been removed.

**Comment by SeanFeldman** [comment]
@HaripraghashSubramaniam could you let know if the [repro you've shared](https://www.dropbox.com/s/u3q9yjju2s76gg8/nsbasb7.zip?dl=0) caused a memory leak on your end? In case it did, how long have you had it running and what project was it (sender or receiver)?

Sender takes a really long time to send all those messages (transport v6 limitation), but still I did not see anything abnormal.

**Comment by HaripraghashSubramaniam** [comment]
I was not able to reproduce this again. This can be closed now i believe

**Comment by SeanFeldman** [comment]
If you get to reproduce it, please return the issue with a repro do that we can investigate further. Thank you.
