### ISSUE TITLE
Message which is to big for ASB doesn't fail in a cloudservive when sending to the bus

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.AzureServiceBus#474]
Hello,

When I receive a message which then is mapped to a specific command(Very huge) it doesn't fail when sending it to the bus if it's hosted inside a azure cloud service. When I execute the same handler and message inside a console app then it throws a NSB.MessageTooLargeException. I'm aware of the DataBus and this specific command must go over this, but the original messages aren't available to retry anymore.

Thanx in advance.

Joey Chömpff

id="Autofac" version="3.5.2" targetFramework="net452"
id="Microsoft.ApplicationInsights" version="2.1.0" targetFramework="net452" />
id="Microsoft.ApplicationInsights.Agent.Intercept" version="1.2.1" targetFramework="net452"
id="Microsoft.ApplicationInsights.DependencyCollector" version="2.1.0" targetFramework="net452"
id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.1.0" targetFramework="net452"
id="Microsoft.ApplicationInsights.TraceListener" version="2.1.0" targetFramework="net452"
id="Microsoft.ApplicationInsights.WindowsServer" version="2.1.0" targetFramework="net452"
id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.1.0" targetFramework="net452"
id="Microsoft.Data.Edm" version="5.7.0" targetFramework="net452"
id="Microsoft.Data.OData" version="5.7.0" targetFramework="net452"
id="Microsoft.Data.Services.Client" version="5.7.0" targetFramework="net452"
id="Microsoft.WindowsAzure.ConfigurationManager" version="2.0.3" targetFramework="net452"
id="Newtonsoft.Json" version="9.0.1" targetFramework="net452"
id="NServiceBus" version="5.2.16" targetFramework="net452"
id="NServiceBus.Autofac" version="5.0.0" targetFramework="net452"
id="NServiceBus.Azure" version="6.2.5" targetFramework="net452"
id="NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="6.4.0" targetFramework="net452"
id="NServiceBus.Hosting.Azure" version="6.2.5" targetFramework="net452"
id="ServiceControl.Plugin.Nsb5.Heartbeat" version="2.0.1" targetFramework="net452"
id="System.Spatial" version="5.7.0" targetFramework="net452"
id="WindowsAzure.ServiceBus" version="2.8.2" targetFramework="net452"
id="WindowsAzure.Storage" version="4.3.0" targetFramework="net452"

**Comment by SeanFeldman** [comment]
@JSCProjects a few clarifications 
1. Are you receiving a message or are you sending a message and it fails?
2. If it's a send operation, is it on a context of a handler or not?
3. Elaborate on

**Comment by JSCProjects** [comment]
Sean,
 
The process works as followed. I receive a event and that event is mapped to a command with specific edi content. For reliability and responsibility reasons this command is send to a specific edi handling endpoint via the bus. This endpoint handles security, connectivity with a legacy system. Normally this event contains daily information, but we didn’t know there was a hidden spec. The old IT team forgot to mention that the same events also contains monthly info. So when we where in production someone (other party) mentioned he never received any monthly edi messages. But when I looked into ServiceInsight I saw that my event was handled correctly but never created the command, which is part of the handle method of that event.

**Comment by SeanFeldman** [comment]
If I understood correctly the scenario is the following:
An endpoint (`Source`) is receiving a message (`incoming`). Processes it, which results in an outgoing message (`outgoing`). `incoming` message is marked as successfully processed, despite the fact that the `outgoing` message was way too large to be sent and actually failed sending operation (with `MessageTooLargeException` being logged). Is this accurate or I'm still off?

Also, when you tried it with a console application, was it exactly the same setup or slightly different?
Thanks.

**Comment by JSCProjects** [comment]
You're completely right. The MessageTooLargeException isn't logged. 

The console app uses the same connection strings but not completely the same bus config

**Comment by SeanFeldman** [comment]
Could tou pleaae share you configuration  (minus connection strings)?

**Comment by JSCProjects** [comment]
Shared code

        public static void ApplyCustomConventions(this BusConfiguration busConfiguration, Func<Type, bool> events = null)
        {
            var conventions = busConfiguration.Conventions();
            conventions.DefiningCommandsAs(t => t.Namespace != null && t.Name.EndsWith("Command"));
            conventions.DefiningEventsAs(t => (t.Namespace != null && t.Name.EndsWith("Event")) || (events != null && events(t)));
            conventions.DefiningMessagesAs(t => t.Namespace == "Messages");

            conventions.DefiningDataBusPropertiesAs(
                p => p.Name.EndsWith("LargePayload") || p.Name.Equals("FileContent", StringComparison.OrdinalIgnoreCase));

            conventions.DefiningTimeToBeReceivedAs(
                t => t.Name.EndsWith("Expires") ? TimeSpan.FromSeconds(30) : TimeSpan.MaxValue);
        }


        public static TransportExtensions<AzureServiceBusTransport> ToUseAzureServiceBusTransport(this BusConfiguration busConfiguration)
        {
            var transportConfig = busConfiguration.UseTransport<AzureServiceBusTransport>();
            transportConfig.ConnectionString(Configuration.ServiceBusConnectionString);
            return transportConfig;
        }
    }

My console testapp uses this config

`            var configuration = new BusConfiguration();
            configuration.UseSerialization<JsonSerializer>();
            configuration.ApplyCustomConventions(events: t => t.Namespace != null && t.Namespace.StartsWith("ServiceControl.Contracts"));
            configuration.EndpointName("test.endpoint");
            configuration.ToUseAzureServiceBusTransport();
            configuration.ScaleOut().UseSingleBrokerQueue();
            configuration.ApplyLicenseFromCloudConfig();
            configuration.UseSerialization<JsonSerializer>();
            configuration.UseDataBus<AzureDataBus>().ConnectionString(Configuration.StorageConnectionString);
            using (var bus = Bus.Create(configuration))
            {
                       bus.Send("QUEUE", MSG)
            }`


Our cloud serice

       public void Customize(BusConfiguration configuration)
        {
            configuration.EndpointName("fdr-mi-mc-e66mv");
            configuration.ToUseAzureServiceBusTransport();

            configuration.ScaleOut().UseSingleBrokerQueue();
            configuration.UsePersistence<AzureStoragePersistence>();
            configuration.UseSerialization<JsonSerializer>();
            configuration.UseDataBus<AzureDataBus>().ConnectionString(Configuration.StorageConnectionString);

            configuration.ApplyCustomConventions();
            configuration.ApplyLicenseFromCloudConfig();

            configuration.DisableFeature<Sagas>();
            configuration.DisableFeature<TimeoutManager>();

            var builder = new ContainerBuilder();
            this.RegisterTypes(builder);
            var container = builder.Build();
            configuration.UseContainer<AutofacBuilder>(c => c.ExistingLifetimeScope(container));
        }

**Comment by yvesgoeleven** [comment]
@JSCProjects So if I understand correctly: MessageTooLargeException is not logged in the cloud services host, but it is when hosted in the console application?

This would mean that either the exception is not thrown, or that the exception is catched somewhere before it's logged.

Do you have any size related or exception related logic in your handler? Can you share your handler's code? 

Are you seeing any other ASB specific exceptions around the same time perhaps?

It seems strange that the transport would behave differently depending on the host.

**Comment by JSCProjects** [comment]
This is the handler. Only altered the types.


    public class Handler : IHandleMessages<SomeEvent>
    {
        public Handler(IBus bus, IMapper mapper)
        {
            this.Bus = bus;
            this.Mapper = mapper;
        }

        public IBus Bus { get; }

        public IMapper Mapper { get; }

        public void Handle(SomeEvent message)
        {
            var command = this.Mapper.Map(message);

            this.Bus.Send(Constants.SomeSendEndpoint, command);
        }
    }

**Comment by SeanFeldman** [comment]
@JSCProjects do you observe any ASB exceptions right _after_ the handler is invoked or reported to be completed successfully? What could be happening is the following:
NSB.ASB v6 participated in a transaction. The size in v6 was checked and if it was below the maximum size, was committed, marking handler execution as successful. Unfortunately, that's not accurate. The real size of an ASB message cannot be reported before it's sent, so NSB check for a message size would not catch the messages that are on the border to exceed the max size. Once message is serialized (during the  actual send operation), ASB adds to the overall size and an ASB client (not the transport) exception will be thrown. That would explain why `MessageTooLargeException` is not logged, but message is not received.

Would it be possible for you to scan the log and see if you find the suspected exception(s)?

**Comment by JSCProjects** [comment]
This describes my problem, there are no MessageTooLargeExceptions logged

**Comment by SeanFeldman** [comment]
And what about logs?

**Comment by JSCProjects** [comment]
There is no sign of any exceptions in the nsb.log

**Comment by SeanFeldman** [comment]
@JSCProjects when this is happening, do you get a fatal error logged from `SendResourceManager` starting with "A fatal exception occured while trying to send a message, the exception was..."? If you do, could you please share it?

**Comment by SeanFeldman** [comment]
@JSCProjects can you reproduce this behavior in a standalone project? Thank you.

**Comment by SeanFeldman** [comment]
Closing for now. @JSCProjects please reopen if you can repro this issue. Thank you.
