### ISSUE TITLE
Roundrobin strategy - 2 ASB namespaces with same subscription names

### ISSUE THREAD

**Issue by HaripraghashSubramaniam** [Particular/NServiceBus.AzureServiceBus#487]
Hi,

I have 2 ASB namespaces. I have a topic called XX on each one of them. The names of the topics are same. I have a Azure worker role using NSB ASB 7.1.1 and uses round robin strategy. This worker role creates a subscription called YY to topic XX on namespace1 and another subscription called YY to topic XX on namespace2. Here the creation of  subscription YY on topic XX on namespace2 fails because of the following code.

var exists = await rememberExistence.GetOrAdd(key, notFoundKey =>
            {
                logger.InfoFormat("Checking namespace for existence of subscription '{0}' for the topic '{1}'", subscriptionName, topicPath);
                return namespaceClient.SubscriptionExists(topicPath, subscriptionName);
            }).ConfigureAwait(false);

The key here will always be the same since the topic name and subscription name are the same but they are in different namespaces.

**Comment by HaripraghashSubramaniam** [comment]
This is on similar lines to issue 411

**Comment by boblangley** [comment]
@HaripraghashSubramaniam We have confirmed the problem and I have submitted PR #489 to resolve the issue. I will update this issue when we have released the patch.

**Comment by boblangley** [comment]
@HaripraghashSubramaniam [NServiceBus.Azure.Transports.WindowsAzureServiceBus 7.1.4](https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureServiceBus/7.1.4) has been [released](https://github.com/Particular/NServiceBus.AzureServiceBus/releases/tag/7.1.4) which addresses this issue.
