### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by HaripraghashSubramaniam** [Particular/NServiceBus.AzureServiceBus#490]
@SeanFeldman I have uploaded a repro. Uses azure sdk 2.9.5 with vs2017RC ASB 7.1.1 and NSB 6.1.2. I have removed the ASB conn string and licence. Run the publisher solution to start publishing messages and  WorkerRole1 to receive them. Run it atleast for 15 mins to see the private bytes consumption increasing.

Publisher - https://drive.google.com/open?id=0B4SLN0ruS-dvVEJPSHByMmtnM0k
Subscriber - https://drive.google.com/open?id=0B4SLN0ruS-dvV3VVSjdsLUUxMFE

**Comment by tmasternak** [comment]
@HaripraghashSubramaniam after investigating this we found a bug in ASB 7.1.1 causing the memory leak. We are working on the patch and will inform you as soon as it is read.

**Comment by HaripraghashSubramaniam** [comment]
Thank you. Is there a way to prioritize this? We are very close to production and this is a blocker for us to go live. I have thought of raising a non-critical support request using platinum licence that we have. But not sure if that helps.

**Comment by tmasternak** [comment]
@HaripraghashSubramaniam we are already working on the fix. The patch should be released on Monday.

**Comment by HaripraghashSubramaniam** [comment]
Thank you so much. Really helps

**Comment by tmasternak** [comment]
I'll let you know as soon as it's available.

**Comment by danielmarbach** [comment]
@HaripraghashSubramaniam I created a new issue with a more detailed description. It can be found https://github.com/Particular/NServiceBus.AzureServiceBus/issues/493 thanks for raising this.

**Comment by HaripraghashSubramaniam** [comment]
Thank you. Now it clears it as I was seeing a lot of the internal Async class objects in Gen 2

**Comment by tmasternak** [comment]
@HaripraghashSubramaniam [7.1.3](https://github.com/Particular/NServiceBus.AzureServiceBus/releases/tag/7.1.3) release is out.

**Comment by HaripraghashSubramaniam** [comment]
Thank you so much !!
