### ISSUE TITLE
EnableInstallers & queue creation difference v6

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#500]
According to @JSCProjects there is a difference in configuration that is undocumented. Core v5 would automatically create queues, where v6 does not.

https://twitter.com/JSCProjects/status/831497054249693184

**Comment by indualagarsamy** [comment]
@yvesgoeleven - is this a bug or does this need to be documented?

**Comment by yvesgoeleven** [comment]
@indualagarsamy From my perspective it just needs doco

**Comment by Scooletz** [comment]
I reviewed the current approach based on the installer `QueuesCreator` that calls provided `ICreateQueues`. This is somehow stated on this page: https://docs.particular.net/nservicebus/transports/queuecreation#creation with

> Queues get created during installation time only.

So it looks that it's stated, that queues will be created only when installers are run. In my opinion that's enough and we should not duplicate it in ASB doco if that's handled by the core. 

Thoughts @yvesgoeleven @indualagarsamy ?

**Comment by Scooletz** [comment]
I issued a PR for this page though applying proper versioning (no ifs on the page) https://github.com/Particular/docs.particular.net/pull/2756

**Comment by Scooletz** [comment]
Closing it as it is document in the general documentation which is easy to find by searching for queues' creation.
