### ISSUE TITLE
Create a MSMQ to ASB bridge guidance / sample

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#504]
<sup>*Moved from https://github.com/Particular/docs.particular.net/issues/2036 opened by @indualagarsamy on [11 Oct 2016 19:02 UTC](https://github.com/Particular/docs.particular.net/issues/2036)*</sup>
We have a a MSMQ to Sql relay. We've been getting similar requests for MSMQ to Azure bridging.
Create adequate doco / sample to illustrate it:

Link to Google Group:
https://groups.google.com/forum/#!msg/particularsoftware/wk_3XOkxouk/yCQryfGrAAAJ

**Comment by SeanFeldman** [comment]
<sup>*@SeanFeldman commented on <a id="issuecomment-284432194" href="504#user-content-issuecomment-284432194">06 Mar 2017 15:37 UTC</a>*</sup>
Multiple options, one of them is [NServiceBus.Raw](https://docs.particular.net/nservicebus/rawmessaging/)

**Comment by yvesgoeleven** [comment]
@SeanFeldman moving this in progress as PR is submitted https://github.com/Particular/docs.particular.net/pull/3358

**Comment by SeanFeldman** [comment]
Sample is released https://docs.particular.net/samples/azure/azure-service-bus-msmq-bridge/
