### ISSUE TITLE
[ASB] Partitioning strategy for HA and failover both

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#506]
<sup>*Moved from https://github.com/Particular/docs.particular.net/issues/2240 opened by @SeanFeldman on [14 Nov 2016 20:21 UTC](https://github.com/Particular/docs.particular.net/issues/2240)*</sup>
Document creation of a namespace partitioning strategy that supports both HA and failover in a sample.

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/586

**Comment by danielmarbach** [comment]
Closing in favour of https://github.com/Particular/NServiceBus.AzureServiceBus/issues/505
