### ISSUE TITLE
ASB Transport may attempt to update immutable properties of existing queues / topics

### ISSUE THREAD

**Issue by onesadjam** [Particular/NServiceBus.AzureServiceBus#508]
BUG: Transport will attempt to update immutable properties of entity, resulting in exception.

Encountered in version 7.1.4, but would appear in previous releases as well.

If a queue or topic exists and the requested entity definition is different from the existing definition, the transport will attempt to update the entity.  Some properties are immutable:

- RequiresDuplicateDetection
- EnablePartitioning
- RequiresSession

If the difference between the requested definition and existing definition is limited to these properties, the entity will not be updated.  However, if the difference includes these as well as other, mutable properties, the update attempt will proceed.  This will result in a 400 response from ASB.  For instance, if a queue exists with a maximum size of 1MB and is unpartitioned, and a request is made to define the queue as 5MB and partitioned, the update attempt will proceed because the change in size is allowed.

The resolution is to only update those mutable properties.  Immutable properties should be read from the existing entity and applied to the update request.

**Comment by SeanFeldman** [comment]
Thank you @onesadjam.
Will look into this and PR #509

**Comment by SeanFeldman** [comment]
Added a fix for `RequiresSession` in PR #511

**Comment by SeanFeldman** [comment]
@onesadjam hotfixes are staged and will be released shortly.

**Comment by SeanFeldman** [comment]
Closing this issue. For the relevant hotfixes, subscribe to #512 or #513

**Comment by SeanFeldman** [comment]
@onesadjam 7.1.5 release has [gone out](https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureServiceBus/7.1.5).

**Comment by onesadjam** [comment]
@SeanFeldman Fantastic, thanks for your help!
