### ISSUE TITLE
Support for Basic Tier

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#51]
http://stackoverflow.com/questions/32098881/nservicebus-with-azure-service-bus-basic-mode%3E

**Comment by SeanFeldman** [comment]
Considering that there's no topics with Basic Tier, this would require a separate topology.
How many people would use it?

**Comment by abombss** [comment]
-1, there is almost no reason when using NSB to need basic tier, just use Azure Queues.  Basic Tier makes sense if you want a single API (Azure SDK) or need things like AMQP.  All of that makes no sense when you already have a common API and transport abstraction with NSB.  Also, Standard is not really more expensive, its $10 / mo per subscription, I would assume customers licensing NSB could easily afford $10 / mo if they wanted to ASB.  If they really need free and no native pub / sub then just use Azure Queues.

**Comment by Micha-kun** [comment]
Well, at least, put in the docs Basic tier is not supported.

**Comment by yvesgoeleven** [comment]
@Micha-kun VNext will support basic namespaces, we are redoing the entire configuration & topology model anyway to accomodate for all the new things that ASB team has been releasing (and I expect them to continue to come up with new capabilities), with this new model support for queue only topologies basically comes for free.

**Comment by Micha-kun** [comment]
@yvesgoeleven That's good news :) Anyway, if with current version won't work, I think it should be written in the docs that, for now, only works from Standard tier ahead for clarification.

**Comment by SeanFeldman** [comment]
@Micha-kun [documentation updated](http://docs.particular.net/nservicebus/azure/azure-servicebus-transport#enabling-the-transport), thank you for pointing that out.

**Comment by abombss** [comment]
Should this get closed, nobody uses basic tier

**Comment by SeanFeldman** [comment]
Just like @abombss has mentioned, for queueing only [ASQ transport](https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureStorageQueues) can be used. Major benefit you'll get out of ASQ is full support for pub/sub which you wouldn't get with the basic tier of ASB. There are also other ASB [native features](https://azure.microsoft.com/en-us/pricing/details/service-bus/) that we utilize, and w/o those ASB transport is not a viable option.

@Micha-kun if you'd like to follow up on this, I'll be more than happy to assist with any questions.
Thank you.

**Comment by danielmarbach** [comment]
We discussed this again in the sync meeting yesterday and came to the conclusion it makes no sense for NSB.ASB to support the basic tier as outlined by [@SeanFeldman comment](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/51#issuecomment-194458497). Closing

**Comment by SeanFeldman** [comment]
+100
