### ISSUE TITLE
The bundles feature for the ForwardingTopology can be missconfigured on different endpoints causing message loss

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#524]
## Who's affected

You are affected if you are using ForwardingTopology and custom number of topics in bundle using [`NumberOfEntitiesInBundle(int)` API](https://docs.particular.net/nservicebus/azure-service-bus/configuration/full#configuring-the-topology-forwarding-topology).

## Symptoms

Misconfigured publisher and subscriber cause events to be posted to the topics that are not listened to, causing events to be lost.

## More details

As part of the conversation in #521 it was identified that the scenario for a message loss could exist when `ForwardingTopology` is used and number of topics in bundles are miss-configured on different endpoints (see [this visualization](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/521#issuecomment-294614402)).

We could have a startup check to verify that number of topics per bundle is aligned with the number of actually found topics. If that's not the case, an exception should be thrown preventing endpoint from starting until bundles configuration is resolved.

## Affected versions
- [x] `support-7.2` --> PR #565 
- [ ] `develop` --> PR #570 
- [x] Announcement --> PR https://github.com/Particular/Announcements/pull/149

**Comment by SeanFeldman** [comment]
At maintainers sync, the following was proposed as a part of potential hotfix:

1. Subscriber(s) to scan all the topics in the bundle and subscriber to all (forwarding, cheap)
1. Obsolete Bundle API with proper messages

**Comment by yvesgoeleven** [comment]
Note: The above is not completely fool proof. If publisher reconfigures the number of bundles without upgrading then subscriber may still miss messages.

**Comment by SeanFeldman** [comment]
@yvesgoeleven have a look at #3 in the https://github.com/Particular/NServiceBus.AzureServiceBus/issues/524#issuecomment-295322130 - it will address the edge case you referred to.

**Comment by yvesgoeleven** [comment]
@SeanFeldman good idea, allows to drain the second topic before we stop using it

**Comment by yvesgoeleven** [comment]
created a branch for this issue https://github.com/Particular/NServiceBus.AzureServiceBus/issues/524

**Comment by yvesgoeleven** [comment]
> Subscriber(s) to scan all the topics in the bundle and subscriber to all

This requires the transport to have manage rights, what will we do if we don't have manage rights?

**Comment by yvesgoeleven** [comment]
From first investigation it appears that ForwardingTopology.RunPreStartupChecks might be the right place to check for the bundles configuration (there we know if we get manage rights or not)

**Comment by SeanFeldman** [comment]
I already had a branch for this that wasn't pushed 😀

**Comment by SeanFeldman** [comment]
`hotfix-7.2.1` branch replaced `prevent-bundle-misconfiguration`.

**Comment by SeanFeldman** [comment]
Pre startup checks are executed _after_ we create topology sections.
Because of that, we can't scan for topics in `ForwardingTopology.RunPreStartupChecks()` but need to do it before, in `ForwardingTopology.GetQueueCreatorFactory()` (which is executed by `TransportInfrastructure.ConfigureSendInfrastructure()` that is first calling `topology.GetQueueCreatorFactory()` and only after that `topology.RunPreStartupChecks()`).

Perhaps there's a better place, but I can't think of any @yvesgoeleven

**Comment by SeanFeldman** [comment]
There are a few paths:

1. **Installers turned off, manage rights not needed** - we don't care, user responsibility to set up the topology. Runtime exception will take place if topology is not created properly.
1. **Installers turned on, no manage rights** - we'll throw an exception about lack of manage rights at startup.
1. **Installers turned on, manage rights exist** - this PR will handle misconfiguration between publishers and subscribers.

Which would mean that Manage Rights PR #547 would need to go in first.

@danielmarbach could you repeat what we've discussed and why do you think it won't work?

**Comment by SeanFeldman** [comment]
Once hotfix 7.2.3 ( #555) is merged, this PR will be unblocked.
Will need to rebase and review verification of the management rules as it will become unnecessary since #555 will handle that.

**Comment by SeanFeldman** [comment]
With 7.2.3 released, I re-started work on this one.

Still having a problem with timing. The manage rights check is now taking place in [`TopologyCreator.Create()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e1719d446567b50983cfd810d76f2c91c8a251f9/src/Transport/Topology/TopologyCreator.cs#L33). Challenge with that is the fact that it operates on topology section generated by `TopologySectionManager` that requires to know about the topics (ie run the manage rights check). Chicken and egg situation. 

@danielmarbach I'm not sure how to avoid manage rights duplication tbh.

**Comment by SeanFeldman** [comment]
Ah, see that now we're checking manage rights in `TransportResourcesCreator` first, then invoke section manager.

**Comment by danielmarbach** [comment]
Closing this to get proper release notes
