### ISSUE TITLE
SendAtomicWithReceive documentation is hard to understand

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#525]
The diagram for the `SendAtomicWithReceive` ([Understanding internal transactions and delivery guarantees page](https://docs.particular.net/nservicebus/azure-service-bus/understanding-transactions-and-delivery-guarantees)) is very hard to understand. It requires understanding of core pipelines, context of the transactionscope and ASB relationship.

> I think at a minimum, it should be accompanied by a written description of what is in the diagram, e.g. I don't understand why we have 3 pipeline blocks in it

Suggested to rework this documentation to break down the diagram into series of visualized steps to make this doco simpler rather than just add text.

Additional issue raised in doco: https://github.com/Particular/docs.particular.net/issues/2679

**Comment by SeanFeldman** [comment]
@yvesgoeleven could you take a stab at this? I can help from Monday.

**Comment by yvesgoeleven** [comment]
I have reworded it. Don't think the diagram needs to be split, all you can do is leave the curly braces representing the scope on/off but I don't see much value in that.

**Comment by SeanFeldman** [comment]
WIP removed, at a review stage.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/docs.particular.net/commit/d8cf5d42dfec6611a30f06db6185f041978afd3c
