### ISSUE TITLE
Polymorphic events

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#53]
Currently polymorphic events are ending up being sent multiple times due to inner workings of Azure Service Bus subscriptions.

## Example

**Polymorphic Messages**
`Shared.Events` (Namespace)
`EventA : IEvent`
`EventB : EventA`

**Handlers**
`HandlerA : IHandle<EventA>`
`HandlerB : IHandle<EventB>`

**Invocation**

`bus.Publish<EventB>(e => ...);`

**Expected behaviour**

Handler A and B to be invoked

**Actual behaviour**

Handler A and B are invoked twice each

## Analysis

What's happening is that endpoint publishing these events has 2 subscriptions: one for `EventA` and one for `eventB`. When message of type `EventB` is published, it will be sent to subscriber twice (once because default rule filter on `EventA` subscription will catch it with `[NServiceBus.EnclosedMessageTypes] LIKE '%Shared.Events.EventA%' OR...` and once because default rule filter on `EventB` subscription will catch it with `[NServiceBus.EnclosedMessageTypes] LIKE '%Shared.Events.EventB%' OR...`). This is because published message `NServiceBus.EnclosedMessageTypes` header is `Shared.Events.EventA, Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null;Shared.Events.EventB, Shared, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`
Since each event message will be delivered to an endpoint, each will go through polymorphic routing and will be invoked with event handlers that can handle it, i.e. `HandlerA` and `handlerB`. This will result in duplicate invocation of handlers.

## Workaround

1. Disable auto-subscription for subscriber endpoint 
1. Subscribe to base event only manually

[GG issue](https://groups.google.com/forum/#!topic/particularsoftware/g7roalODpLU)

Connect to #13

**Comment by SeanFeldman** [comment]
@Particular/azure what do we do with this?

**Comment by SeanFeldman** [comment]
We should implement polymorphic event dispatch using `SqlRuleAction`s. This will allow proper implementation w/o workarounds.

**Comment by WestDiscGolf** [comment]
@SeanFeldman that doesn't sound like a quick fix, any idea when the issue will be resolved?

**Comment by yvesgoeleven** [comment]
@WestDiscGolf there is no quick fix for this issue besides the workaround, to fix it properly we need to change the internal broker topology and we can only do that in a next major release as it requires significant changes. We are working very hard on the next major, but can't give you an ETA yet.

**Comment by WestDiscGolf** [comment]
@yvesgoeleven thought that might be the case. Thanks for the update :-)

**Comment by SeanFeldman** [comment]
@WestDiscGolf there's also an issue with NServiceBus core - it performs polymorphic routing on it's own, so just transport change would not be enough unfortunately :(

**Comment by WestDiscGolf** [comment]
@SeanFeldman owch :-( Ok, well thanks for letting us know :-)

**Comment by SeanFeldman** [comment]
@WestDiscGolf in the new topology polymorphic events will be working as expected OOTB.

**Comment by WestDiscGolf** [comment]
@SeanFeldman Thanks for the update :-)

**Comment by SeanFeldman** [comment]
**Issue**

`TopologySectionManager.DeterminePublishDestination()` is used for both, topology section creation (from `SumbscriptionNamanger`) and querying (from `Batcher.AddMulticastOperationBatches()`) which causes two things:
1. Return entities for partitioning intent that is "hard-coded", `PartitioningIntent.Creating`
2. Once topology section is calculated, the model is cached and all topics in the bundle are always returned, causing published event to be duplicated as number of topics in the bundle.

Need to address this in order to make polymorphic events to work OOTB along with normal events.
Repro: polymorphic events sample with `ForwardingTopology`.

/cc @yvesgoeleven

**Comment by WestDiscGolf** [comment]
@SeanFeldman @yvesgoeleven Can you clarify if this will be fixed in V6 or V7? It's marked with a V7 milestone but with a Core V6 tag? Cheers

**Comment by yvesgoeleven** [comment]
@WestDiscGolf both :) Core = V6, ASB transport = V7

**Comment by yvesgoeleven** [comment]
Our components are versioned independently

**Comment by WestDiscGolf** [comment]
@yvesgoeleven Cool, thanks for the clarification :-)

**Comment by SeanFeldman** [comment]
@WestDiscGolf if you need it in v5, there's a sample for getting it to work: docs.particular.net/samples/azure/polymorphic-events-asb/
