### ISSUE TITLE
Duplication of Timeout Messages

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#530]
Original issue raised in GG: https://groups.google.com/forum/#!topic/particularsoftware/gpDXlWqwWMg

Description: 
NSB 6.x / ASB 7.x

> We are upgrading from NSB 5 to 6 and I'm at the part where I'm upgrading code that handles deduplication of timeout messages.  We previously tried Outbox but ran into performance issues due to the volume of traffic (north of 10 million a day).  We removed Outbox and leveraged Azure's deduplication capabilities and a Feature that would format messages to enable deduplication.  That works, but with the upgrade we're looking around at some other options to streamline things.

> We have one service that creates and receives timeouts.  It gets one, kicks off some work, and puts another one on the bus with a future delivery date.  Each "job" which maps to a row in the appropriate saga table has a single timeout, so if we have 200,000 rows in the saga table, then we'd have 200,000 timeouts.  There is a separate problem where we have noticed that Timeouts can be lost (the working theory is that if the Windows Azure Worker Host crashes we will lose timeouts) and I'm also hoping that SendsAtomicWithReceive will prevent this issue, but I haven't tested that part yet.

> With NSB 6 I wanted to try and leverage TransportTransactionMode.SendsAtomicWithReceive to see if that would be an acceptable solution.  My first test of 3.6 million messages resulted in 41 duplicate timeout messages.  That was with azure deduplication turned off on that queue and with our custom feature disabled.

> I was also hoping that Batched Messaging (https://docs.particular.net/nservicebus/upgrades/5to6/messaging) would address this issue.

> So, I guess my question is, should SendsAtomicWithReceive have prevented the creation of duplicate timeouts, or is the only way to truly prevent this through NSB to use Outbox, a custom feature, or to not use timeouts at all for this purpose and instead use a webjob or something to trigger this activity?

>The code to enable SendsAtomicWithReceive is:

> transport.TransportType(Microsoft.ServiceBus.Messaging.TransportType.NetMessaging);
> transport.Transactions(TransportTransactionMode.SendsAtomicWithReceive);

**Comment by SeanFeldman** [comment]
Distilled version to repro the issue:

Endpoint gets 5K messages. For each message, a short (1 minute) timeout is scheduled. When timeouts are processed, a replacement timeout message is issued. Over time, number of timeouts starts to grow (duplicates).

Solution with using message id deduplication (ASB native feature) helped, proving that endpoint is sending duplicates.

@daerath have I summed it up correctly?

**Comment by SeanFeldman** [comment]
@daerath what persistence are you using when running this?

**Comment by daerath** [comment]
Correct.  However the timeout delay we use for prod is between 5 and 7.5 minutes (the random drift helps spread work out to avoid clumping), but we've seen duplicates with short timeouts (1 minute) and longer ones (7.5 minutes).

Correct in that we are using the native ASB deduplication feature to prevent this problem.

We're using NHibernatePersistence for this service.  That's where we're storing sagas related to those timeouts.

**Comment by SeanFeldman** [comment]
@daerath could you please share how did you implement your native de-duplication? Did you implement a custom `IConvertOutgoingMessagesToBrokeredMessages`?

**Comment by daerath** [comment]
Attached.  We implemented it as a pipeline step in NSB5 and ported it over for NSB6.  It works on the IOutgoingLogicalMessageContext that adjusts the context.Headers MessageId before returning next().  Attached instead of pasting it here.

[dedup.txt](https://github.com/Particular/NServiceBus.AzureServiceBus/files/965193/dedup.txt)

**Comment by SeanFeldman** [comment]
@daerath this doesn't really help since ASB's native de-dup is based on the physical message ID, which ASB transport set's to a [random GUID for every outgoing message](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e5f8c315adc2c6703ace760b72e975b0d2307c73/src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs#L30). This happens regardless of the NSB message ID header which is ignored (in the context of the linked code, NSB message header ID would be found in `outgoingOperation.Message.MessageId`).

**Comment by daerath** [comment]
That's very odd then.  It absolutely worked in our NSB5 implementation.  Did the exposed properties change in NSB6?  It's possible I ported it over incorrectly as that code did change somewhat.  Let me check out version history to see if this isn't just a bug in the NSB6 version.

**Comment by SeanFeldman** [comment]
In NSB v5 [that was the case](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/support-6.4/src/Transport/Utils/BrokeredMessageConverter.cs#L107) @daerath as the transport used the message ID set by NSB for the physical message (`BrokeredMessage`).

In NSB v6, it's no longer the case.

**Comment by daerath** [comment]
Ah.  So...  It sounds like our old method won't work in 6.0.  That's definitely going to be a blocker for us to complete the upgrade.  Is there any possibility of exposing a property to let us set the physical message ID?  Alternately, is there a sample relating to IConvertOutgoingMessagesToBrokeredMessages that would give details on how we could set that value?

**Comment by SeanFeldman** [comment]
With NSB 6, there are [4 transport transaction guarantees](https://docs.particular.net/nservicebus/transports/transactions). With ASB transport, we support [`SendAtomicWithReceive`](https://docs.particular.net/nservicebus/azure-service-bus/understanding-transactions-and-delivery-guarantees) which should work for your scenario. By working around the issue with the physical message ID and native de-duplication, we're hiding the actual cause of the problem. I'd like to find the root cause of the problem to eliminate it.

With `SendAtomicWithReceive` guarantee, outgoing messages (including timeouts) should **never** go out if exception is thrown either in the handler code or by the saga persister.

**Comment by daerath** [comment]
Oh, I am in absolute agreement.  I would much rather the root duplication cause be fixed, but until it is, and since we're already using SendAtomicWithReceive, I'm trying to find a way to not block our deployment.

**Comment by SeanFeldman** [comment]
@daerath I've managed to narrow this down. This a bug in the transport NSB.ASB.
I'll raise an issue and link to here.

**Comment by daerath** [comment]
Fantastic!  I'm trying a scale up approach to repro the other issue, and will try to make a stock msn repro as well.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SeanFeldman** [comment]
@daerath issue #532 is what we've got. You don't need to scale up to repro it. I've managed to repro within less than an hour with a single queue and [this code](https://github.com/SeanFeldman/Duplicates.Repros).

**Comment by SeanFeldman** [comment]
Closing this in favor of #532
