### ISSUE TITLE
Duplicates with SendsAtomicWithReceive transport transaction mode

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#532]
Related to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/530

## Who's affected

Anyone using Azure Service Bus transport with `SendsAtomicWithReceive` transaction guarantee

## Symptoms 

Incoming message is processed, **not** completed (a warning about message lost lock is logged), but the outgoing messages are dispatched.
As a result of that, incoming message is re-processed, causing outgoing messages to be sent again, generating duplicates.

## Analysis

The incoming message completion and outgoing batched operations are wrapped in a transaction. Transaction should be completed when the incoming messages is completed successfully _and_ outgoing messages are dispatched.

When an [incoming message is completed](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/6597458e4050c05d19eabfe482c35f2b112058f7/src/Transport/Receiving/MessageReceiverNotifier.cs#L227), there's a slight chance that the lock will be lost. If that's the case, the wrapping transaction should not be completed. Currently, the transaction is completed, causing outgoing messages to be dispatched irregardless of the incoming message completion status.

## Affected versions

The following [supported versions](https://docs.particular.net/nservicebus/upgrades/all-versions#transport-packages-nservicebus-azure-transports-windowsazureservicebus) are affected

- [x] `7.1`
- [x] `7.2`
- [ ] `develop`

## Original issue

https://github.com/Particular/NServiceBus.AzureServiceBus/issues/530

**Comment by daerath** [comment]
@SeanFeldman Sweet.  Great catch!

**Comment by SeanFeldman** [comment]
fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/609eb483cc2a9f229ccb6fb974e7043ae5a6c55b
