### ISSUE TITLE
Discussion - Handling Failed to Dispatch exception less severely

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.AzureServiceBus#536]
So I might be looking at below logs incorrectly, but it seems to me the logging could be improved to be less shocking.

The error log says `Failed to dispatch a batch with the following message IDs: 77edab5d-0f5b-4b4e-8ebf-ce66b397b13c`. Then NSB smartly tries to abandon this, which fails too because of the same (probably) connection issue. Then we get the log `Abandoning brokered message ce33a65d-49ef-49ca-8e98-38ba3bfd854a failed. Message will reappear after peek lock duration is over.`.

There's probably a couple of layers of abstractions I'm killing with it, but from my point of view the logs would be improved a lot if the error line contains this 'you'll be ok, NSB + ASB takes care of this, this will just get re-processed' kind of approach. I get notified of error logging, and since the `Failed to dispatch` sounds pretty fatal, I dig into the logs every time to verify nothing got lost.

![image](https://cloud.githubusercontent.com/assets/383634/25651100/85a43362-2fe1-11e7-931e-b4c779877f23.png)

**Comment by yvesgoeleven** [comment]
@janpieterz it really depends on how the transport is configured. you can configure it so that the second step doesn't happen when the first occurs. In order to merge these logs we would have to bleed receive configuration info and related logic into the dispatcher, blending concerns.

**Comment by janpieterz** [comment]
True, I was afraid of killing/blending those abstractions.
With the above transport config, would it be safe to just ignore this one since it would always get reprocessed?

**Comment by yvesgoeleven** [comment]
@janpieterz yes you can ignore it, as long as peek lock is on you won't loose any messages. even if the failures keep occuring over and over the message will still be in the dlq and can be resubmitted for processing

**Comment by janpieterz** [comment]
Great, thanks!
