### ISSUE TITLE
Automatically reduce number of receive clients when concurrency limit is lower

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#539]
Currently the default values for concurrency limit & number of receivers are both equal to the number of cores on the machine. If users lower the concurrency limit and not the number of receivers, then those receivers will still each pick up a message which is then 'blocked' by a semaphore to respect the concurrency limit.

This is wastefull in resources, and can lead to increased message lock lost exceptions if the operation takes long. If message lock lost exceptions occur, and the execution of the initial method took very long (as was the case in one of our ATT's), then it even leads to weird behavior where the other receivers pick up the messages that you were processing, which then get blocked until the first execution finished, but continue before the test ends. Aka unexpected results.

Maybe it's a good idea to automatically reduce the number of receivers if the concurrency limit is less than that number.

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/587

**Comment by SeanFeldman** [comment]
👍 
I'll try to summarize a few things that would like to see discussed, specifically:
1. Throttling (NSB message pump) vs concurrency (ASB client receivers).
1. Tying number of receivers to concurrency level.
1. Preventing throttled messages that expired entering pipeline.
