### ISSUE TITLE
Align with `NServiceBus.Core` to use own `TaskEx.Completed`

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#54]
Instead of `Task.FromResult(true)` use your own internal copy of https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/TaskEx.cs

@Particular/tf-asyncawait agree?

**Comment by SeanFeldman** [comment]
@danielmarbach you mean this?

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/BatchSend/src/Transport/TaskEx.cs#L5

:)

**Comment by danielmarbach** [comment]
@SeanFeldman yes I saw a lot of code which wasn't using it

**Comment by danielmarbach** [comment]
Talk to @yvesgoeleven I briefed him today

**Comment by SeanFeldman** [comment]
[This](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/54#issuecomment-145911436) can be explained by lack of information flowing. Need to get better at that ;)

Moving forward, `TaskEx.Completed` is used.

**Comment by yvesgoeleven** [comment]
None left
