### ISSUE TITLE
Support ASB SDK 3.x

### ISSUE THREAD

**Issue by abombss** [Particular/NServiceBus.AzureServiceBus#55]
The new ASB SDK 3.x is RTM and it should be fully compatible with NSB.  Please change the nuget package dependencies to support >= 2.x and <= 4.x.

https://www.nuget.org/packages/WindowsAzure.ServiceBus/3.0.4

There are some features in 3.x that we would like, especially setting connectivity mode to HTTPS to provide for faster startup and avoid protocol negotiation for SBMP over websockets and HTTPS.

The only breaking changes that I know of are removing the old APM methods in favor of the TAP methods, but I believe NSB currently only uses the Sync based methods.

**Comment by yvesgoeleven** [comment]
vnext is built against this SDK, can you wait until then, or are you asking for a change to current?

**Comment by SimonCropp** [comment]
@abombss I assume u mean ` >= 3 and < 4` and not ` >= 2 and <= 4` since we dont want to claim compat with a yet to be released version and we dont want to attempt to also support v2 with all the breaking changes between 2 and 3 http://apicomparer.particular.net/compare/WindowsAzure.ServiceBus/2.0.0...3.0.0

**Comment by abombss** [comment]
Correct, >= 2 & < 4

We were actually looking for a refresh with all current nsb / asb versions.
We had some support tickets open with MS and they wanted us to update to
the 3.x SDK.

Adam

**Comment by yvesgoeleven** [comment]
@abombss You can always override dependencies by specifying --IgnoreDependencies in your Update-Package statement when updating the ASB SDK, then it should install as well. But we'll take this along in the next patch

**Comment by SeanFeldman** [comment]
Next version (v7) is using ASB v3
