### ISSUE TITLE
occured => occurred

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#560]
Thank you @dvdstelt, will fix spelling mistake

https://github.com/Particular/NServiceBus.AzureServiceBus/search?utf8=%E2%9C%93&q=occured&type=

**Comment by SeanFeldman** [comment]
Fixed in `develop`

**Comment by SeanFeldman** [comment]
Also will be included in hotfix-7.2.4 targeting `master`.
