### ISSUE TITLE
Frequent checks for existence of ServiceControl queues

### ISSUE THREAD

**Issue by Bishbulb** [Particular/NServiceBus.AzureServiceBus#566]
I'm seeing the following sequence of logs appearing every 10 seconds in an endpoint that hosts a send-only bus:

> 2017-05-30 19:37:00.304 INFO  NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator Checking existence cache for 'Particular.ServiceControl'
2017-05-30 19:37:00.304 INFO  NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator Determined that the queue 'Particular.ServiceControl' exists
2017-05-30 19:37:00.304 INFO  NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusQueueCreator Queue 'Particular.ServiceControl' already exists, skipping creation

We're running version 6.4.1 of the `NServiceBus.Azure.Transports.WindowsAzureServiceBus` package, with a send-only instance of the bus. The code to create the singleton bus instance is as follows:

> var configuration = new BusConfiguration();
configuration.UseSerialization<JsonSerializer>();
configuration.UseTransport<AzureServiceBusTransport>().ConnectionStringName("Azure.ServiceBus");
bus = Bus.CreateSendOnly(configuration);

Is it normal/expected to have these frequent log messages regarding ServiceControl? Note that we do have the `ServiceControl.Plugin.Nsb5.Heartbeat` package installed in this endpoint (version 2.0.1).

**Comment by yvesgoeleven** [comment]
@Bishbulb yes those are normal, it checks the cache and is not actually hitting the service. In future versions of the transport we have removed the log, it is annoying.

if you want to get rid of them you can add a filter at the log4net level
