### ISSUE TITLE
Lots of transient exceptions lately, causing endpoint failures

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.AzureServiceBus#567]
We've been seeing more and more transient exceptions lately on ASB. 
This is generally fine, as the retry picks it up and the messages get processed in the end.
The problem is the NSB endpoints tend to go down too. 

While an auto-service restart is fine, I wonder if this occurs with more NSB clients, and if there's some way the trigger behavior can be set to be less trigger-happy, or in general change the approach, given that it seems ASB is becoming more and more failure-prone.
I realise this isn't really something that's wrong in NServiceBus, though it'd be nice to be able to tackle it here.

MSDN chats:
[1] : https://social.msdn.microsoft.com/Forums/en-US/cab03738-e238-49ed-b553-1bf4c4c41033/timeout-exceptions?forum=servbus
[2]: https://social.msdn.microsoft.com/Forums/en-US/17920ac2-4b23-47b0-8174-b5a4ef6cfca9/lots-of-instability-in-service-bus-connections-lately?forum=servbus

Logging of, for example, last night. It kept kind of recovering and then failing, after a while it ended up not recovering anymore.

![image](https://cloud.githubusercontent.com/assets/383634/26668607/c8030c76-46aa-11e7-8bbc-a99c26e9be57.png)

**Comment by danielmarbach** [comment]
Hi @janpieterz 

In the OnExceptionReceived event handler before we trigger the error callback, we log a few things with log level DEBUG and INFO. Would it be possible to attach the log file here so that we can have a closer look?

I'm specifically interested in

> OptionsOnExceptionReceived invoked, action: '{exceptionReceivedEventArgs.Action}', with non-transient exception.

**Comment by janpieterz** [comment]
Certainly! Made a gist (CSV export from Seq):
https://gist.github.com/janpieterz/01ade98f59e25a29340f4c74b892c348

OptionsOnExceptionReceived has two, both with RenewLock: `OptionsOnExceptionReceived invoked, action: 'RenewLock', with non-transient exception.`

**Comment by yvesgoeleven** [comment]
yeah we've seen a few more cases over the past week, and Ms support always seems to suggest "You can try recreate these entities as partition entity for the mitigation"

Funny thing is that deleting all entities and recreating them helped in all cases so far, partitioned or not does not matter.

something must be off on the service side that disappears when recreating the entity as all resources are obviously reset and reallocated. But it's a nuclear bomb solution, they'd better fix the underlying issue instead.

**Comment by janpieterz** [comment]
Very odd! 
So would this be simply deleting all queues and topics and letting NSB re-create them?

Goes into the box of great _have you tried turning it off and on again_ 😄

**Comment by yvesgoeleven** [comment]
basically yes, you'll loose the messages inside though so it's not a solution for a production environment.

**Comment by janpieterz** [comment]
I can (luckily) control most input into the queues, everything gets retried externally if I don't push it to a queue.
I'll give it a shot!

**Comment by danielmarbach** [comment]
@janpieterz I do think though we could do a better job with the RenewLock action. I'll discuss it internally and keep you posted.

**Comment by janpieterz** [comment]
Great @danielmarbach ! Although this might solve it for now, who's to say it doesn't come back indeed! 
It'd be great if the errors that are more 'transient' (restart fixes it) wouldn't case it to fail but just to back off. 

I'll keep an eye on this thread, our production change will probably be done on Monday, if this _doesn't_ fix it I'll pop back here!

**Comment by danielmarbach** [comment]
@janpieterz Raised an issue. https://github.com/Particular/NServiceBus.AzureServiceBus/issues/568 What's your thought? Feel free to comment on the other issue

**Comment by SeanFeldman** [comment]
Closing this issue in favor of #568

**Comment by janpieterz** [comment]
Just to report back about re-creating queues and topic on production, started tracking end of 31st of May. Not totally gone but significant improvement.

![image](https://user-images.githubusercontent.com/383634/27081885-d0066552-5042-11e7-8137-61624f292475.png)

**Comment by yvesgoeleven** [comment]
@janpieterz did you also get an email about the capacity changes in West - EU? I assume you were impacted as well

**Comment by janpieterz** [comment]
I did not, odd! Any link? We indeed run in west-eu.

**Comment by yvesgoeleven** [comment]
@janpieterz in short, the issues should be resolved now, more capacity was added

**Comment by janpieterz** [comment]
Good to know, cheers!

**Comment by SeanFeldman** [comment]
> re-creating queues and topic

ASB team has rolled out a fix on the broker side in the last couple of weeks that was related to entities creation bug. Could be a contributor as well 😉
