### ISSUE TITLE
Trace messages that are larger then the maximum message size allowed by Azure ServiceBus

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus.AzureServiceBus#57]
Things to do:
- [ ] Documentation

---

**Original issue**:
Messages that fail by the BrokeredMessageConverter.GuardMessageSize, don't seem to end up in Audit Queue (or just not with the message Id provided in the error message). Can understand if its by design, but where can one find the message to investigate the content?

**Comment by SeanFeldman** [comment]
Audit queue would only get messages that are incoming messages and were successfully processed. In this case, application is trying to send out a message that is more than 256KB and that will fail. That means there is no successful processing of a message, so no audit.
I see your point about ID in the exception and ability to investigate the message. @Particular/azure  should we log the body of the message rather than the ID which will not go anywhere anyways?

It could be a wider question beyond ASB transport.

**Comment by yvesgoeleven** [comment]
Transport won't be able to send it anywhere in ASB as the body size won't fit, only thing we could do is log the body to a local file I guess, or maybe a blob?

**Comment by danielHalan** [comment]
Storing it as a Blob sounds like an good idea, could be good convention for any messages that "fail to launch" for some reason (transport etc).

**Comment by yvesgoeleven** [comment]
It can't be default behavior, as asb transport is uncoupled from azure storage and has to stay that way, but it could be a plugin model that you can turn on when using ASB in combination with Azure storage.

**Comment by SeanFeldman** [comment]
Things to do:
- [ ] Documentation

**Comment by abombss** [comment]
Why can't the user catch the exception at the point of send / publish and handle it there?  There is also the DataBus for large messages and the claim check pattern.

**Comment by yvesgoeleven** [comment]
We should mention the databus in the exception message indeed, but sometimes you don't know/expect a message property to be large and you can get caught of guard. When a developer doesn't realize he should have used databus, he's also not going to think of handling the message size exceeded exception. I think what @danielHalan want's to prevent here is, outbound message loss, when the dev doesn't take size into account.

**Comment by SeanFeldman** [comment]
We should 
- [ ] provide some guidance on using `DataBus` in the [exception](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Sending/ThrowOnOversizedBrokeredMessages.cs#L11)
_and_
- [ ] log a warning message > than a max message size is [detected in the router](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src%2FTransport%2FSending%2FDefaultOutgoingBatchRouter.cs#L161)

**Comment by yvesgoeleven** [comment]
Replaced by https://github.com/Particular/docs.particular.net/issues/1274
