### ISSUE TITLE
Support FailOverNamespacePartitioning and SendsAtomicWithReceive together

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#571]
Question/Feature request from the forums

https://groups.google.com/forum/#!topic/particularsoftware/PvjiC4Hzumo

Can we support this?

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/586

**Comment by yvesgoeleven** [comment]
Option:

Explicit opt in method that specifies how to combine the 2 features

transport
   .Transactions(TransportTransactionMode.SendsAtomicWithReceive);
   .AllowCrossNamespaceTransactions(FallbackBehavior.Silent)

**Comment by SeanFeldman** [comment]
Our failover strategy is currently invoked upon dispatching. That is when a message is received from a namespace-A and we attempt to dispatch messages and cannot. To enable failover and keep atomic send with receive, we'd need to 
1. Review when failover happens (cannot be during dispatching as we'd end up with an incoming message from namespace-A and trying to dispatch to namespace-B. SendVia will not be possible.
1. Review what do we do have a state when a message received from namespace-A and we failed over, while in this opt-in mode.

I suggest maintainers discuss this first prior to committing to a feature or suggesting API 😃
