### ISSUE TITLE
Update SC doco to list incompatible features

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#572]
https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features

**Comment by ramonsmits** [comment]
I think it is not only needed to add it to this page but to all pages where features are documented. Just as I did with the notes in https://github.com/Particular/docs.particular.net/pull/2846 . ServiceControl is probably not the first thing a customer is configuring/installing. They should be advised upfront of any incompatibilities.

**Comment by SeanFeldman** [comment]
Added https://github.com/Particular/docs.particular.net/issues/2851 and https://github.com/Particular/docs.particular.net/issues/2850

**Comment by yvesgoeleven** [comment]
PR https://github.com/Particular/docs.particular.net/pull/2855
