### ISSUE TITLE
Smoketest docs update

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#575]
from @SimonCropp 

> i updated docs samples to NServiceBus.Azure.Transports.WindowsAzureServiceBus 7.2.4  u might want to smoke test

**Comment by SeanFeldman** [comment]
Should have been part of
https://github.com/Particular/docs.particular.net/pull/2826

I missed it out.

**Comment by SeanFeldman** [comment]
Tested pub/sub related sample
