### ISSUE TITLE
Subscribe to multiple azure service buses

### ISSUE THREAD

**Issue by jeremy001181** [Particular/NServiceBus.AzureServiceBus#58]
Hi 

A requirement I had is to build a windows service that can subscribe to events that are from multiple topics that are created under different azure service buses (different connection string)

Is there any way I can have multiple `AzureServiceBusQueueConfig` in single app.config?

```
  <AzureServiceBusQueueConfig 
    BackoffTimeInSeconds="3" 
    BatchSize="10" 
    ConnectionString="" 
    DefaultMessageTimeToLive="" 
    EnableDeadLetteringOnFilterEvaluationExceptions="true" 
    EnableDeadLetteringOnMessageExpiration="true"
    LockDuration="3000" 
    MaxDeliveryCount="3" 
    MaxSizeInMegabytes="2048" 
    QueueName="" />
```

**Comment by yvesgoeleven** [comment]
Hi Jeremy,

You can specify the connectionstring to use in the message endpoint mapping, similar to this

<UnicastBusConfig>
    <MessageEndpointMappings>
      <add Assembly="assembly1" Endpoint="topic@connectionstring1" />
      <add Assembly="assembly2" Endpoint="othertopic@connectionstring2" />
    </MessageEndpointMappings>
  </UnicastBusConfig>

**Comment by jeremy001181** [comment]
Thanks
