### ISSUE TITLE
Retire support branches that are no longer needed

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#582]
According to our [support policy](https://docs.particular.net/nservicebus/upgrades/supported-versions#transport-packages-nservicebus-azure-transports-windowsazureservicebus), the following support branches are out of support:
- `support-6.2`
- `support-6.3`
- `support-7.0`
- `support-7.1`

Do we need to remove those branches?

**Comment by Scooletz** [comment]
I see no point of having them pinned for no reason.
