### ISSUE TITLE
Subscribe on other namespace is broken

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#584]
Relates to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/586

Looks like it is no longer possible to subscribe on an endpoint in a different namespace (one not part of topology), now that endpoint mappings are gone

**Original issue**

[GG post](https://groups.google.com/forum/#!topic/particularsoftware/9XK0kL5YuJc)

> I have have an azure cloud service(worker role) endpoint. This is worker role listens to 2 ASB namespaces N1 and N2. Events E1, E2, E3 are published by another component on both the namespaces N1 and N2. Is there a way to for NSB to listen to events E1 and E2 in ASB Namespace N1 and listed to Event E3 in ASB Namespace N2? Currently it is listening to events from both the namespaces.

> This was possible in NSB 4.7.6 and the control was through EndpointMappings. So this feature is no possible with NSB 6.0?

TODO:
 - [ ] Documentation update

**Comment by HaripraghashSubramaniam** [comment]
May I please know how this is being prioritized at the moment?

**Comment by SeanFeldman** [comment]
@HaripraghashSubramaniam we'll start investigation this week to identify at what point this feature was no longer supported.

**Comment by danielmarbach** [comment]
Hi @HaripraghashSubramaniam 

It is still possible to listen to events E1 and E2 in ASB Namespace N1 and listed to Event E3 in ASB Namespace N2 by doing the following:

The subscriber endpoint which wants to listen to E1 and E2 could add a custom namespace partitioning strategy like described in [Custom ABS Namespace Partitioning](https://docs.particular.net/samples/azure/custom-partitioning-asb/) documentation page.

The subscriber can then use the strategy in the following way:

```
        var namespacePartitioning = transport.NamespacePartitioning();
        namespacePartitioning.AddNamespace("namespace1", "Endpoint=sb://namespace1");
        namespacePartitioning.AddNamespace("namespace2", "Endpoint=sb://namespace2");
        namespacePartitioning.UseStrategy<ReplicatedNamespacePartitioningStrategy>();
```

then it could declare handlers that receive events from both namespaces.

```
public class EventFromNamespace1Handler :
    IHandleMessages<EventFromNamespace1>
{
    static ILog log = LogManager.GetLogger<EventFromNamespace1Handler>();

    public Task Handle(EventFromNamespace1 message, IMessageHandlerContext context)
    {
        log.Info($"Received EventFromNamespace1. EventId: {message.EventId}");
        return Task.CompletedTask;
    }
}

public class EventFromNamespace2Handler :
    IHandleMessages<EventFromNamespace2>
{
    static ILog log = LogManager.GetLogger<EventFromNamespace2Handler>();

    public Task Handle(EventFromNamespace2 message, IMessageHandlerContext context)
    {
        log.Info($"Received EventFromNamespace2. EventId: {message.EventId}");
        return Task.CompletedTask;
    }
}
```

I attached an example

[custom-partitioning-asb_asb_7-modified.zip](https://github.com/Particular/NServiceBus.AzureServiceBus/files/1142197/custom-partitioning-asb_asb_7-modified.zip)

Would that help? The sample assumes that you are using ForwardingTopology and that it is OK to create all required entities on both namespaces.

**Comment by SeanFeldman** [comment]
`MessageEndpointMappings` cannot be combined with some features in v7 of the transport (such as secured connection strings. Also, `MessageEndpointMappings` is gone from NSB v7.

**Comment by yvesgoeleven** [comment]
Suggestion, move RegisterPublisher down from EndpointOriented topology to routing and add additional connectionstring option

**Comment by yvesgoeleven** [comment]
Been discussing this capability with @danielmarbach and want to discuss it further during our sync today. Some concerns and thoughts have been raised that will influence the design (so ignore my api suggestion above)

concerns:

We should not blend logical & physical routing, RegisterPublisher is at the logical level and adding a connectionstring to it would blend this. Maybe better is to have a config method that allows user to specify that a logical endpoint, maps to a connectionstring outside the topo. e.g;
  `transport.NamespaceRouting().EndpointIsLocatedIn(endpointname, connectionstring or alias)`

Should this be considered a bug? or a new feature?

Do we want this capability for all topologies?

**Comment by yvesgoeleven** [comment]
We are only going to provide this for endpoint oriented topology as it was never available for forwarding to begin with.

**Comment by yvesgoeleven** [comment]
PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/624

**Comment by danielmarbach** [comment]
Closing via https://github.com/Particular/NServiceBus.AzureServiceBus/pull/624
