### ISSUE TITLE
Send to another namespace cumbersome

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#585]
Now that endpoint mappings is gone, ever send that occurs to an endpoint another namespace needs to pass in the namespace using `SendOptions`, there is no mapping anymore between type & namespace

Relates to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/586

**Comment by yvesgoeleven** [comment]
MessageEndpointMappings still exist, so can serve as workaround until we can add a new api for this

**Comment by SeanFeldman** [comment]
`MessageEndpointMappings` is deprecated in NSB v7.

**Comment by yvesgoeleven** [comment]
suggested API:

Additional overloads that accept a connectionstring

transport.Routing().RouteToEndpoint();

**Comment by danielmarbach** [comment]
@yvesgoeleven I'm tasked to get this started. I will start with it today or tomorrow depending on my schedule.

**Comment by yvesgoeleven** [comment]
@danielmarbach cool, I'll help as well

**Comment by yvesgoeleven** [comment]
Been discussing this capability with @danielmarbach and want to discuss it further during our sync today. Some concerns and thoughts have been raised that will influence the design (so ignore my api suggestion above)

concerns:

We should not blend logical & physical routing, RouteToEndpoint is at the logical level and adding a connectionstring to it would blend this. Maybe better is to have a config method that allows user to specify that a logical endpoint, maps to a connectionstring outside the topo. e.g;
  `transport.NamespaceRouting().EndpointIsLocatedIn(endpointname, connectionstring or alias)`

Should this be considered a bug? or a new feature?

**Comment by yvesgoeleven** [comment]
Implementation wise, I think looking up the endpoint to destination mapping belongs here (and not inside the topo)

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Sending/Batcher.cs#L34

**Comment by yvesgoeleven** [comment]
It was decided to go forward with send as described above, should be fairly easy to implement

**Comment by danielmarbach** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/pull/623

**Comment by yvesgoeleven** [comment]
Maybe add the send to the example after as well?

endpointInstance.Send(destination: "sales",   message: new MyMessage());

**Comment by danielmarbach** [comment]
Done

**Comment by SeanFeldman** [comment]
> Maybe add the send to the example after as well?

Are you referring to a sample?!
