### ISSUE TITLE
Respect MaxLockDuration when waiting for notifiers to shut down

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#589]
When `MessageReceiveNotifier.Stop()` is invoked, it waits for messages in flight to be processed for [30 seconds](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/21f24f43d16129b470ca5c7f5a8e937168e89c57/src/Transport/Receiving/MessageReceiverNotifier.cs#L114) before shutting down messaging infrastructure.  Since message lock duration can be configured to be up to 5 minutes, we should at least respect `MaxLockDuration` of the endpoint to ensure all messages in flight processing is allowed to be completed w/o interruption.

There's also a question about lock auto renewal. Challenge with that operation is that it's not guaranteed. We can discuss what to do about it. As a bare limit, we should respect lock duration config.

**Comment by yvesgoeleven** [comment]
The 30 seconds probably comes from the default wait time on shutdown that is allowed by NT services, extending it to MaxLockDuration would break this semantics. If not hosted in NT services, but in azure, then default shutdown behavior is 'kill'. Again, extending to MaxLockDuration makes little sense.
