### ISSUE TITLE
CircularBuffer may throw IndexOutOfRangeException

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#59]
Task force: @yvesgoeleven @seanfeldman

## Who's affected

Anyone who's using Azure Service Bus transports and using `Bus.Send()` or `Bus.Publish()` in a very tight loop with multiple threads.

## Symptoms

Due to a calculation error that can happen with concurrent access an `IndexOutOfRangeException` exception can be thrown

---

Reported in GG: https://groups.google.com/forum/#!topic/particularsoftware/a1GigfXhI94

[`CircularBuffer.Get()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Creation/Clients/CircularBuffer.cs#L166) is not thread safe and may throw exception when used in concurrent mode

Repro:
```c#
Parallel.ForEach(hugeArray, new ParallelOptions() { MaxDegreeOfParallelism = 5 }, item =>
{
    Bus.Send(new SomethingCommand
    {
        Item = item
    });
});
```

## Plan of attack

- [x] Make `CircularBuffer` thread safe
- [ ] Fix all support versions that qualify
- [ ] Release and make and announcement 
  - [ ] Google group
  - [ ] ASB customers

## Impact assessment

Customers must be using ASB transport and set concurrency > 1 (1 is the default).
Since we haven't heard back from a lot of customers till now and this is only specific to ASB transport, impact is `Small`.

## Customer communication

TBD

**Comment by tekmaven** [comment]
Thanks @SeanFeldman.  This issue is pretty severe and will lead to data loss, so I hope Particular prioritizes this.  Consider a simple WebApi controller that has a method only doing a single `Bus.Send()`.  If there are concurrent requests to the service (generally a common thing), this exception will be encountered and data will be lost.

**Comment by SeanFeldman** [comment]
@tekmaven we're looking into it and will be releasing a hotfix as soon as possible.
