### ISSUE TITLE
JsonSerializer removed from core vNext

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#591]
We are currently setting the JsonSerializer as the default serializer in https://github.com/Particular/NServiceBus.AzureServiceBus/blob/09c16d9f3fd2f7e9131e5b4862a81bd9d3bda682/src/Transport/Config/DefaultConfigurationValues.cs#L15

In Versions 7 and above of NServiceBus the JsonSerializer has been removed. Use the external [Json.NET Serializer](/nservicebus/serialization/newtonsoft.md) instead. See also [Compatibility between the core and external Json.NET serializer](/nservicebus/serialization/newtonsoft.md#compatibility-with-the-core-json-serializer).

**Comment by SeanFeldman** [comment]
Serialization is a mandatory setting and needs to be provided.
