### ISSUE TITLE
Headers do not contain entity full path when entities have hierarchy in its path

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#593]
When [hierarchy composition](https://docs.particular.net/transports/azure-service-bus/namespace-hierarchy) is used, entities can be prefixed with an additional segments in the path. For example, full path for a queue `queueA` that has a prefixed path of `production/tenant1/` would result in the full path `production/tenant1/queueA` for the queue to be identified and used for sends and receives.

When a message with an extended path is sent out, headers of the messages do not include the section of the path added by the hierarchy composition.  

![image](https://user-images.githubusercontent.com/1309622/28842405-cf75c670-76ba-11e7-95d8-c65fdf2e2a1e.png)

This could be an issue when a message needs to be replied and the receiver doesn't have the same hierarchy composition path added as the originator of the message. The message won't be sent to the proper destination and will fail.

**Comment by SeanFeldman** [comment]
**Update**

This issue would manifest itself in two scenarios:

1. Endpoints are misconfigured.
1. ServiceControl is used

First scenario would be identified and resolved during development. Therefore doesn't qualify as a bug.

Second scenario, a suitable workaround would be to use [Service Control adapter](https://docs.particular.net/servicecontrol/transport-adapter/) when composition with hierarchy is involved. (Needs to be confirmed, see PoA).

Unless proven differently, this is not a bug.

**Action Items**

- [ ] Verify SC Adapter can help with SC
  - [ ] Update SC Adapter for ASB [sample](https://docs.particular.net/samples/servicecontrol/adapter-asb-multi-namespace/)
  - [ ] Update [SC Adapter doco for ASB](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features#azure-service-bus) to list composition with hierarchy as another feature that requires adapter

**Comment by SeanFeldman** [comment]
@yvesgoeleven could you please add the history behind this feature being added to v7? Thanks.

**Comment by yvesgoeleven** [comment]
Hierarchies in ASB are used for security and management reasons, you can set up ADFS integration at different levels in the hierarchy.

E.g.

/production/myqueue1
/production/myqueue2
/development/myqueue1
/development/myqueue2

You can set different access levels at the production and development branches this way.

Assumption for this feature was indeed that all endpoints are configured with same hierarchy, as this is a security feature both would need the same custom tokenprovider as well.

Service control is still on the old transport, which does not support this new feature either.

**Comment by SeanFeldman** [comment]
Resolved by using SC adapter.
Documentation and samples PR sent to doco.
