### ISSUE TITLE
Use subscription entity metadata to avoid adding rules

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#597]
This is an idea I'm raising as part of the investigation for https://github.com/Particular/NServiceBus.AzureServiceBus/issues/592

As of now it is not possible to query rules that were added to a subscription. That's why the subscription creator has to add rules over and over again when the endpoint starts. This significantly contributes to the startup time of the endpoint. To improve the situation an issue was raised in the core to [concurrently subscribe](https://github.com/Particular/NServiceBus/issues/4897). While this certainly improves the situation a lot here is an idea which would potentially allow to be even faster when starting. 

Azure Entities can have a metadata property that is stored on the broker. The metadata property can have up to 2 KB in text in it. We could change the subscription creator the following way

When the subscription description is created use the metadata to encode the currently available rules (for example comma separated). Then we can query the subscription description for the broker and look up in the description whether the rules were already added (equality comparison would need to include this). When it is not already added then Add the rule and update the subscription description with the new metadata containing the rule. 

We currently allow users to override the subscription description factory. We would need to make sure we always append the information to the info that was already added by the customer (why are we exposing this seam anyway?)

**Comment by SeanFeldman** [comment]
Metadata is already [used](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs#L47) for subscriptions.

**Comment by SeanFeldman** [comment]
`UserMetadata` is limited to 1K. So that can't be it. @danielmarbach what property you're referring to?

**Comment by danielmarbach** [comment]
@SeanFeldman Yes it is used but it can be augmented. Since the information can be updated at will we can override it.

I refer to UserMetadata. I tested it on the standard tier and assigned new char('*', 1024) to it. A char has two bytes, therefore, we can assign 1024 * two bytes = 2048 bytes. Which is 2 KB. Thanks I made a calc mistake. Will correct. Still wouldn't that be enough to store the info?

**Comment by SeanFeldman** [comment]
There can be potentially up to 2K subscriptions per topic. With 2KB, that's a byte per subscription name.
Yes, an edge case, but need to account for that.

**Comment by danielmarbach** [comment]
Yeah, probably not worth pursuing then. Shall I close?

**Comment by SeanFeldman** [comment]
If there was no change on the Core side, I'd keep it. Since Core will
invoke subscriptions creation in parallel as of next hotfix, probably can
close it.

**Comment by yvesgoeleven** [comment]
Closing, reopen if needed
