### ISSUE TITLE
DescriptionFactory should have been renamed to DescriptionCustomizer on topic & subscription API

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#612]
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Tests/APIApprovals.ApproveAzureServiceBusTransport.approved.txt#L148

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Tests/APIApprovals.ApproveAzureServiceBusTransport.approved.txt#L165

**Comment by danielmarbach** [comment]
PR is merged. No milestone assignment since this doesn't need to be in the release notes. Closing
