### ISSUE TITLE
Things left that need to be deprecated

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#631]
https://github.com/Particular/NServiceBus.AzureServiceBus/search?utf8=%E2%9C%93&q=TODO%3A+needs+to+be+deprecated&type=

Should be fixed before v8

**Comment by SeanFeldman** [comment]
I can't recall the reason behind the decision to remove `ForwardDeadLetteredMessagesTo`.
@Particular/azure-maintainers anyone recalls what was it?

**Comment by yvesgoeleven** [comment]
Me neither

**Comment by yvesgoeleven** [comment]
Was it because we did not want people to forward poisonous messages to the error queue?

**Comment by SeanFeldman** [comment]
Can only guess at this point. Thinking about it now, we won't have anything, but poisonous message in DLQs since with versions 7 and up we are not deadletting on retries. So should we truly take this option away?

**Comment by SeanFeldman** [comment]
- Deprecate/Remove Express
- Leave ForwardDeadLetteredMessages
