### ISSUE TITLE
When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.Should_remove_subscription_rule_from_topology fails

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#632]
See https://github.com/Particular/NServiceBus.AzureServiceBus/pull/630#issuecomment-332786315

**Comment by SeanFeldman** [comment]
The [comment](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/630#issuecomment-332786315) was:
> I think that test is checking the backward compat when there happens to exist more entities in the bundle then what the topo has been configured for, that entity 'bundle-2' was probably created manually as the topology creator won't do it automatically. Should extend the test to create that entity if it does not exist (using a new instance of namespace manager)

Sounds correct.

**Comment by danielmarbach** [comment]
Fixed as part of 9fc815a447610335383aace857de935968957755
