### ISSUE TITLE
Transport doesn't accept connection strings with domain names other than servicebus.windows.net

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus.AzureServiceBus#662]
## Who's affected

Anyone using NServiceBus.Azure.Transports.WindowsAzureServiceBus transport version 7 and needs to connect to Azure Service Bus using domain other than `servicebus.windows.net`.

## Symptoms 

Exception is thrown.

## Original issue

The ConnectionString class uses a regex to verify the connection string:

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/171cda89df0554d7a65afb838623444e84e438e9/src/Transport/Topology/MetaModel/ConnectionString.cs#L11

This prevents the use of `NAME.servicebus.usgovcloudapi.net` in the connection string.

**Comment by SeanFeldman** [comment]
This fix will be backported.

**Comment by yvesgoeleven** [comment]
are there any other domains like usgovcloudapi?

**Comment by SeanFeldman** [comment]
Yes. https://github.com/Azure/azure-service-bus/issues/111

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/5bd132f256ee52108e25a0fb7546755cd9530658
