### ISSUE TITLE
One subscription with multiple rules failes to create correctly on endpoint startup

### ISSUE THREAD

**Issue by jgoyvaerts** [Particular/NServiceBus.AzureServiceBus#667]
As is:
When an endpoint is configured with forwarding topology with one entity in the bundle, you would expect the endresult to be 1 bundle with 1 subscription with multiple rules (one rule per event).

However, what seems to be happening is there are multiple calls (one for each event) to Task<SubscriptionDescription> Create in AzureServiceBusForwardingSubscriptionCreator.cs. One of the calls creates the subscription, and the other ones receive a MessagingEntityAlreadyExistsException with "the subscription already exists". However, these calls don't add the rule anymore, making the end result be 1 bundle with 1 subscription with 1 rule.

When I restart the endpoint for a second time, the subscription already exists, and the missing rules are added.

Am I missing something in configuration, or is 
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/db4a1d9ca44f59e6d95f47368e3716826abf4d14/src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs#L94-L98
missing the code to add the rule when the subscription already exists? Like here:
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/db4a1d9ca44f59e6d95f47368e3716826abf4d14/src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs#L77-L91

**Comment by yvesgoeleven** [comment]
@jgoyvaerts sounds like a concurrency bug on our end, I will investigate. Thanks for reporting

**Comment by yvesgoeleven** [comment]
If this line is called concurrently

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/db4a1d9ca44f59e6d95f47368e3716826abf4d14/src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs#L58

and the second call would throw it would indeed be considered finished and not add the rule (until restarted)

**Comment by yvesgoeleven** [comment]
@jgoyvaerts what version of nservicebus and transport are you using?

**Comment by jgoyvaerts** [comment]
@yvesgoeleven Nservicebus 6.4.2,  Transports.WindowsAzureServiceBus 7.2.6

**Comment by boblangley** [comment]
@jgoyvaerts We have released [NServiceBus.Azure.Transports.WindowsAzureServiceBus 7.2.9](https://www.nuget.org/packages/NServiceBus.Azure.Transports.WindowsAzureServiceBus/7.2.9) that addresses this issue.
