### ISSUE TITLE
Message Replay after commit when sending more than 100 to ASB

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#670]
Originally raised by Carl Berisford Murray https://discuss.particular.net/t/message-replay-after-commit-when-sending-more-than-100-to-asb/163

> Hi
> This is now no longer a critical bug, but something that probably requires looking into or a great big disclaimer somewhere.
> 
> I left some debugging code in a handler that was sending more than 100 messages in the production system. What I would have expected would be for the entire handler transaction to fail, but it commited the database changes as expected, and then replayed the message again (and again a few times before I could stop it).
> 
> There is a danger message about the maximum size of a message, but not about the number of messages.

**Comment by SeanFeldman** [comment]
I've left a detailed [comment at Discuss](https://discuss.particular.net/t/message-replay-after-commit-when-sending-more-than-100-to-asb/163/3).

**Comment by carlbm** [comment]
I don't know enough about the intricacies of NSB, but what is the reason that the transport transaction is not finished before the business transaction is committed?

And is there a way to make a message fail if it fails on the transport rather than having it retried?

**Comment by danielmarbach** [comment]
@carlbm SendsWithAtomicReceive is achieved on the broker by using a feature called Send-Via. The trick is essentially that all outgoing messages are attached to the incoming message with a special header that indicates where the messages need to go to. Only when the incoming message is marked as successfully completed the messages are then sent by the broker behind the scenes to the destination queues. 

Since the message is the thing that triggers your business logic in the handler the business logic completes first (to determine the outcome) and only if that was successful only then the message transaction is completed since this is less likely to fail.

**Comment by SeanFeldman** [comment]
@carlbm please review [ASB's official documentation on transactions](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions).

Given the transport is working as expected, I'm going to close the issue.
If you think it still needs to remain opened, please let know. Thank you.
