### ISSUE TITLE
Topic generation can go awry

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#675]
The function DetermineTopicsToCreate

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs#L50

uses BundleConfigurations.GetNumberOfTopicInBundle, which simply counts the number of topics that start with prefix "bundle-"

And then generates n number of entities "bundle-"+ i where i is a number

if there is a topic where i is not a number, e.g. bundle-x,  this will result in a new topic created with a number attached incrementing the number of topics every time the endpoint start.

Example

bundle-1, bundle-2, bundle-X -> 3 topics to create, resulting in
bundle-1, bundle-2, bundle-3, bundle-X -> 4 topics to create
bundle-1, bundle-2, bundle-3, bundle-4, bundle-X -> 5 topics to create, 
etc...

**Comment by SeanFeldman** [comment]
This is an edge case for sure. Does it deserve a patch though?

**Comment by SeanFeldman** [comment]
![image](https://user-images.githubusercontent.com/1309622/33134145-3433475a-cf5c-11e7-839b-f4a7edeade7c.png)

**Comment by jgoyvaerts** [comment]
@SeanFeldman @yvesgoeleven 
When is this fix being backported to 7.2.9 branch and being released to nuget?

We're running into this issue and we'd like to have it resolved before moving ahead with our next release cycle.

Thanks in advance!

**Comment by yvesgoeleven** [comment]
@jgoyvaerts where did the other 'bundle-' topic come from in your case?

**Comment by SeanFeldman** [comment]
@jgoyvaerts it will be released as part of 7.2.10.
I'll add an update here with a an issue to track.

**Comment by jgoyvaerts** [comment]
@yvesgoeleven servicepulse was using companyname.productname.xxx which was causing the issue with our chose topic name companyname.productname. We changed our topic name to productname as a workaround for now

**Comment by yvesgoeleven** [comment]
@jgoyvaerts so you changed the bundle prefix to companyname.productname ?

**Comment by jgoyvaerts** [comment]
@yvesgoeleven No now our topic is just called productname-1 so we don't run into the issue anymore.
The servicepulse topic is still called companyname.productname.xxx

**Comment by SeanFeldman** [comment]
@jgoyvaerts the issue with topics would manifest itself only if you'd have `bundle-<anything>` topics.

**Comment by jgoyvaerts** [comment]
Maybe I misread the issue.
The behavior we're seeing, which we've been able to reproduce 100% of the time :
Have a preexisting topic a.b or a.b.xxx
Start multiple endpoints at the same time, all with forwarding topology and the same topicname a.b (which should result in the creation of one topic a.b-1)
Observe that more than one topic will have been created, sometimes 2, sometimes 3 (so also a race condition maybe?): a.b-1 and a.b-2
If we restart those endpoints without deleting any topics even more topics will be created.

**Comment by SeanFeldman** [comment]
Ah, you must have override the bundle name.
https://docs.particular.net/transports/azure-service-bus/topologies/

**Comment by jgoyvaerts** [comment]
@SeanFeldman I'm confused.
This is our setting:

`var forwardingTopology = transport.UseForwardingTopology();
            forwardingTopology.BundlePrefix("CompanyName.ProductName");
            forwardingTopology.NumberOfEntitiesInBundle(1);`
We have a preexisting topic for servicecontrol called: "CompanyName.ProductName.sc.debug"
When we launch multiple endpoints at the same time with the above forwardingtopology settings, the end result is the following topics:

- CompanyName.ProductName.sc.debug
- CompanyName.ProductName-1
- CompanyName.ProductName-2
(and sometimes -CompanyName.ProductName-3)

If we were to restart the endpoints, we would end up with even more topics with incrementing numbers.

I think this is a clear bug and not intended behavior?

**Comment by yvesgoeleven** [comment]
@jgoyvaerts yes, that is the bug that will be fixed by this patch

**Comment by jgoyvaerts** [comment]
Cool thanks!

**Comment by SeanFeldman** [comment]
> Ah, you must have override the bundle name.

Sorry, what I meant is that you must have overriden the _default_ bundle prefix ("`bundle`") with a custom value, which you have confirmed.

`forwardingTopology.BundlePrefix("CompanyName.ProductName"); `

**Comment by SeanFeldman** [comment]
@jgoyvaerts the issue for version 7 of the transport is #683.
You can subscribe to get notified when it's merged and released.
