### ISSUE TITLE
Deprecated bundle prefix API could break customers that rely on this functionality

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#682]
Customers using ASB v7 transport [override bundle prefix](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/675#issuecomment-346963567). [Obsoleted API](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/a5abfb0ede4224e02686b7a323a99316fe2dd2f2/src/Transport/obsoletes.cs#L84) will mean their code will be broken. We need to review the decision to obsolete and deprecated this API.

**Comment by SeanFeldman** [comment]
@jgoyvaerts could you please provide an insight what was the reason to [customize bundle prefix](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/675#issuecomment-346963567) for endpoint(s) in your solution? Thank you.

**Comment by jgoyvaerts** [comment]
@SeanFeldman I think at some point we found a configuration sample which used the bundle prefix, or we checked out the available configuration APIs and found it ourselves. Not sure, never really thought about it too much.

Wasn't aware it was being deprecated

**Comment by jgoyvaerts** [comment]
@SeanFeldman Will there be a way in the future to rename the bundle? This way we can separate completely different applications on the same service bus.

**Comment by danielmarbach** [comment]
@jgoyvaerts would something like suit your need?

https://docs.particular.net/transports/azure-service-bus/namespace-hierarchy

**Comment by danielmarbach** [comment]
That is the reason you want to let multiple applications run on the same namespace and not have dedicated namespaces per application?

**Comment by SeanFeldman** [comment]
> This way we can separate completely different applications on the same service bus.

To completely separate applications on ASB, have you considered using different namespaces?
You don't really segregate applications if you just use different entities. The combined workload is going to affect them all. From a namespace perspective you won't have more than N sas tokens for management (I think it's 6). Have you considered running each app on its own namespace @jgoyvaerts ?

**Comment by SeanFeldman** [comment]
Maintainers have discussed this and we've concluded this API needs to be brought back in v8.

**Comment by yvesgoeleven** [comment]
I've put the configuration method back, https://github.com/Particular/NServiceBus.AzureServiceBus/commit/32f80672fd4dd925a236eff3d6d47008ad6eab13
