### ISSUE TITLE
Abililty to correlate ASB MessageId & NSB MessageId

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#685]
Because https://github.com/Particular/NServiceBus.AzureServiceBus/issues/201, the ASB MessageId and NSB MessageId have been decoupled. The ASB MessageId is a random guid now.

But customer indicates that some of their operational processes rely on the fact that these values used to be the same (or at least correlatable).

Provide a way to correlate these, without reintroducing https://github.com/Particular/NServiceBus.AzureServiceBus/issues/201

**Comment by yvesgoeleven** [comment]
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs#L31

Options:

* Custom implementation of IConvertOutgoingMessagesToBrokeredMessages
* Provide a callback at this point
* Prefix the generated id with the outgoing message id

**Comment by SeanFeldman** [comment]
> Prefix the generated id with the outgoing message id

@yvesgoeleven  did you mean "...outgoing **NserviceBus** message id"?

**Comment by SeanFeldman** [comment]
Awaiting for more details before we can discuss this.

**Comment by SeanFeldman** [comment]
Closing. Please re-open if this is still a problem.
