### ISSUE TITLE
Allow connection string to be without credentials for custom STS

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#686]
## Who's affected

Customers trying to use a custom Security Token Service to secure their Azure Service Bus namespace

## Symptoms

The connectionstring validation does not allow the format “Endpoint=sb://[namespace name].servicebus.windows.net/” without credentials.

- [x] Fix v7 [PR](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/689)
- [x] Port to ASB v8
- [x] Announcement [PR](https://github.com/Particular/Announcements/pull/208)

**Comment by yvesgoeleven** [comment]
This probably boils down to making the second part in the regex optional: https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Topology/MetaModel/ConnectionString.cs#L11

**Comment by SeanFeldman** [comment]
> This probably boils down to making the second part in the regex optional:

This would be a breaking change as we use namespace name, SAS key and SAS token for [equality](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e8c61ff128d70e28aed7bdffddf5e4175324c9df/src/Transport/Topology/MetaModel/ConnectionString.cs#L49-L55).

**Comment by yvesgoeleven** [comment]
@SeanFeldman it would just need a null check, but it would not break the equality logic. A connectionstring without key would not be equal to one with key.

**Comment by SeanFeldman** [comment]
Is there any doco update that would be required as a result of this change?

**Comment by SeanFeldman** [comment]
Classification is missing (`Feature` or `Bug`)

**Comment by yvesgoeleven** [comment]
> Is there any doco update that would be required as a result of this change?

No, we have no doco about connectionstring formats

**Comment by yvesgoeleven** [comment]
Announcement drafted https://github.com/Particular/Announcements/pull/208

**Comment by SeanFeldman** [comment]
> No, we have no doco about connectionstring formats

Should we? This is a very advanced scenario, and custom, that's why I'm not sure if we should or not.
