### ISSUE TITLE
Guarding against unset serializer

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#693]
When default (JSON) serializer got removed from the ASB transport ([PR link](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/615)), a [guard was added](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/8fd857f5582995943e643d7d2a5ee27d032d1457/src/Transport/Utils/Guard.cs#L41) to ensure users set some serializer with a hint to use `NServiceBus.Newtonsoft`.

The challenge with this guard is that transport should not have any saying in the serialization used by endpoints. This is causing an issue in scenarios such as [SC Transport Adapter](https://github.com/Particular/ServiceControl.TransportAdapter/issues/22), where this guard is preventing from the adapter to execute. [Sample for ASB SC transport adapter and NServiceBus v7](https://github.com/Particular/docs.particular.net/pull/3511) has surfaced this issue.

~~Potential resolution would be to look into removing the check for serializer from the transport to make it serialization agnostic for major release version 8 as this would be a breaking change and would require testing on the users side to be caught.~~

Give this needs to be resolved for RC of NServiceBus 7, @Particular/azure-maintainers let's discuss in our  sync. Thanks.

**Update**: 
A [third option](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/693#issuecomment-351495275) was introduced, discussed, and agreed upon. The change will target 8.0.0 RC.

### PoA
- [x] Discuss with Azure maintainers
- ~~Open an issue with DotNetCoreLaunchWave~~ - not required. Will be handled as part of RC work.
- [ ] Make changes against **`release-8.0.0` branch** (not `develop`)
- [ ] Update documentation / samples / upgrade guide

**Comment by yvesgoeleven** [comment]
Removing that guard would be far worse, then regular endpoints would suddenly start running with xml serializer as core still defaults to that

**Comment by SeanFeldman** [comment]
A blast from the past.
Given we're taking about major release, this is an opportunity to stop the incorrect behavior and address it. The transport should have no business in serialization, wouldn't you agree? And that a major upgrade would require retesting. Would you agree to that? 

We need to discuss it as it's breaking SC transport adapter. Either way, it will not be a win win for all. I'll keep away from commenting until all maintainers have a chance to voice their thoughts.

**Comment by yvesgoeleven** [comment]
Besides removing the check unconditionally, we could also add an opt-in 'NoSerializer()' configuration method that can be used from the bridge and turns the check off. This way upgrades of existing endpoints would not magically default to xml, which I consider breaking wire compatibility, and the bridge would still work.

**Comment by SeanFeldman** [comment]
[Assumption at the time](https://github.com/Particular/PlatformDevelopment/issues/1378) was made that Core should not have a default serializer. This is too much of a breaking change for all ASB customers. Therefore [suggested approach](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/693#issuecomment-351329083) is the one Azure maintainers want to go with.

**Comment by SeanFeldman** [comment]
We've discussed 2 options so far, but there's also a third option that could be a middle ground for now. Let me re-iterate the options and add a new one.

1. **Remove the check for default serializer**. This would be still a breaking change. Just like the exception thrown now as part of the check. Difference is that w/o throwing an exception it would not be as simple to identify and address serializer problem as with exception thrown at the startup time.
2. **Require SC Transport Adapter to allow serialization related API**. This would also require changes in `NServiceBus.Raw` and not ideal as it would be a setting to satisfy ASB transport solely.
3. **Take a dependency on `Particular.Newtonsoft` package and remove the check until Core removed the default serializer**. This is what the transport used to do until Core v7. It was setting the **default** serialization (internal to Core), allowing customers to override it. With this approach, we're not throwing any exceptions, we're wire compatible by default (`JSON`) for the existing ASB customers that are accustomed to this way of things working, _and_ do not require any ASB-specific modifications to SC transport adapter/`NServiceBus.Raw`. We can re-evaluate this approach with when Core decides on the future of default serializer.

Option #3 sounds like a viable "middle ground" until Core seam and `NServiceBus.Raw` items are sorted out.

@Particular/azure-maintainers can I please get your full name, address, and a signature at the bottom? Or just thumb it up. Thanks.

**Comment by yvesgoeleven** [comment]
@SeanFeldman I'm fine with going back to the old model (option 3)

**Comment by boblangley** [comment]
Option 3 is the most explicit. 👍

**Comment by danielmarbach** [comment]
We discussed option 3 before we came up with the current approach. I
remember that we argued that the indirect coupling to another dependency
that depends on Newtonsoft could be problematic since ASP uses Newtonsoft
as well. Another reason why we went with the current approach was also that
we wanted users to read the compatibility guide and choose a suitable
serializer that the restrictions of Azure.

I'm not against option 3. I want to outline the reasons that lead to the
current behavior

Am 13.12.2017 20:45 schrieb "Bob Langley" <notifications@github.com>:

**Comment by SeanFeldman** [comment]
Thank you @danielmarbach 
You're 100% correct about shared dependency on Newtonsoft and explicit selection of serializer rather than transport continue doing it for the users. For the current situation it seems like the best compromise we could get w/o forcing any side into painful changes. From customers perspective, this would be same as before. We would need to address it with the next major of Core though, lobbying for Core to drop default serialization.

With that, we have an agreement that this can move into `Ready` and target 8.0.0 RC.

**Comment by danielmarbach** [comment]
We discussed this again in the maintainer sync and we think we should make another attempt to address this from a core perspective since the compromise has consequences for the maintainability of the transport as well as for customers that don't want to use the json serializer (another dependency that gets pulled in over and over again). 

Moved to blocked state for now. I will initiate another conversation with the core launch.

**Comment by SeanFeldman** [comment]
Conclusion ATM is to register a fake default serializer in the SC Transport Adapter rather than removing the guard.

```c#
var settings = transport.GetSettings();
var serializer = Tuple.Create(new FakeSerializer() as SerializationDefinition, new SettingsHolder());
settings.Set("MainSerializer", serializer);
```
Closing.
