### ISSUE TITLE
HierarchyComposition PathGenerator applied multiple times

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.AzureServiceBus#695]
Raised by @SzymonPobiega 

When applying `HierarchyComposition` the path generator is applied two times and since the composition strategy is not idempotent incorrect paths are generated.

Sample

```
transport.Composition().UseStrategy<HierarchyComposition>().PathGenerator(path => "scadapter/");
```

leads to `scadapter/scadapter/EntityPath` queue name instead of `scadapter/EntityPath` queue name

### Analysis

When [we fixed](https://github.com/Particular/NServiceBus.AzureServiceBus/commit/0efd41c0903c90c66af8d43aadd1ffb90d4aa425) the `ToTransportAddress` implementation we talked about the effects on the strategies and that the strategies should be idempotent. Since we don't have a test for the hierarchy composition strategy we didn't realize that the hierarchy composition strategy is not. This the core calls `ToTransportAddress` which uses the address generator and the composition strategy to resolve the entity path. That new path is passed into `DetermineSendRessources` which then applies the address generator again leading to incorrect paths.

Composition strategies and address generation should be idempotent
Question is whether DetermineSend destination really needs to reapply the address generation.

## PoA

- [x] Fix in `release-8.0` (PR #696)
- [x] Update [Composition doco](https://docs.particular.net/transports/azure-service-bus/configuration/full#physical-addressing-logic-composition) (docs PR https://github.com/Particular/docs.particular.net/pull/3563)

**Comment by yvesgoeleven** [comment]
> Composition strategies and address generation should be idempotent

Should we document this? or enforce it ourselves by ensuring it's called only once in the code path (or checking if it was called before)?

**Comment by SeanFeldman** [comment]
Additional problem with `AddressingLogic` is that it's used to build up topology and also during dispatch.

- When building a topology, we can cache results produced by `AddressingLogic` to avoid nested paths creation.
- When dispatching messages, we can validate that the destination used has a suffix (`@alias` or `@connectionString`) and skip `AddressingLogic` processing.

**Comment by danielmarbach** [comment]
@SeanFeldman what if the path prefix of the HierarchyComposition strategy is also very long? Or are we saying that is not an allowed scenario and the prefix chosen by the composition strategy should always be human readable?

**Comment by SeanFeldman** [comment]
> what if the path prefix of the HierarchyComposition strategy is also very long? Or are we saying that is not an allowed scenario and the prefix chosen by the composition strategy should always be human readable?

That's exactly the issue @danielmarbach. The definition of the prefix is not clear and as it works right now, would be included in the total path and sanitized, rather than being human readable.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/cff5f81cb876fc02bfe76dcc4a7da006c5f2467a
