### ISSUE TITLE
Slow initial pickup of messages

### ISSUE THREAD

**Issue by jgoyvaerts** [Particular/NServiceBus.AzureServiceBus#701]
**Situation**
- Endpoint is running, queue is empty
- Messages get queued (by send only endpoint in a webapp), messages appear on queue (can be verified with Servicebus Explorer).

**Problem**
After the messages get queued, they sit there for several seconds (up to 10-15 seconds) before being picked up by the endpoint. After the initial message is picked up, the rest of the messages is picked up as soon as the previous one is completed. 

However, because of this initial "delay", clients perceive our application as "slow". Is there something we can do configuration wise to combat this initial delay? Is it a bug, an idle time, a configuration setting?

Endpoint is running with
```
transport.NumberOfClientsPerEntity(1);
configuration.LimitMessageProcessingConcurrencyTo(1);
```

Any help would be appreciated!

**Comment by yvesgoeleven** [comment]
What you see here is a 'feature' of the ServiceBus SDK, it's called ServerWaitTime, which keeps a connection open for this amount of time if there are no messages and batches up messages that come in in this time before actually receiving it. Sadly enough we cannot control it, through the API we are using internally, the SDK hardcodes it to the DefaultOperationTimeout which equates to 60 seconds.

The perceived performance might improve if you increase the number of clients and concurrency though, then each receiver has a 60 second server wait time, but they might have started at a different moment so the first one to pick up a message will be faster.

On a second note, I think you have a design issue here. A queue can have any length, your processing concurrency is very limited, so it is very likely for a message to be in that queue for a long time if traffic ramps up. Your UI should be designed in such a way that the user isn't expecting a result in a few seconds.

**Comment by jgoyvaerts** [comment]
We also notice the issue with multiple clients and concurrency, since they all startup at the same time, I was just trying to simplify the erroneous behavior.

It's not a design issue I'm worried about (our users perfectly know the action they're performing is non-instant), it's the fact that an action which should take 1 second with no other load on the system is taking 10-15 seconds that is bothering me.

**Comment by yvesgoeleven** [comment]
On startup with nothing in the queue they are indeed likely to wait equally long. I wish we could control this for you, but we can't.

Here is the decompiled code from the ASB SDK, as you can see the value is set in the constructor and the field accessor is internal, so we cannot provide a config option to control it.

```
  /// <summary>Provides options associated with message pump processing using
  /// <see cref="M:Microsoft.ServiceBus.Messaging.QueueClient.OnMessage(System.Action{Microsoft.ServiceBus.Messaging.BrokeredMessage})" /> and
  /// <see cref="M:Microsoft.ServiceBus.Messaging.SubscriptionClient.OnMessage(System.Action{Microsoft.ServiceBus.Messaging.BrokeredMessage})" />.</summary>
  public sealed class OnMessageOptions
  {
    private int maxConcurrentCalls;
    private TimeSpan autoRenewTimeout;

    /// <summary>Initializes a new instance of the <see cref="T:Microsoft.ServiceBus.Messaging.OnMessageOptions" /> class.</summary>
    public OnMessageOptions()
    {
      this.MaxConcurrentCalls = 1;
      this.AutoComplete = true;
      this.ReceiveTimeOut = Constants.DefaultOperationTimeout;
      this.AutoRenewTimeout = Constants.ClientPumpRenewLockTimeout;
    }

    /// <summary>Gets or sets the maximum number of concurrent calls to the callback the message pump should initiate.</summary>
    /// <value>The maximum number of concurrent calls to the callback.</value>
    public int MaxConcurrentCalls
    {
      get
      {
        return this.maxConcurrentCalls;
      }
      set
      {
        if (value <= 0)
          throw new ArgumentOutOfRangeException(SRClient.MaxConcurrentCallsMustBeGreaterThanZero((object) value));
        this.maxConcurrentCalls = value;
      }
    }

    /// <summary>Gets or sets a value that indicates whether the message-pump should call
    /// <see cref="M:Microsoft.ServiceBus.Messaging.QueueClient.Complete(System.Guid)" /> or
    /// <see cref="M:Microsoft.ServiceBus.Messaging.SubscriptionClient.Complete(System.Guid)" /> on messages after the callback has completed processing.</summary>
    /// <value>true to complete the message processing automatically on successful execution of the operation; otherwise, false.</value>
    public bool AutoComplete { get; set; }

    internal bool AutoRenewLock
    {
      get
      {
        return this.AutoRenewTimeout > TimeSpan.Zero;
      }
    }

    /// <summary>Gets or sets the maximum duration within which the lock will be renewed automatically. This
    /// value should be greater than the longest message lock duration; for example, the LockDuration Property. </summary>
    /// <value>The maximum duration during which locks are automatically renewed. The default value is 5 minutes, and if you
    /// set this value to <see cref="F:System.TimeSpan.Zero" /> the lock will not be automatically renewed.</value>
    public TimeSpan AutoRenewTimeout
    {
      get
      {
        return this.autoRenewTimeout;
      }
      set
      {
        TimeoutHelper.ThrowIfNegativeArgument(value, nameof (value));
        this.autoRenewTimeout = value;
      }
    }

    /// <summary>Occurs when an exception is received. Enables you to be notified of any errors encountered by the message pump.
    /// When errors are received calls will automatically be retried, so this is informational. </summary>
    public event EventHandler<ExceptionReceivedEventArgs> ExceptionReceived;

    internal ClientEntity MessageClientEntity { get; set; }

    internal TimeSpan ReceiveTimeOut { get; set; }

    internal void RaiseExceptionReceived(ExceptionReceivedEventArgs e)
    {
      // ISSUE: reference to a compiler-generated field
      EventHandler<ExceptionReceivedEventArgs> exceptionReceived = this.ExceptionReceived;
      if (exceptionReceived == null)
        return;
      exceptionReceived((object) this.MessageClientEntity, e);
    }
  }```

**Comment by jgoyvaerts** [comment]
I understand the problem of not accessing or modifying the value, however it's still unclear to me why we would be waiting for a timeout if there is a message available.

1 endpoint with 1 client with 1 concurrency with prefetchcount 0 should not need to wait for "batching up messages that come in at this time" since our batchsize is 1 (== prefetchcount?) and there is a message available on the queue

**Comment by yvesgoeleven** [comment]
You are absolutely right ofcourse, it makes no sense in your configuration, but the only people that can answer this question are the designers of the ASB SDK. I see no reason why this setting isn't exposed myself.

**Comment by SeanFeldman** [comment]
A few points:

1. The 1 minutes `ReceiveTimeOut` is a part of long-polling implementation. It doesn't influence the time it takes to receive first message. What it does is waiting for the server to send a message for a minute. If nothing is sent by the server, the client will send a new request to receive messages. The value of 1 minutes is set by the Azure Service Bus team and is internal. If you'd like to dispute that decision for the given client, feel free to raise an issue at https://github.com/Azure/azure-service-bus/issues.
1. Same behaviour is found with the new client, where message pump is requesting a message from the broker and [waits for 1 minute to retrieve a message](https://github.com/Azure/azure-service-bus-dotnet/blob/1db236d5bb98595e951413989c3da38c6bdf8c8f/src/Microsoft.Azure.ServiceBus/MessageReceivePump.cs#L64). If no message is retrieved, a new request is issued. You can trace 1 minute value from [`MessageHandlerOptions`](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/MessageHandlerOptions.cs) set to the [`Constants.DefaultOperationTimeout`](https://github.com/Azure/azure-service-bus-dotnet/blob/1db236d5bb98595e951413989c3da38c6bdf8c8f/src/Microsoft.Azure.ServiceBus/Constants.cs#L30) constant. Which is like the current/old client is 1 minute.

At this point I'm not convinced that the described delay of 10-15 seconds is solely to be associated with how internal ASB client pump is retrieving messages @yvesgoeleven.

**Comment by yvesgoeleven** [comment]
@SeanFeldman I'm fairly certain, I ran into this with the MH client as well. That's why these slowdown and speedup methods are built on the serverwaittime variable https://github.com/MessageHandler/MessageHandler.Runtime.EventProcessing/blob/master/src/receiving.servicebus/MessageReceiverPump.cs#L107 and it uses the receiveasync api instead of the onmessage one.  The broker actually waits when initially there is no message.
