### ISSUE TITLE
Support application/octed-stream side by side with the current application/octect-stream

### ISSUE THREAD

**Issue by johnm123** [Particular/NServiceBus.AzureServiceBus#707]
At the risk of sounding like a pedant, is this a typo? If the header is used by a non NSB consumer expecting it to be the conventional "application/octet-stream" this could perhaps cause problems.

In the documentation (https://docs.particular.net/transports/azure-service-bus/brokered-message-creation) it is referred to as "application/octect-stream". In the code, (BrokeredMessagesToIncomingMessagesConverter.cs) it is referred to in the method below: 

` static string GetDefaultTransportEncoding(ReadOnlySettings settings)
{
            var configuredDefault = settings.Get<SupportedBrokeredMessageBodyTypes> WellKnownConfigurationKeys.Serialization.BrokeredMessageBodyType);
            return configuredDefault == SupportedBrokeredMessageBodyTypes.ByteArray ? "wcf/byte-array" : "application/octect-stream";
        }`

**Comment by yvesgoeleven** [comment]
This is a typo indeed, thanks for reporting @johnm123

**Comment by SeanFeldman** [comment]
It could be fixed for incoming messages to support native integration scenario that use a proper message type (`"application/octet-stream"), but not for the outgoing messages. Outgoing messages could be dispatched to the older endpoints that are not updated and it would be a breaking change.

@johnm123 @asosricharde is this a blocker for you?

**Comment by johnm123** [comment]
Thanks for the replies. @SeanFeldman Yes, I understand fixing it would break compatibility with earlier versions that are expecting the typo to be there. Anyhow, I don't think it's a blocker for us as the non-NSB consumers can assume the content to be a stream type.

**Comment by johnm123** [comment]
Hi Sean,

Thanks for the message, makes sense. I would be happy to do it if this is any help.

**Comment by SeanFeldman** [comment]
@johnm123 you're not expected, but sure you can 😃

For this to work, we need to ensure that both values are accepted for streams in the [`BrokeredMessagesToIncomingMessagesConverter`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/8c7ef11e911c5718dfe2f2ad663006e72f585617/src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs#L47). To verify it's still working, you could add a [test](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/8c7ef11e911c5718dfe2f2ad663006e72f585617/src/Tests/Receiving/When_converting_brokered_messages_to_incoming_messages.cs#L157).

**Comment by johnm123** [comment]
@SeanFeldman have issued a PR... Change is covered by a test, hope this is okay.

**Comment by SeanFeldman** [comment]
Thank you @johnm123.
There's an edge case for native-integrations I'll have to look into to determine if this approach is not going to break backwards compatibility.

**Comment by SeanFeldman** [comment]
Thank you @johnm123 🙂

**Comment by SeanFeldman** [comment]
Fix merged into `develop` and will be released with the next minor.

**Comment by danielmarbach** [comment]
We are about to release 8.0.1. This is a useful and non-breaking addition that can go in 8.0.1 without any risk.
