### ISSUE TITLE
Missing MessageIntent prevents transport from handling message

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.AzureServiceBus#718]
## Who's affected

Customers injecting messages into AzureServiceBus containing no message intent (for example when doing integration)

## Symptoms

When a message is received without a Message Intent property on it, an exception is thrown as the transport tries to convert to an NServiceBus Transport Message. This prevents the message from making it to NServiceBus.

[The code assumes the intent property is present as long as any properties are present](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/support-6.4/src/Transport/Utils/BrokeredMessageConverter.cs#L28)

**Comment by danielmarbach** [comment]
Fixed with https://github.com/Particular/NServiceBus.AzureServiceBus/pull/719. Closing
