### ISSUE TITLE
"NServiceBus.Azure.Transports.WindowsAzureServiceBus" version="8.0.0" doesn't respect RecoverabilitySettings it takes int.MaxValue

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus.AzureServiceBus#723]
When configuring an endpoint with 

```
var recoverabilitySettings = configuration.Recoverability();
recoverabilitySettings.Immediate(immidiate => immidiate.NumberOfRetries(2));
recoverabilitySettings.Delayed(delayed => delayed.NumberOfRetries(1));
```
Then Max Delivery Count isn't set to the correct number. It's set to int.MaxValue

![image](https://user-images.githubusercontent.com/19533149/42577511-c7e602de-8524-11e8-8a98-7b23aeacc866.png)

**Comment by SeanFeldman** [comment]
@JSCProjects as of version 8 `MaxDeliveryCount` is decoupled from the recoverability. Recoverability is tracked by NServiceBus and `MaxDeliveryCount` is set to the maximum to avoid accidental ded-lettering. 

Please re-send the issue in case you ran into a bug with this. Thanks.

**Comment by SeanFeldman** [comment]
**Update**: followed up with @JSCProjects over twitter - the issue stems from the state of the ASB namespace where entity is exceeding its max size. That causes all sorts of abnormal behaviour with ASB and affects message transfers. Fix - bring ASB entities under max size.
