### ISSUE TITLE
Upgrading CustomConfigurationSource from NserviceBus 5 to 7

### ISSUE THREAD

**Issue by ashokchebrolu** [Particular/NServiceBus.AzureServiceBus#736]
Hi All,
I am working on upgrading NserviceBus 5 to 7. In need to upgrade , I have upgrade **CustomConfigurationSource (new BusConfigurationSource());**

This is how **BusConfigurationSource** class look like

```c#
public override string ToString()
{
    var sb = new StringBuilder();
    sb.AppendFormat("\n{0} Configuration Information\n", Assembly.GetExecutingAssembly().GetName());
    var unicastBusConfig = GetServiceBusConfig<UnicastBusConfig>();
    if (unicastBusConfig != null)
    {
        sb.Append("UnicastBusConfig\n");

        sb.AppendFormat(
            string.IsNullOrEmpty(unicastBusConfig.DistributorControlAddress)
                ? string.Empty
                : "    DistributorControlAddress: {0}\n",
            unicastBusConfig.DistributorControlAddress);

        sb.AppendFormat(
            string.IsNullOrEmpty(unicastBusConfig.DistributorDataAddress)
                ? string.Empty
                : "    DistributorDataAddress: {0}\n",
            unicastBusConfig.DistributorDataAddress);

        foreach (MessageEndpointMapping mapping in unicastBusConfig.MessageEndpointMappings)
        {
            sb.AppendFormat("    {0} Messages mapped to {1}\n", mapping.Messages, mapping.Endpoint);
        }
    }

    MessageForwardingInCaseOfFaultConfig faultConfig = GetServiceBusConfig<MessageForwardingInCaseOfFaultConfig>();
    if (faultConfig != null)
    {
        sb.Append("MessageForwardingInCaseOfFaultConfig\n");
        sb.AppendFormat("     ErrorQueue: {0}\n", faultConfig.ErrorQueue);
    }

    var transportConfig = GetServiceBusConfig<TransportConfig>();
    if (transportConfig != null)
    {
        sb.Append("TransportConfig\n");
        sb.AppendFormat("    NumberOfWorkerThreads: {0}\n", transportConfig.MaximumConcurrencyLevel);
        sb.AppendFormat("    MaxRetries: {0}\n", transportConfig.MaxRetries);
    }

    var msmqSubscriptionStorageConfig = GetServiceBusConfig<MsmqSubscriptionStorageConfig>();
    if (msmqSubscriptionStorageConfig != null)
    {
        sb.Append("MsmqSubscriptionStorageConfig\n");
        sb.AppendFormat("    Queue: {0}\n", msmqSubscriptionStorageConfig.Queue);
    }

    return sb.ToString();
}

private static T GetServiceBusConfig<T>() where T : class
{
    // When the config is being overriden it will be in a group called serviceBus
    // If it's not being overriden then return the standard config from the app.config
    var config = (T)ConfigurationManager.GetSection(string.Format("serviceBus/{0}", typeof(T).Name))
                 ?? (T)ConfigurationManager.GetSection(typeof(T).Name);

    return config;
}
```

**Comment by adamralph** [comment]
Hi @ashokchebrolu, I'm not sure what your question is. Are you having problems upgrading?

BTW - we recommend upgrading a single major version at one time. I.e. you should first upgrade from Version 5.x to 6.x, and ideally deploy to production. After you have confident that everything is still working, you should then upgrade from Version 6.x to 7.x. Please see https://docs.particular.net/nservicebus/upgrades/ for more info.

**Comment by ashokchebrolu** [comment]
Thank you! :-)

**Comment by adamralph** [comment]
You're welcome.

BTW, some more info here: https://docs.particular.net/nservicebus/upgrades/support-policy#upgrading

> NServiceBus versions are wire-compatible, meaning the endpoints using different versions can exchange messages with each other.
> 
> However, some features might require data migration (e.g. converting from old to new format), and the conversion might be performed in the background after upgrade.
> 
> Therefore the recommended approach is to upgrade 1 major version at a time, including a full regression testing of the system and deployment to production.

I'll close this issue for now, but if you still have any specific problems, please feel free to raise a [support case](https://particular.net/support). We also have our [discussion forum](https://discuss.particular.net/) if you want to chat about this more generally.

**Comment by adamralph** [comment]
@ashokchebrolu have you been following the [upgrade guide for Version 5 to 6](https://docs.particular.net/nservicebus/upgrades/5to6/)?

**Comment by ashokchebrolu** [comment]
Yes, I upgraded NserviceBus 6.2 and I am seeing warning the interface IConfigurationSource is obsolete.
This is code snippet from this link is still using IConfigurationSource. 
 https://docs.particular.net/nservicebus/hosting/custom-configuration-providers

**6.x - 6.4 NServiceBus**
public class MyCustomConfigurationSource :
    IConfigurationSource
{
    public T GetConfiguration<T>() where T : class, new()
    {
        if (typeof(T) == typeof(RijndaelEncryptionServiceConfig))
        {
            var config = new RijndaelEncryptionServiceConfig
            {
                Key = "gdDbqRpqdRbTs3mhdZh9qCaDaxJXl+e6"
            };
            return config as T;
        }
        // leaving the rest of the configuration as is:
        return ConfigurationManager.GetSection(typeof(T).Name) as T;
    }
}

**Comment by adamralph** [comment]
@ashokchebrolu `IConfigurationSource` was deprecated in version 7.0. When you upgrade from version 5 to 6, you should be able to use that interface without problem.

If you like we can hop on a call and I can see if I can help you. Either drop me an email at adam.ralph@particular.net or raise a [support case](https://particular.net/support) and I'll set it up.
