### ISSUE TITLE
Dead-letter Forwarding is not working with transport version 8

### ISSUE THREAD

**Issue by welshdave** [Particular/NServiceBus.AzureServiceBus#737]
## Who's affected

Anyone updating from NServiceBus version 6 to version 7 and configuring queue/subscription dead-letter forwarding using `.ForwardDeadLetteredMessagesTo(Func<string, bool>, string)` API.

## Symptoms

Endpoing fails to start with exception System.InvalidOperationException: 'The entity error has an auto-forwarding policy to itself.'

## Original issue

Currently I have an azure worker role (using Azure Service Bus Transport) that is able to forward all dead lettered messages to a queue called "error". 
Updating to NServiceBus 7 I'm unable to do this. I get the following error:
System.InvalidOperationException: 'The entity error has an auto-forwarding policy to itself.'

I have some code that replicates the issue here (you'll need to update the connection string):
https://github.com/welshdave/NSBForwardingIssue

**Comment by SeanFeldman** [comment]
Thank you @welshdave.
This is a bug in the transport and we'll hotfix it.

**Comment by SeanFeldman** [comment]
Closed via 7e1d5bc88cf40031c9d6ba2f9203d6618d5956ae

**Comment by SeanFeldman** [comment]
@welshdave thank you for raising the issue.
A fix has been [release](https://discuss.particular.net/t/nservicebus-azure-transports-windowsazureservicebus-8-0-2-patch-release-available/722)
