### ISSUE TITLE
Test standard topology with a long running process

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#76]
Connects to https://github.com/Particular/EndToEnd/issues/2

As a part of NSB.ASB V7 testing, standard topology needs to be tested in the real azure environment as a long running process.

We should log anything that is not handled (using `appdomain.unhandledexception`) to see if we get anything from ASB library we didn't plan for.

- [x] create endurance test
- [ ] setup to run test in testing environment
   - [x] Setup Raygun application for exception tracking
   - [ ] Convert exception logging to Raygun
   - [ ] Setup octopus deployment

**Comment by SeanFeldman** [comment]
A good candidate for GH location is https://github.com/Particular/ProductionTests

**Comment by SeanFeldman** [comment]
The initial idea is to have a simple console app that sends/receives running for a few weeks. 

@Particular/azure should we also add pub/sub to that (for the `StandardTopology`)?

**Comment by SimonCropp** [comment]
If the tests do not need to span multiple versions then there is no reason to move them out of the main azure repro.

**Comment by SeanFeldman** [comment]
@SimonCropp these are not conventional test, but more of the endurance tests. Also, we don't know how small/big it will be, so it doesn't sound quite right to put it with the transport at this point.

Alternatively, we thought of a separate repo for those kind of tests/projects, but didn't want to increase # of repos that is already substantial.

**Comment by yvesgoeleven** [comment]
Just add a project to the asb solution, it's going to be very asb specific

**Comment by SimonCropp** [comment]
@SeanFeldman it may not seem right but it will result in significantly less fiction for you

**Comment by yvesgoeleven** [comment]
Separate repo is fine for me as well, the smaller repo's are the easier to maintain

**Comment by SeanFeldman** [comment]
@SimonCropp ok, we'll start simple, in the transport solution and if need to split it, we'll do so.
/cc @boblangley

**Comment by boblangley** [comment]
Setting up 2 tests to start:
* Long Running Process, sending and receiving messages at regular intervals
* Throttling test: Flood the bus with messages to introduce throttling

I will add a Solution Folder called Soak Tests, and create a Command Line project for each so we can run them as needed.

@Particular/azure Are these the right tests to setup to start and are there others that should be included as well?

**Comment by SeanFeldman** [comment]
For # 1 - that would be a soak test (@yvesgoeleven recommended 1msg/sec to begin with)
For # 2 - we should run it in a controlled environment, i.e. not let it run w/o manual intervention and supervision (or else will get _very_ expensive :smiley:)

**Comment by SeanFeldman** [comment]
@melkio could you connect with @boblangley to see what he's done on this?

**Comment by boblangley** [comment]
Added WIP pull request https://github.com/Particular/NServiceBus.AzureServiceBus/pull/110

**Comment by boblangley** [comment]
@SeanFeldman reviewed and is ready to merge the pull request once we are sure failing acceptance tests on build server are transient environmental issues and not pull related

**Comment by mikeminutillo** [comment]
@boblangley what is the status of this one? The plan of attack seems to imply that it is half done but it hasn't been updated in 2 weeks. Is there a test environment being provisioned for this?

**Comment by boblangley** [comment]
I am working on deployment / test environment and I have updated the description with remaining steps.

**Comment by yvesgoeleven** [comment]
@boblangley it's probably better to run the tests in a regular vm instead of a cloudservice in terms of costs. Other transports also seem to be working on tests similar/same as this, please sync up with them as well in terms of hosting https://github.com/Particular/EndToEnd/issues/2

**Comment by andreasohlund** [comment]
Is this one in progress? I propose we merge it into Particular/EndToEnd#2 and close this one

**Comment by boblangley** [comment]
I am all for merging this one and #106 into https://github.com/Particular/EndToEnd/issues/2. We decided to host the code here, but we should also move the tests over there as well.

**Comment by SeanFeldman** [comment]
@boblangley :+1: 
Are you going to move the [endurance tests](https://github.com/Particular/NServiceBus.AzureServiceBus/tree/b8fab982b207dcc99d16e6d2136e67bfaac11442/src/EnduranceTests) code out ?

**Comment by boblangley** [comment]
I am closing this and updating the description of https://github.com/Particular/EndToEnd/issues/2 to make sure it includes this scope. @SeanFeldman I will move the code out when https://github.com/Particular/EndToEnd/issues/2 is given the green light to proceed.
