### ISSUE TITLE
Duplicated subscriptions with endpoint-oriented topology

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#811]
## Who's affected

Anyone using endpoint-oriented topology with the legacy Azure Service Bus transport version 9 and above.

## Symptoms

When a subscribing endpoint creates its subscriptions, a duplicate subscription is created for each event. While subscriber is listening to only one of those, messages in the duplicate subscription are accumulated and could cause event overflow, impacting the entire namespace performance. Eventually, this can lead to degradation and interruption of the normal service operation.

## Workaround

A possible workaround is to manually modify the default rule for the original subscription to match the default rule of the duplicate subscription. After doing this, the duplicate subscription can be deleted. When the endpoint restarts it will no longer create the duplicate subscription. 
_Credit: @onesadjam_

## Will be there duplicate messages?

No. There will be no duplicated delivered to the subscribers as subscriber will only receive from a single subscription.

## Will be there duplicate messages in the migration mode?

No. There will be no duplicates delivered to the subscribers while the system is in the [migration mode](https://docs.particular.net/transports/azure-service-bus/legacy/migration).

**Comment by onesadjam** [comment]
A workaround that we employed is to manually modify the default rule for the original subscription to match the default rule of the duplicate subscription.  After doing this, the duplicate subscription can be deleted.  When the endpoint restarts it will no longer create the duplicate subscription.

**Comment by SeanFeldman** [comment]
That's correct. As Subscription creator won't find a mismatching rule in
the subscription it will probe. Great Adam! I'll add that as a viable
workaround.
