### ISSUE TITLE
Exceptions in recoverability policy do not trigger critical error

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.AzureServiceBus#818]
## Who's affected
Anyone using the transport.

## Symptoms
Exceptions thrown in recoverability policy are not propagated as critical error and hide the underlying infrastructure problems that user code could be responding to.

## Description
By not properly handling exceptions when the recoverability policy throws, and not raising a critical error, the transport does not allow taking an action when the underlying messaging infrastructure is partially failing.

**Comment by SeanFeldman** [comment]
Fixed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/5763dbe1050244522ca56263f9b0b30ed3e02a57
