### ISSUE TITLE
Support for custom subscription filter

### ISSUE THREAD

**Issue by tchelidze** [Particular/NServiceBus.AzureServiceBus#829]
Subscription filter is generated by `SqlSubscriptionFilter` with the following logic

```
$"[{Headers.EnclosedMessageTypes}] LIKE '%{eventType.FullName}%'"
```

Which is not sufficient for the following scenario.

Having a legacy message structure `LegacyNamespace.MessageA` which is used by an existing endpoint. Trying to introduce a new message, `NewNamespace.MessageA` (in a new endpoint) which is compatible with an existing one, hence ServiceBus message body generated by serializing legacy message successfully deserializes to a new message.

Filter generated by `SqlSubscriptionFilter`

```
[NServiceBus.EnclosedMessageTypes] LIKE '%NewNamespace.MessageA%'
```

is filtering out legacy messages.

With the ability to customize how subscription filter is generated, we would be able to generate the following filter

```
[NServiceBus.EnclosedMessageTypes] LIKE '%NewNamespace.MessageA%'
OR [NServiceBus.EnclosedMessageTypes] LIKE '%LegacyNamespace.MessageA%'
```
Which would pass both legacy and new messages.

**Comment by SeanFeldman** [comment]
@tchelidze it sounds like you have two distinct events that happened to overlap in their properties and name, but those are not the same event. Could you explain why you cannot have two different events and have the endpoint to subscribe to both?
Also, if this is affecting your production, please raise a support case here: https://particular.net/support

**Comment by tchelidze** [comment]
Hi @SeanFeldman 

Nope, it's exactly the same event. We decided to improve the structure of the event messages. Existing endpoints are currently using an old message. The plan is to gradually migrate all the existing endpoints as well as add new ones, which will use a new message structure.

**Comment by SeanFeldman** [comment]
Thank you, @tchelidze. If this is the same event and you're refactoring the namespace, could you have a handler on the subscriber side that that handles both `OldNamespace.MessageA` and `NewNamespace.MessageA`?

Note that this transport is a [legacy ASB transport](https://docs.particular.net/transports/azure-service-bus/legacy/) which is replaced by the [new ASB transport.](https://docs.particular.net/transports/azure-service-bus/).

**Comment by tchelidze** [comment]
Thank you @SeanFeldman for a good suggestion. It could be a workaround, though if we go that road, we have to upgrade all the endpoints at the same time. Say we release an `Endpoint1` which is publishing a new message, then we should also modify (add a handler to new message) and release all the endpoints which are subscribing to that message or its legacy counterpart.

**Comment by SeanFeldman** [comment]
I would first update the subscribers to subscribe to the new event type and release those. Only after that start publishing the new message. Otherwise, events of the new message type will be lost.

Another option is to introduce a custom outgoing pipeline behaviour to modify the message type in the headers. That way you can public both the old and the new event type with subscribers receiving both. Once all of the subscribers are modified to handle the new event type, you could remove the custom pipeline behaviour and the new events would be handled as new events, knowing that subscriptions are in place. Either way, it's a better approach than trying to add a new feature into the transport that will not serve multiple customers.

**Comment by tchelidze** [comment]
Thank you @seanfarmar 

Indeed the problem is solvable with both of the options. 

Though the first one requires careful coordination to keep track of which endpoints have subscribers for new messages and since the number of endpoints is high, so is the chance of losing messages. 

Regarding the second option, indeed it solves the problem from message publishing/sending prospective, but we still need to have 2 subscribers for the legacy and new message and do a manual map.

Since the system is in production I would like to take the safest option, first such would be customizing subscription filter or alternatively adding supporting subscribers to old messages

Regarding the usage of the suggested feature, it opens up a door to filter the message by additional property rather than its CLR type. 
   Say, you have the `Activity` message, which gets published for various kinds of activities, but the subscriber is only interested in few, then by promoting `Activity.ActivityType` to message header and having the ability to customize filter, you would reduce the number of received (and then in memory filtered) messages significantly. 
  Or say (migration scenario) you have following endpoints, `Endpont1V1`, `Endopint1V2`, `Endpoint2V1` and `Endpoint2V2` living side by side and the plan is `V2` endpoints to listen for `V2` endpoint messages only and `V1` to `V1`. Then simply adding endpoint version to message header and customizing filter, it will become easier.

**Comment by danielmarbach** [comment]
Have you considered introducing a base event type or interface that both
inherit from?

https://docs.particular.net/samples/versioning/

Bitchiko Tchelidze <notifications@github.com> schrieb am Di., 18. Juni
2019, 11:34:

**Comment by tchelidze** [comment]
@SeanFeldman Regarding having 2 subscription for the legacy and new messages. My colleague just let me know that it's not possible in our scenario, since both legacy and new messages have **the same name** and different namespace. While subscription name is `"{EndpointName}{Message class name}"` both of the handler will live under the same subscription.

@danielmarbach We haven't. But it could be an option, i'll look into it. Thank you

**Comment by DavidBoike** [comment]
@tchelidze Another possibility is to introduce an [outbound behavior](https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors) (probably on IOutgoingPhysicalMessageContext) that would modify the Enclosed Message Types header on the way out. You would add this to the publisher of any of the affected message types, and if it contained, for example, `LegacyNamespace.MessageA`, you would update it to contain both that AND `NewNamespace.MessageA`. Then all subscribers, whether updated or not, would correctly find and process it with their default subscription filters.

**Comment by SeanFeldman** [comment]
This is a legacy transport and new features won't be added.
The new transport (https://docs.particular.net/transports/azure-service-bus/) is what we recommend customers moving forward.

**Comment by tchelidze** [comment]
Just in case someone needs that feature, i've implemented that in my fork which can be found [here](https://github.com/tchelidze/NServiceBus.AzureServiceBus/tree/master)
