### ISSUE TITLE
Validate SendVia feature

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#83]
[**Originally from @abombss**](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/78):
> Also, you can combine the OnComplete Tasks and the incoming Complete in Task.All instead of doing them serially, this will cut down on latency by sending everything together and potentially batching under the covers. The TX ensures the incoming complete won't happen unless all the Sends succeed as well.

TODO
- [x] Verify that SendVia is working as designed, including test scenarios validation

**Comment by yvesgoeleven** [comment]
Documentation moved to https://github.com/Particular/docs.particular.net/issues/1257

Don't we have enough tests now that validate this? anything missing?

**Comment by SeanFeldman** [comment]
With bug fix #149 we have addressed incorrect default for `SendVia`.
The concern in general description is also [addressed](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/144).

@yvesgoeleven anything else missing for this or we can close it?
