### ISSUE TITLE
NServiceBus.Transport.Encoding header not passed to pipeline

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#833]
For unknown reasons the `NServiceBus.Transport.Encoding` header is not passed to the processing pipeline. This results in the header to not be visible in the pipeline thus not in ServiceControl/ServiceInsight.

This header provides essential information on the body format and should IMHO not be filtered. It provides value especially when using for example understanding transport configuration based on payload.

```c#
foreach (var h in context.MessageHeaders)
{
    Console.WriteLine($"{h.Key} {h.Value}");
}
```

![image](https://user-images.githubusercontent.com/152998/64430022-a22d9680-d0b7-11e9-9881-c96ffc6fee46.png)

![image](https://user-images.githubusercontent.com/152998/64430079-c7baa000-d0b7-11e9-97d5-f5141b29a721.png)

**Comment by SeanFeldman** [comment]
Thank you, @ramonsmits.
Could you add the steps you took to find out this header was missing?

**Comment by ramonsmits** [comment]
@SeanFeldman Added screenshots, it seems the following line causes this:

https://github.com/Particular/NServiceBus.AzureServiceBus/blob/cc85bf4aadae802fd1969aa869bd5cf2fca638b0/src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs#L64

**Comment by SeanFeldman** [comment]
> For unknown reasons the NServiceBus.Transport.Encoding header is not passed to the processing pipeline.

The header is not passed into the pipeline as it is not NServiceBus Core header that is required. It's transport-specific. The header is removed once the body of the native has been read successfully:
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/cc85bf4aadae802fd1969aa869bd5cf2fca638b0/src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs#L58

The header is created again when the messages are sent out by the transport:
https://github.com/Particular/NServiceBus.AzureServiceBus/blob/cc85bf4aadae802fd1969aa869bd5cf2fca638b0/src/Transport/Sending/BatchedOperationsToBrokeredMessagesConverter.cs#L169-L188

Therefore it's normal not to have this information in the Core pipeline.
Unless you think this is causing a bug behaviour to NServiceBus Core, we can close the issue.

**Comment by ramonsmits** [comment]
It is valuable information for diagnosing. There are no drawbacks in filtering away the header. To me it is filtering behavior that is not required. There is currently no other way to retrieve these headers and they are not logged either. I tried a [transport mutator](https://docs.particular.net/nservicebus/pipeline/message-mutators#transport-messages-mutators) but there the header is also already gone.

As this is part of the payload on the wire I consider this a bug and this data should IMHO be part of the message send to audit.

**Comment by SeanFeldman** [comment]
@ramonsmits this information bis internal to the transport. It was never intended for users. The issue was originally raised with an intent that the absence of the header is causing SC/SI to fail. If that would be the case, then it would need to be fixed. Otherwise it's working as expected.

Could you please indicate what bug does it cause?

**Comment by ramonsmits** [comment]
@SeanFeldman No, in the description I don't state SI is failing due to the missing header. Only that the header is not visible in header collection of SI. Meaning, the actual message with headers + body that went over the wire is not visible in SI as such which makes its audit capability incomplete as basically the data stored for auditing got modified.

**Comment by SeanFeldman** [comment]
Closing this for reasons stated above.
We can discuss offline if required.
Thank you.
