### ISSUE TITLE
Allow custom topology creation

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#84]
To be able to create a custom Topology, the following changes are needed in the transport
- `DeterminesBestConnectionStringForAzureServiceBus` to be public
- `NamingConventions` to be public and allow setting of the custom conventions

**Comment by SimonCropp** [comment]
@SeanFeldman @dbelcham for people who come here from the release notification can you please link to the feature doco inside the issue description
