### ISSUE TITLE
Maximum batch size for brokered messages is not calculated properly

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureServiceBus#86]
ASB library [`BrokeredMessage.Size`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.brokeredmessage.size.aspx) does not report message total size correctly. Data stored in [`BrokeredMessage.Properties`](https://msdn.microsoft.com/en-us/library/microsoft.servicebus.messaging.brokeredmessage.properties.aspx) is not taken into consideration.

Repro code: [link](https://gist.github.com/yvesgoeleven/681b211f585c3402bf98)

TODO
* [x] Implementation
* [ ] Document
  * default message size padding 5%
  * configuration option

**Comment by abombss** [comment]
Can this be overcome with a simple helper, NSB custom headers are all strings should it should be pretty simple calculate the size of anything in BrokeredMessage.Properties and then add a little overhead for some of the BrokeredMessage built-in props like To, From, ReplyTo, PartitionKey, etc, and then even add a little extra padding if needed.

The retry / fallback can also take a pretty simplistic binary approach to split the batch if it fails.  Just keep cutting the batch in half until it succeeds.

Not ideal nor optimal but certainly doable and the benefits outweigh the the loss of not being able to batch.

**Comment by SeanFeldman** [comment]
That's the plan @abombss 
We won't wait for MSFT team, though would be nice if they'd internalize batching.

**Comment by yvesgoeleven** [comment]
doco https://github.com/Particular/docs.particular.net/issues/1273
