### ISSUE TITLE
MaxDeliveryCount set to int.MaxValue can result in inifinite retries

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureServiceBus#887]
**Describe the bug**

In [ASBL v8 it was decided to set MaxDeliveryCount is to int.MaxValue to ensure messages are not dead-lettered accidentally and to remove the dependency on the endpoints' immediate retries configuration](https://docs.particular.net/transports/upgrades/asb-7to8#queue-and-subscription-maxdeliverycount). This default was copied to ASBS from inception.

- https://github.com/Particular/NServiceBus.AzureServiceBus/blob/1d01629441ca5a0b50cf37d296f71383220c7fcd/src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs#L12
- https://github.com/Particular/NServiceBus.AzureServiceBus/blob/1d01629441ca5a0b50cf37d296f71383220c7fcd/src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs#L13

However, this can cause issues where messages processing keeps failing. Basically resulting in "infinite" immediate retries. This results in excessive logging and excessive resource utilization.

Workarounds:

- Manually set the value for each queue using Service Bus Explorer: https://github.com/paolosalvatori/ServiceBusExplorer
- According to https://docs.particular.net/transports/upgrades/asb-7to8#queue-and-subscription-maxdeliverycount these seems to be a workaround which requires new deployment.

In the users scenarios a `MessageSizeExceededException` occurs, this results in an infinite amount of immediate retries due to `int.MaxValue`. Clearly this is not what you would want. A more sane limit for such scenarios should be used like 10 or 15 which already is a *very* high number for immediate retries. More attempts should happen via delayed retries.

**To Reproduce**
Steps to reproduce the behavior. If you have a repro repository, provide a link.

**Expected behavior**

**Versions:**
 - NuGet package: [e.g. 1.0.0-alpha0073]
 - OS: [e.g. Windows 10 build 1803]
 - .NET Version [e.g. .NET Core 2.1.300]

**Additional context**
- Code repro
- Screenshot

**Comment by SeanFeldman** [comment]
Please note that this transport is [deprecated](https://docs.particular.net/nservicebus/upgrades/supported-versions#transport-packages-nservicebus-azure-transports-windowsazureservicebus).

I've also left an [extensive comment](https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/138#issuecomment-628371762) on a similar issue in the ASB (new) repository to cover this issue.

**Comment by DavidBoike** [comment]
This package is deprecated and will no longer receive updates, patches, or fixes. See https://particular.net/blog/the-end-of-the-azure-service-bus-legacy-transport for more details.
