### ISSUE TITLE
Support CorrelationFilters

### ISSUE THREAD

**Issue by thecrockster** [Particular/NServiceBus.AzureServiceBus#952]
SqlFilter is used by default for subscription rules. Has any thought been given to allow CorrelationFilter. MS docs suggest "_Whenever possible, applications should choose correlation filters over SQL-like filters because they're much more efficient in processing and have less impact on throughput_".

https://docs.microsoft.com/en-us/azure/service-bus-messaging/topic-filters#filters

**Comment by SeanFeldman** [comment]
@thecrockster, yes, there was. Please see #703.

**Comment by thecrockster** [comment]
Could you have a config option on the Asb Transport to turn on exact filter matching...use CorrelationFilter instead of SqlFilter, set the correlationId to eventType.FullName (when creating a new RuleDescription) and set the correlationId on the native message to eventType.FullName?

**Comment by SeanFeldman** [comment]
@thecrockster, I don't follow. Did you look at the thread I have linked to? If you do what you're saying, it will be breaking the message hierarchy (especially events). Have you considered that? If you want to expand the discussion and get into details specific to your use case, I suggest raising a support case, mentioning this thread.

**Comment by DavidBoike** [comment]
This package is deprecated and will no longer receive updates, patches, or fixes. See https://particular.net/blog/the-end-of-the-azure-service-bus-legacy-transport for more details.
