### ISSUE TITLE
StartupCheckResult

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#96]
Figure out why there is a StartupCheckResult callback in the transport seam and implement it if necessary

**Comment by melkio** [comment]
StartupCheckResult is used as a pre-checker before starting Receiving and Sending feature in core.
Do we have any check to satisfy before giving back the control to core?

Msmq transport, for example, use this "extension point" to verify and log if queues permissions are properly configured.

**Comment by yvesgoeleven** [comment]
We should definitly validate the following
- At least one connection string /  namespace is set
- If create queues is on, we should validate that those connectionstrings have manage permissions

**Comment by melkio** [comment]
If create queues is off, do we have to check that queues already exist?

**Comment by yvesgoeleven** [comment]
You would need manage rights to check that, which is not always given when create queues is off. So I would say no?

**Comment by melkio** [comment]
:+1:

**Comment by SeanFeldman** [comment]
@melkio please update the general description with what's left and either close it or move back if needed. Thank you.

**Comment by SeanFeldman** [comment]
Considered done. @melkio please reopen if not.
