### ISSUE TITLE
Integrate error queue

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.AzureServiceBus#99]
Error queue is injected in messagepump init, but we're not using it, figure out why it is injected and what we are supposed to do with it

**Comment by SeanFeldman** [comment]
Example: messages failing deserialization are natively DLQ-ed. Should those be sent to the error queue instead?

**Comment by SeanFeldman** [comment]
### MSMQ

`PushSetting.ErrorQueue` is used to get the machine name to ensure [error queue is on the same machine ](https://github.com/Particular/NServiceBus/blob/2b76f2669aca24abc020d8022b1372cf1cfeff6f/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L37) as the endpoint (MSMQ requirement) and passed into [receiver strategy](https://github.com/Particular/NServiceBus/blob/2b76f2669aca24abc020d8022b1372cf1cfeff6f/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L155) to [deal with failed messages](https://github.com/Particular/NServiceBus/blob/2b76f2669aca24abc020d8022b1372cf1cfeff6f/src%2FNServiceBus.Core%2FTransports%2FMsmq%2FReceiveWithNativeTransaction.cs#L35).

### SQL Transport

Error queue passed into [receiver strategy](https://github.com/Particular/NServiceBus.SqlServer/blob/0a431ec41ed4a7fe3b6666d4b92105c5fcdab28d/src/NServiceBus.SqlServer/Receiving/MessagePump.cs#L144) to [deal with poisonous messages](https://github.com/Particular/NServiceBus.SqlServer/blob/0a431ec41ed4a7fe3b6666d4b92105c5fcdab28d/src/NServiceBus.SqlServer/Receiving/ReceiveWithSendsAtomicWithReceiveTransaction.cs#L30).

### RabbitMQ

[Deal with failed messages](settings.ErrorQueue) by passing error queue into [`PosinousMessageForwarder`](https://github.com/Particular/NServiceBus.RabbitMQ/blob/core-v6-update/src/NServiceBus.RabbitMQ/PoisonMessageForwarder.cs#L30).

**Comment by SeanFeldman** [comment]
Consider passing error queue from `MessagePump.OnError()` into `ITopologyOperator.OnError()` so that it can be passed into `MessageReceiveNotifier.Initialize()` and be used in `ProcessMessageAsync()` to move message into error queue.

**Comment by SeanFeldman** [comment]
Raise [an issue #632](https://github.com/Particular/PlatformDevelopment/issues/632) in PlatformDevelopment

**Comment by SeanFeldman** [comment]
We don't need to integrate with the error queue since the transport is DLQing natively messages that are failing serialization.
